### ISSUE TITLE
Publish Action to GitHub Marketplace and get Verified Creator status

### ISSUE THREAD

**Issue by srgoni** [securego/gosec#1004]
### Summary 

Using the gosec Action is currently not possible when a restrictive Action policy is set on a repository or an organization.

Please publish the gosec action to the GitHub marketplace and obtain [GitHub Verified Creator](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#about-badges-in-github-marketplace) status.

### Steps to reproduce the behavior
1. Open the settings for a GitHub repository
2. Open the Actions -> General settings
3. Tick the "Allow <organization>, and select non-<organization>, actions and reusable workflows"
4. Try to run a workflow that uses the securego/gosec action

### gosec version
2.17.0

### Go version (output of 'go version')
N/A

### Operating system / Environment
N/A

### Expected behavior
The workflow is executed.

### Actual behavior
The workflow doesn't run, instead GitHub displays the following error when opening the Action output:
```
securego/gosec@master is not allowed to be used in <organization/repo>. Actions in this workflow must be: within a repository owned by <organization>, created by GitHub, or verified in the GitHub Marketplace.
```

**Comment by ccojocar** [comment]
The action is now published in the marketplace: https://github.com/marketplace/actions/gosec-security-checker
