### ISSUE TITLE
gosec failing to identify SQL injection

### ISSUE THREAD

**Issue by santikris2003** [securego/gosec#1013]
### Steps to reproduce the behavior : this is my sample test code 
import (
    "database/sql"
    "fmt"
    "log"

    "github.com/lib/pq"
)

func main() {
    connStr := "user=pqgotest dbname=pqgotest sslmode=verify-full"
    db, err := sql.Open("postgres", connStr)
    if err != nil {
        log.Fatal(err)
    }

    id := "'58'"
    query := fmt.Sprintf("SELECT name, email FROM users WHERE ID = %s", id)
    rows, err := db.Query(query)

    // Don't forget to check for errors and handle the rows returned.
}

### Go version (output of 'go version')
gosec -version
Version: dev
Git tag: 
Build date: 

### Operating system / Environment
Mac
### Expected behavior
it should detect SQL injection vulnerability 
### Actual behavior
in the results output did not detect SQL injection for my sample test code as per rules G201 or G202

**Comment by audunmo** [comment]
I'm failing to see the injection in the reproduction code. There's no user input here, is there?

**Comment by audunmo** [comment]
Though arguably, gosec should enforce that variables are passed to queries using prepared statements. Not sure I love that as a default behavior though, but I can see situations where I'd like to have that as a flag

**Comment by santikris2003** [comment]
But shouldn't gosec scan atleast flag that variables in SQL queries are passed without prepared statements or parametrized queries especially in cases where variables are directly inputted with SQL query or concatenated with SQL query which could result in a potential SQL Injection , developers  can then decide if they should consider that flagged event as False Positive or plan for a fix

**Comment by santikris2003** [comment]
> I'm failing to see the injection in the reproduction code. There's no user input here, is there?

I just used this sample example to test if gosec atleast flags such SQL queries where data is directly inputted or concatenated with query without any prepared statement or parametrised queires

**Comment by audunmo** [comment]
@santikris2003 if you pass something like os.Args[1] you'll see it shows that user input is being passed in. Variables being passed in to queries isn't scary in and of itself, if the variable contents are not user controlled. Gosec is actually "smart" in this sense, as it's evaluating if the variable is potentially user controlled or not. This lowers the amount of false-positive findings

I do agree though that I'd like to see some way of enforcing the use of prepared statements

**Comment by santikris2003** [comment]
@audunmo  thats good to know that "Gosec is actually "smart" in this sense, as it's evaluating if the variable is potentially user controlled or not. This lowers the amount of false-positive findings" that make sense to me.
I tried with another code sample where user input is actually inputted by used through a web form just to check if Gosec is not resulting in False Negatives
Code Sample used:

package main
import 
	( "database/sql" 
		"fmt" 
		"html/template" 
		"log"
		 "net/http" 
		"strings"
 		"github.com/lib/pq"
	)
var templates = template.Must(template.ParseGlob("templates/*.html"))
func main() 
	{
 	http.HandleFunc("/", indexHandler) 
	http.HandleFunc("/query", queryHandler)
	log.Fatal(http.ListenAndServe(":8080", nil))
	}
func indexHandler(w http.ResponseWriter, r *http.Request) { 
err := templates.ExecuteTemplate(w, "index.html", nil) i
f err != nil {  
http.Error(w, err.Error(), http.StatusInternalServerError) 
}
}
func queryHandler(w http.ResponseWriter, r *http.Request) { 
connStr := "user=pqgotest dbname=pqgotest sslmode=verify-full" 
db, err := sql.Open("postgres", connStr) 
if err != nil { 
 http.Error(w, err.Error(), http.StatusInternalServerError)  
 return 
 }
  defer db.Close()
 // Get user input from the HTML form 
username := r.FormValue("username")
 // WARNING: This approach is highly insecure and vulnerable to SQL injection. // It is only for demonstration purposes and should NEVER be used in a production environment. 
query := fmt.Sprintf("SELECT name, email FROM users WHERE username = '%s'", username)
 rows, err := db.Query(query) 
if err != nil {  
http.Error(w, err.Error(), http.StatusInternalServerError)  
return } 
defer rows.Close()
 // Process the rows here 
var results []Result
 for rows.Next() {  
var name, email string  
if err := rows.Scan(&name, &email); err != nil {   
http.Error(w, err.Error(), http.StatusInternalServerError)  
 return  
}  
results = append(results, Result{Name: name, Email: email}) 
}
 err = templates.ExecuteTemplate(w, "results.html", results) 
if err != nil {  
http.Error(w, err.Error(), http.StatusInternalServerError) 
}
}
type Result struct { 
Name string 
Email string
}	

strange gosec did not flag this one as well for SQL Injection , here username is directly inputted to SQL Query in fmt.Sprintf from the User Input HTML Form

**Comment by santikris2003** [comment]
And yes  it is good to have some way of enforcing the use of prepared statements

**Comment by santikris2003** [comment]
thanks for checking but this is the output I get of gosec . run
$ gosec .
[gosec] 2023/09/19 20:04:34 Including rules: default
[gosec] 2023/09/19 20:04:34 Excluding rules: default
[gosec] 2023/09/19 20:04:34 Import directory: /Users/santikris/Downloads/temp1
Results:

Golang errors in file: [.]:

  > [line 0 : column 0] - importing dir ".": test.go:3:3: illegal character U+00A0 (and 7 more errors)



Summary:
  Gosec  : dev
  Files  : 0
  Lines  : 0
  Nosec  : 0
  Issues : 0

**Comment by audunmo** [comment]
The code in that foldee isn't compiling. That's not a gosec error

**Comment by santikris2003** [comment]
I removed the illegal char errors still not seeing the SQL injection Flagged 

$gosec --no-fail  .
[gosec] 2023/09/19 20:14:25 Including rules: default
[gosec] 2023/09/19 20:14:25 Excluding rules: default
[gosec] 2023/09/19 20:14:25 Import directory: /Users/santikris/Downloads/temp1
[gosec] 2023/09/19 20:14:26 Checking package: main
[gosec] 2023/09/19 20:14:26 Checking file: /Users/santikris/Downloads/temp1/test.go
Results:

Golang errors in file: [/Users/santikris/Downloads/temp1/test.go]:

  > [line 3 : column 3] - "database/sql" imported and not used

  > [line 8 : column 3] - "strings" imported and not used

  > [line 9 : column 3] - could not import github.com/lib/pq (invalid package name: "")

  > [line 13 : column 2] - unexpected semicolon or newline before {

  > [line 15 : column 28] - undefined: queryHandler

  > [line 19 : column 55] - expected ';', found i

  > [line 31 : column 8] - undefined: db

  > [line 36 : column 14] - undefined: db



[/Users/santikris/Downloads/temp1/test.go:16] - G114 (CWE-676): Use of net/http serve function that has no support for setting timeouts (Confidence: HIGH, Severity: MEDIUM)
    15: 	http.HandleFunc("/query", queryHandler)
  > 16: 	log.Fatal(http.ListenAndServe(":8080", nil))
    17: 	}



Summary:
  Gosec  : dev
  Files  : 1
  Lines  : 59
  Nosec  : 0
  Issues : 1

**Comment by audunmo** [comment]
Your code is still not compiling. That's what these errors are.

**Comment by audunmo** [comment]
I reckon those issues are still causing compilation failures that are messing up gosec's ability to analyze the AST. Resolve those first

**Comment by santikris2003** [comment]
thanks for the responses , now I got the SQL Injection after correcting it with an IDE
[gosec] 2023/09/19 20:27:37 Including rules: default
[gosec] 2023/09/19 20:27:37 Excluding rules: default
[gosec] 2023/09/19 20:27:37 Import directory: /Users/santikris/Downloads/temp1
[gosec] 2023/09/19 20:27:38 Checking package: main
[gosec] 2023/09/19 20:27:38 Checking file: /Users/santikris/Downloads/temp1/test.go
Results:


[/Users/santikrisDownloads/temp1/test.go:16] - G114 (CWE-676): Use of net/http serve function that has no support for setting timeouts (Confidence: HIGH, Severity: MEDIUM)
    15: 	http.HandleFunc("/query", queryHandler)
  > 16: 	log.Fatal(http.ListenAndServe(":8080", nil))
    17: 	}



[/Users/santikris/Downloads/temp1/test.go:35] - G201 (CWE-89): SQL string formatting (Confidence: HIGH, Severity: MEDIUM)
    34: // WARNING: This approach is highly insecure and vulnerable to SQL injection.// It is only for demonstration purposes and should NEVER be used in a production environment.
  > 35: query := fmt.Sprintf("SELECT name, email FROM users WHERE username = '%s'", username)
    36: rows, err := db.Query(query)



Summary:
  Gosec  : dev
  Files  : 1
  Lines  : 59
  Nosec  : 0
  Issues : 2

**Comment by audunmo** [comment]
Super! Please close the issue 😊

**Comment by santikris2003** [comment]
Thank You I have closed the ticket now appreciate all the help rendered to me :)
