### ISSUE TITLE
Gosec using too much parallelism on CI

### ISSUE THREAD

**Issue by danielmitre** [securego/gosec#1014]
### Summary 

As our projects grew we noticed CircleCI getting OOM occasionally, even on 8GBs instances.

I intended to profile which rules are using most resources when I found Gosec uses all the cores (it thinks) are available by default:
https://github.com/securego/gosec/blob/aebe20cfba724c45b6d6a2d8946ffa41a00f628c/cmd/gosec/main.go#L120

Which seems pretty much some problems CircleCI points ([link1](https://circleci.com/docs/configuration-reference/#resourceclass), [link2](https://support.circleci.com/hc/en-us/articles/360005442714-Your-test-tools-are-smart-and-that-s-a-problem-Learn-about-when-optimization-goes-wrong-)):

> Java, Erlang and any other languages that introspect the /proc directory for information about CPU count may require additional configuration to prevent them from slowing down when using the CircleCI resource class feature. Programs with this issue may request 32 CPU cores and run slower than they would when requesting one core. Users of languages with this issue should pin their CPU count to their guaranteed CPU resources.

### Steps to reproduce the behavior

Run this program inside a CircleCI Docker instance:

```go
package main

import (
	"fmt"
	"runtime"
)

func main() {
	fmt.Printf("You have %d cores\n", runtime.NumCPU())
}
```

I tested on a 4 vCPUs instance and it outputed:
```
You have 36 cores
```

### gosec version

v2.17.0

### Go version (output of 'go version')

go version go1.19.1 linux/amd64

### Operating system / Environment

A CircleCI large Docker instance.

```
uname -a
Linux dbe19358977c 5.15.0-1039-aws #44~20.04.1-Ubuntu SMP Thu Jun 22 12:21:12 UTC 2023 x86_64 GNU/Linux
```

### Expected behavior

To use only the available cores.

It could even default to no concurrency if the "CI" environment is set and we update the README.md documenting  `-concurrency`.

### Actual behavior

Trying to use all the cores of the host.

**Comment by ccojocar** [comment]
Thanks for raising this issue but you can configure the concurrency via the flag if you don't want to use the default setting.
