### ISSUE TITLE
"G602 (CWE-118): Potentially accessing slice out of bounds" false positive

### ISSUE THREAD

**Issue by vitaly-zdanevich** [securego/gosec#1024]
![image](https://github.com/securego/gosec/assets/3514015/c7083228-d02d-4f19-859b-002ce32036e1)

I cannot reproduce this on minimum example, but as you see on the screenshot - we check `if len()`.

Here no errors:
```
package main

import "fmt"

func main() {
	m := []string{"a", "b"}
	fmt.Println(m[0])
}
```

### gosec version
`dev`

### Go version
go1.21.1

### Operating system
Gentoo linux amd64

**Comment by ccojocar** [comment]
Thanks for providing this issue but I need a minimum source code sample with which I could reproduce this issue. The len check is already covered in tests therefore I am going to close this issue.
