### ISSUE TITLE
G304 reasoning?

### ISSUE THREAD

**Issue by KaibutsuX** [securego/gosec#1031]
### Summary 

Can someone provide the reasoning for G304's inclusion as a security risk?

I'm thinking specifically of linux, but in even Window's and Mac's cases, attempting to read files outside the current user's (or running processes) home directory should result in a EACCESS error.

Is this rule attempting to force developers to consider access concerns that that filesystem may allow?

By "fixing" this issue, I simply see developers providing large (and difficult to maintain) maps of safe and unsafe directories on the underlying filesystem where proper permissions are not enforced.

The 304 documentation uses `/safe/path/../../private/path` as an example, but if this path was `/home/me/../../etc/ssh` then the underlying filesystem would deny the access (assuming not running as root). The only way I see this being relevant is if these 'safe' and 'private' paths look something like `/home/my/stuff/../please/dont/read/these/files`, which doesn't really strike me as a security issue.

**Comment by ccojocar** [comment]
This rule tries to detect possible taint input vulnerabilities. It's true that sometimes they are mitigated by the OS but it is not always the case and also OSes can have different implementations.

**Comment by KaibutsuX** [comment]
That seems overly broad and ambitious. Seems equivalent to scanning for `fmt.Printf("%s\n", myPrivateKey)`
