### ISSUE TITLE
Update to @latest ignores #nosec annotation

### ISSUE THREAD

**Issue by Integralist** [securego/gosec#1044]
### Summary 

Latest release (2.18.1) causes `// #nosec` to be ignored.

<img width="1357" alt="Screenshot 2023-10-13 at 14 13 57" src="https://github.com/securego/gosec/assets/180050/0b4df60a-0304-4c08-a346-d0bdba9c3268">

### Steps to reproduce the behavior

I have a bunch of code that looks like this...

```go
// #nosec
if file, err = os.Open(path); err == nil { ... }
```

### gosec version

Should be latest (as this error happened the moment I noticed: `go: downloading github.com/securego/gosec/v2 v2.18.1` in my terminal), although I've just now noticed that things aren't quite as clear...

<img width="800" alt="Screenshot 2023-10-13 at 14 10 02" src="https://github.com/securego/gosec/assets/180050/5534cadf-0280-42f4-83a5-75f25c862a4a">

### Go version (output of 'go version')

```
go version go1.21.3 darwin/arm64
```

### Operating system / Environment

```
Darwin D3496LK9V7 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64
```

### Expected behavior

No warnings/errors reported about these items because I have them annotated with `#nosec`.

### Actual behavior

The `#nosec` annotation is being ignored.

**Comment by ccojocar** [comment]
It needs to be placed on the line where the issue is reported not above, like this:
```
if file, err = os.Open(path); err == nil /* #nosec */ { ... }
```

**Comment by Integralist** [comment]
@ccojocar interesting. thanks for clarifying.

Has this change in location happened recently because I've not had an issue with gosec here for years (i.e. I've been ignoring certain issues just above the line for a long time).

If this is a change introduced with the latest version then fine, but it's definitely unexpected.

**Comment by ccojocar** [comment]
Yes, it is recent change. Ignoring the line where the issue is reported makes more sense than ignoring the entire statement.

**Comment by tbailey** [comment]
I ran into this issue too.  I was able to get my build passing by inlining the annotated statements, and in one case refactoring the structure of my code.  

In my opinion, this feels like a breaking change as it states in the docs that annotating a block with #nosec stops the processing of deeper nodes in the AST.  https://github.com/securego/gosec#annotating-code

Just a heads up you may want to update your docs since it wasn't readily apparent how I should fix this.

**Comment by Integralist** [comment]
> In my opinion, this feels like a breaking change

I would agree.

**Comment by rounak-adhikary** [comment]
@ccojocar what is the correct way to annotate tlsconfig related lines of code? I am getting errors which I have tried to suppress as shown below 
```
[/root/terraform-provider-ome/clients/client.go:109] - G402 (CWE-295): TLS InsecureSkipVerify may be true. (Confidence: LOW, Severity: HIGH)
    108:                        TLSClientConfig: &tls.Config{
  > 109:                                InsecureSkipVerify: opts.SkipSSL, // #nosec G402
    110:                                RootCAs:            pool,



[/root/terraform-provider-ome/clients/client.go:94] - G402 (CWE-295): TLS InsecureSkipVerify may be true. (Confidence: LOW, Severity: HIGH)
    93:                         TLSClientConfig: &tls.Config{
  > 94:                                 InsecureSkipVerify: opts.SkipSSL, /* #nosec G402 */
    95:                         },
```

I also tried
```
[/root/terraform-provider-ome/clients/client.go:94] - G402 (CWE-295): TLS InsecureSkipVerify may be true. (Confidence: LOW, Severity: HIGH)
    93:                         TLSClientConfig: &tls.Config{
  > 94:                                 /* #nosec */ InsecureSkipVerify: opts.SkipSSL,
    95:                         },
```
None of the inlining seems to work.

**Comment by tbailey** [comment]
@rounak-adhikary This worked for me, I had to break the setting out from being nested in the struct.
```
	tlsConfig := &tls.Config{
		MinVersion: tls.VersionTLS12,
	}
	tlsConfig.InsecureSkipVerify = cfg.Insecure // #nosec G402
```

**Comment by Integralist** [comment]
@tbailey oof 🙁 thanks for sharing as I was confused about why things weren't working for me. Unfortunate that you have to set the field separately though.
