### ISSUE TITLE
invalid value "-incorrect" for flag -test1: flag value cannot start with -

### ISSUE THREAD

**Issue by skabashnyuk** [securego/gosec#1052]
### Summary 
The test output of coverage action has some strange output 
```
invalid value "-incorrect" for flag -test1: flag value cannot start with -
``` 
![Знімок екрана 2023-10-18 о 15 38 08](https://github.com/securego/gosec/assets/1614429/c473c194-160e-4ab3-bdab-cc472e02da80)

### Steps to reproduce the behavior
Review https://github.com/securego/gosec/actions/runs/6559222860/job/17814503943

### gosec version
 current
### Go version (output of 'go version')
unknown

### Operating system / Environment
unknown
### Expected behavior
Ginko should not show error messages about incorrect parameters
### Actual behavior
Ginko shows an error message about incorrect parameters

**Comment by ccojocar** [comment]
fixed by https://github.com/securego/gosec/pull/1051
