### ISSUE TITLE
Docker image for linux/arm64 contains binary built for linux/amd64

### ISSUE THREAD

**Issue by chrisa-arm** [securego/gosec#1060]
### Summary 

The `linux/arm64` variant of the Docker image uses the wrong target architecture when building the `gosec` binary because it appears to be hardcoded to use `linux/amd64` in the `Makefile`.

https://github.com/securego/gosec/blob/55d79496019a560e16e73e1948dee20a1fad631a/Makefile#L78-L79

You can see this happening in the build output:

https://github.com/securego/gosec/actions/runs/6610375096/job/17952178215#step:13:613

### Steps to reproduce the behavior

Try to run the Docker image on an `aarch64` Linux host.

### gosec version

2.18.2

### Go version (output of 'go version')

N/A

### Operating system / Environment

Linux aarch64

### Expected behavior

Calling `docker run` with the `gosec` image on a Linux `aarch64` host should work.

### Actual behavior

```
$ uname -m
aarch64
$ docker run -it --rm securego/gosec:2.18.2
/bin/entrypoint.sh: line 11: /bin/gosec: cannot execute binary file: Exec format error
$ docker run -it --rm --entrypoint /bin/sh securego/gosec:2.18.2
# readelf -h /bin/gosec | grep Machine
  Machine:                           Advanced Micro Devices X86-64
```

**Comment by ccojocar** [comment]
We don't support ARM on docker image. It is built only for x86-64. Please feel free to contribute this if you need it. Thank you

**Comment by chrisa-arm** [comment]
OK, fair enough but the release pipeline appears to be configured to build a Docker image that specifically includes the `linux/arm64` platform target:

https://github.com/securego/gosec/blob/64bbe901441ed79664986b3d056558b256af07d9/.github/workflows/release.yml#L62-L66

And this is published to DockerHub:

```
❯ docker manifest inspect securego/gosec:2.18.2
...
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1626,
         "digest": "sha256:9ff79cda20791835aef381554b62075d787145d5daed8a16b89d59fc29418f03",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
...
```

**Comment by ccojocar** [comment]
Alright, I removed the hardcoded GOOS value. Hopefully next release should work on ARM.
