### ISSUE TITLE
G402 (CWE-295): TLS min version false positive on client usage 

### ISSUE THREAD

**Issue by bcho** [securego/gosec#1061]
### Summary 

Go 1.18 has set the default minimum TLS version to TLS 1.2 **for client usage** (commit: https://github.com/golang/go/commit/035963c7f5d82b5bf1501f407919031f815bd038 / proposal: https://github.com/golang/go/issues/45428) . However, in current gosec implementation, it's still taking the default value as `0x0000`, which results in false positive:

```
[<redacted>/gosec-tls-config.go:9] - G402 (CWE-295): TLS MinVersion too low. (Confidence: HIGH, Severity: HIGH)
    8: func main() {
  > 9: 	config := &tls.Config{}
    10:
```

I understand this might have technically difficulties on detecting if the tls config usage is for client or server. But giving program compiled after Go 1.18, the client will always use >= TLS 1.2 to talk to server, I assume it's fine to not marking it as `TLS MinVersion too low` for default settings?

### Steps to reproduce the behavior

Can reproduce with the sample program from this gist: https://gist.github.com/bcho/f1cec099f0d55ca8e90da3fde7cddabb

### gosec version

Latest master commit (64bbe901441ed79664986b3d056558b256af07d9)

### Go version (output of 'go version')

go version go1.21.0 darwin/arm64

### Operating system / Environment

Mac / Linux

### Expected behavior

Not reporting G402 for default configuration in `MinVersion` field.

### Actual behavior

Reporting G402.

**Comment by ccojocar** [comment]
Duplicate of https://github.com/securego/gosec/issues/1054.
