### ISSUE TITLE
Gosec github action not ignoring // #nosec G112

### ISSUE THREAD

**Issue by frenchi** [securego/gosec#1066]
### Summary 

While running locally, there is no issue. (i.e. behaviour is expected, the finding is surpressed.)
However when pushed to Github Actions, the nosec directive returns a false positive for the following code snippet:

### Steps to reproduce the behavior
```go
func New(listenAddr string) *Server {
	mux := http.NewServeMux()

	return &Server{
		hs: &http.Server{ // #nosec G112 - No factor. Not publicly exposed 
			Addr:    listenAddr,
			Handler: mux,
		},
		mux: mux,
		mu:  sync.Mutex{},
	} // #nosec G112 - No factor. Not publicly exposed 
}
```
### gosec version
2.18.1

### Go version (output of 'go version')
`go version go1.21.3 linux/amd64`

### Operating system / Environment
- Github Action OS Ubuntu 22.04.3 LTS
- actions/setup-go@v4 go 1.21
- securego/gosec:2.18.1

### Expected behavior
Finding is suppressed & #nosec directive is followed.

### Actual behavior
```
[/github/workspace/pkg/server/server.go:25-28] - G112 (CWE-400): Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (Confidence: LOW, Severity: MEDIUM)
    24: 	return &Server{
  > 25: 		hs: &http.Server{ // #nosec G112 - No factor. Not publicly exposed - yes, gosec needs both of these
  > 26: 			Addr:    listenAddr,
  > 27: 			Handler: mux,
  > 28: 		},
    29: 		mux: mux,
```

**Comment by ccojocar** [comment]
You need to use the master version of the action: `securego/gosec@master`. The @2.18.1 action is using the 2.18.0 version of gosec.

**Comment by frenchi** [comment]
@ccojocar retried with securego/gosec@master - please re-open this issue as it persists.

[/github/workspace/pkg/server/server.go:25-28] - G112 (CWE-400): Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (Confidence: LOW, Severity: MEDIUM)
    24: 	return &Server{
  > 25: 		hs: &http.Server{ // #nosec G112 - used locally, no factor
  > 26: 			Addr:    listenAddr,
  > 27: 			Handler: mux,
  > 28: 		},
    29: 		mux: mux,

**Comment by tomjowitt** [comment]
This is broken for us after updating our build images today. We upgraded from Go 1.21.3 to 1.21.4 and, in the process, pulled the latest gosec.

```
RUN go install github.com/securego/gosec/v2/cmd/gosec@latest
```

A number of `#nosec` annotations are now failing and can only be fixed by removing the rule in the global config, which is less than ideal.

The #nosec failures are:

```
G304
G401
G404
G505
```
