### ISSUE TITLE
New G602 rule not ignoring generated files or can be excluded

### ISSUE THREAD

**Issue by bkmeneguello** [securego/gosec#1071]
### Summary 

The new G602 rule uses the SSA instructions to validate the slice bounds, but this new implementation doesn't checks for generated files comments and doesn't allow disabling the validation.

### Steps to reproduce the behavior

My particular situation involves a generated file (`openapi-generator`) that calls a method on an empty slice (`x := []string{}`), but in the method it checks for emptiness (`if len(x) == 0 {return}`). It gives the former violation despite changing the condition (`if len(x) < 1 {do stuff}`). Fixing the false positive would be awesome, but ignoring the generated file or disabling the validation could also helps.

```go
// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

func whatever() {
	...

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)

	...
}

// selectHeaderContentType select a content type from the available list.
func selectHeaderContentType(contentTypes []string) string {
	if len(contentTypes) == 0 {
		return ""
	}
	if contains(contentTypes, "application/json") {
		return "application/json"
	}
	return contentTypes[0] // use the first content type specified in 'consumes'
}
```

Produces

```
[...] - G602 (CWE-118): slice index out of range (Confidence: HIGH, Severity: LOW)
    153:                }
  > 154:                return contentTypes[0] // use the first content type specified in 'consumes'
    155:        }
```

Even if I call the command with `gosec -exclude-generated -exclude=G602 ./...`

### gosec version

v2.18.2

### Go version (output of 'go version')

go version go1.21.4 darwin/amd64

### Operating system / Environment

macOS Ventura 13.6.1

### Expected behavior

When a slice index access (`x[0]`) is guarded by a length condition, it shouldn't produce the violation.

### Actual behavior

Ideally is should not produce the violation, but ignoring the generated files or excluding the validation should also work.

**Comment by ccojocar** [comment]
As a quick workaround, if you have the generated files in a dedicated folder, you can try to use the `gosec --exclude-dir=/path/to/generated/code`.

**Comment by bkmeneguello** [comment]
I downgraded to v2.17.0, the latest version not affected by this bug.
