### ISSUE TITLE
Separate the sample code in `source.go`

### ISSUE THREAD

**Issue by adambkaplan** [securego/gosec#1074]
### Summary 

The sample code used to run tests currently exists in a single, massive file (`source.go`). Contributing additional test samples to this file can be daunting due to its size. This "enhancement" proposes splitting this code up to separate files that are easier for contributors to read - perhaps organized by issue that gosec checks.

**Comment by adambkaplan** [comment]
One potential approach (I would be happy to turn this into a pull request): https://github.com/securego/gosec/compare/master...adambkaplan:split-source-examples?expand=1

**Comment by ccojocar** [comment]
It sounds like a good improvement. We can split it per rules in smaller files.
