### ISSUE TITLE
Bad case of rule G101

### ISSUE THREAD

**Issue by yeqown** [securego/gosec#1081]
### Summary 

G101 generated false positives in my case,  I know the rule G101 can be noisy and may generate false positives (since it matched the pattern 'pass'). But I have no idea about how to skip but only rename the variable which affects code readability. What's worse is I have multi variable name starts with "compass"

### Steps to reproduce the behavior

![image](https://github.com/securego/gosec/assets/27146233/b73c2c53-1598-4770-b693-7de11b572c07)

### gosec version

- golangci-lint: has version v1.54.1 built with go1.20
- gosec: v2.16.0 https://github.com/golangci/golangci-lint/blob/v1.54.1/go.mod#L88C32-L88C38

### Go version (output of 'go version')

go version go1.20 darwin/arm64

### Expected behavior

No error

### Actual behavior

Raised a security fatal

**Comment by ccojocar** [comment]
Please update to latest version v2.18.2. This issue was addressed. Thanks
