### ISSUE TITLE
Need mappings for CWE top 25

### ISSUE THREAD

**Issue by mnsudhan86** [securego/gosec#1083]
### Summary 
CWE publishes the top 25 most common and impactful software weaknesses that are prevalent currently.
https://cwe.mitre.org/top25/archive/2023/2023_top25_list.html

I know that there is mapping from gosec rules to CWE documented here - https://github.com/securego/gosec/blob/master/issue/issue.go#L50 but it didn't consist of all of top 25. Few of the rules may not be applicable for go, but majority of them still will be. However, I could map only about 50% rules to CWE top 25.

Could you please help with mapping of CWE top-25 to gosec rules and provide some insights if there are some rules missing or not applicable?

### gosec version
v2.17.0

### Go version (output of 'go version')
go1.21.0

### Operating system / Environment
Linux

**Comment by ccojocar** [comment]
There is a mapping already between rules and CWE numbers, but this is just for the relevant rules (existing rules). We will add mapping when a new rule is implemented. There is no plan to implement all Top 25 CWEs, therefore I'll close this issue. Thanks
