### ISSUE TITLE
G601 should not be raised when GOEXPERIMENT=loopvar is enabled

### ISSUE THREAD

**Issue by Hades32** [securego/gosec#1090]
### Summary 
The underlying issue will be fixed in Go 1.22 and is available in Go 1.21 with the `GOEXPERIMENT=loopvar` flag enabled

### Steps to reproduce the behavior
```Go
		for _, item := range items {
			cpItem = &item
			break
		}
```

### gosec version
whatever is included in the latest golang-ci

### Go version (output of 'go version')
go version go1.21.0 linux/amd64

**Comment by elisarver** [comment]
This issue also applies to go 1.22.0
