### ISSUE TITLE
apply `nosec` to entire file

### ISSUE THREAD

**Issue by darrenvechain** [securego/gosec#1093]
### Summary 

Is it possible to apply nosec to an entire file? Preferably, to ignore all rules? Similar to Eslints 1 liner:

```javascript
/* eslint-disable */
```

### Steps to reproduce the behavior

N/A

### gosec version

N/A

### Go version (output of 'go version')

N/A

### Operating system / Environment

N/A

### Expected behavior

`myfile.go`

```golang
/* nosec */
package mypackage

func myFunc() {

}

func myFunc2() {

}
```

### Actual behavior

It doesn't apply to a entire file

**Comment by ccojocar** [comment]
`nosec` doesn't work for an entire file. You can try to use `exlude-dir` instead.

**Comment by darrenvechain** [comment]
@ccojocar I don't wan to exclude an entire directory as I have a lot of code there. I only want to exclude an entire file.
