### ISSUE TITLE
Support for `// nolint:gosec` to skip lines on top of `// #nosec`

### ISSUE THREAD

**Issue by douglascamata** [securego/gosec#1106]
### Summary 

We are in a project where `golangci-lint` is used with a certain configuration but also some linters are manually called. 

So there are already some `// nolint:gosec` clauses sprinkled around. But because `gosec` is not compatible with them, I also have to sprinkle a few `// #nosec` clauses.

This is not ideal. I would love if `gosec` could adhere to the de-facto standard that was set by `golangci-lint`.

### Steps to reproduce the behavior

Try to skip `gosec` linting on a line of code with `// nolint:gosec`.

### gosec version

v2.18.2

### Go version (output of 'go version')

go version go1.21.7 darwin/arm64

### Operating system / Environment

macOS

### Expected behavior

Line's skipped in linting.

### Actual behavior

It's not.

**Comment by ccojocar** [comment]
Thanks for reporting this but but it is not in scope gosec scope for now.

**Comment by agabrys** [comment]
There is an command line option to set it:

```
--nosec-tag 'nolint:gosec'
```

If you find a way to pass it through, or set it via a config file, you can use that format in all of your projects.
