### ISSUE TITLE
"Missing function body" error when parsing calls to assembly code

### ISSUE THREAD

**Issue by sudo-bmitch** [securego/gosec#1116]
### Summary 

Gosec generates a non-ignorable error `missing function body` when parsing a file with calls to assembly code.

### Steps to reproduce the behavior

Scan a project like golang.org/x/sys:

```shell
git clone https://go.googlesource.com/sys
cd sys
gosec -terse ./cpu
```

### gosec version

```
$ gosec -version
Version: v2.19.0
Git tag: v2.19.0
Build date:
```

### Go version (output of 'go version')

```
$ go version
go version go1.22.1 linux/amd64
```

### Operating system / Environment

Debian Linux

### Expected behavior

No errors.

### Actual behavior

```
$ gosec -terse ./cpu
Results:

Golang errors in file: []:

  > [line 0 : column 0] - # command-line-arguments
cpu/cpu_gc_x86.go:11:6: missing function body
cpu/cpu_gc_x86.go:15:6: missing function body



Summary:
  Gosec  : v2.19.0
  Files  : 10
  Lines  : 689
  Nosec  : 0
  Issues : 0


$ echo $?
1
```

**Comment by ccojocar** [comment]
This is because gosec executes the scan in the folder provider as input, and in this case in the `./cpu` folder there ins't any go.mod file found. 

If the scan is executed in the root of the folder where the go.mod is available, it will be successful. You can scan the whole module with: `gosec -terse ./...`.

**Comment by sudo-bmitch** [comment]
@ccojocar the error still occurs if the full project is scanned, there's just a lot more output to scan through to see if and I'm trying to keep the example a minimal real world demonstration.

**Comment by ccojocar** [comment]
I see but looking at the code, it seems that those functions are without body and they are implemented outside of Go in C/assembly. 

https://go.googlesource.com/sys/+/refs/heads/master/cpu/cpu_gc_x86.go#11

I think you can ignore these errors.

**Comment by sudo-bmitch** [comment]
They can't be ignored because the scanner exits with a non-zero return code.

**Comment by ccojocar** [comment]
The CFiles/SFiles are not included in the package loading just the CgoFiles (which are go files with import "C" inside). This is why the compilation fails in this case. You can use the -no-fail argument if you want to ignore them.

**Comment by sudo-bmitch** [comment]
Using `-no-fail` effectively disables the scanner. That's something I can do by just removing the scanner from my project.

**Comment by sudo-bmitch** [comment]
Why not give the ability to ignore the errors and not cause a non-zero exit when they are the only error encountered?
