### ISSUE TITLE
G101: False positive of HIGH Severity on constant

### ISSUE THREAD

**Issue by gusandrioli** [securego/gosec#1122]
### Summary 
False positive on G101: Potential hardcoded credentials. 

### Steps to reproduce the behavior
I have this definition and it triggers the linter. 
```go
const (
	routeTokens = "public_tokens.route"
)
```

If i remove `public_`, i.e. 
```go
const (
	routeTokens = "tokens.route"
)
```

It goes away. Complete report:
```
[main.go:77] - G101 (CWE-798): Potential hardcoded credentials (Confidence: LOW, Severity: HIGH)
    76: const (
  > 77:         routeTokens = "public_tokens.route"
    78: )
```

### gosec version
Latest (v2.19.0)

### Go version (output of 'go version')
```
go version go1.21.8 darwin/arm64
```

### Operating system / Environment
Mac M1 2020

### Expected behavior
Should not trigger linter.

### Actual behavior
Triggers linter on false positive

**Comment by gusandrioli** [comment]
I can fix this with some pointers/directions if needed.

**Comment by ccojocar** [comment]
G101 rule tries to do the best effort by default to detect hardcoded secrets but has some missies. You can further adjust the configuration https://github.com/securego/gosec?tab=readme-ov-file#configuration.
