### ISSUE TITLE
Regarding customizing a configuration file to load G101 rules, where keywords with "-" cannot be matched

### ISSUE THREAD

**Issue by kb-at-zero** [securego/gosec#1133]
### Summary 
Regarding customizing a configuration file to load G101 rules, where keywords with "-" cannot be matched.

### Steps to reproduce the behavior

Step 1 : The configuration file
<img width="466" alt="image" src="https://github.com/securego/gosec/assets/41460026/a822fc25-7df0-4e6b-9879-5dcac220a502">

Step 2 : Need to match content
<img width="486" alt="image" src="https://github.com/securego/gosec/assets/41460026/2ab6febc-4ec0-41f7-8c45-284b63a75588">

Step 3 : gosec loading configuration file for matching scan
<img width="414" alt="image" src="https://github.com/securego/gosec/assets/41460026/76618418-4b43-4578-a280-06a5e4b57c59">
**It does not match any content**

When I replace the keywords with "_" form, gosec can be matched normally
<img width="467" alt="image" src="https://github.com/securego/gosec/assets/41460026/74ea165e-a429-437a-a66c-ba6edc545ecc">
<img width="426" alt="image" src="https://github.com/securego/gosec/assets/41460026/743cc903-6c63-4ba1-8d37-d05aa1576ca8">
<img width="1320" alt="image" src="https://github.com/securego/gosec/assets/41460026/36d28f6d-dbe3-43e9-a2e6-ee4aaa684eba">

Step 4 : Escape using escape characters
<img width="486" alt="image" src="https://github.com/securego/gosec/assets/41460026/2860dbc4-5e31-4a50-a1b9-3b96c0e33c94">
<img width="481" alt="image" src="https://github.com/securego/gosec/assets/41460026/67bc424c-f72b-45bd-b8c0-470351ed0eff">
<img width="368" alt="image" src="https://github.com/securego/gosec/assets/41460026/5bd70fee-8f22-40c5-b586-6766dda10b10">

**Still unable to match the content**

**So, I don't know where the problem is occurring that is preventing me from matching keywords with '-'. Can you help me identify where the issue lies? Thank you.**

### gosec version
2.19.0

**Comment by ccojocar** [comment]
In Go an identifier can only contains alphanumerical characters and underscore not the minus sign. Please have a look at the specifications: [identifier](https://go.dev/ref/spec#Identifiers).
