### ISSUE TITLE
Gosec Configuration file to integrate with GitHub ( as a workflow file)  

### ISSUE THREAD

**Issue by Revanthathreya** [securego/gosec#1141]
Hello , 

1. This is the configuration that i am using.

name: GoSec

Run workflow each time code is pushed to your repository.
on:
push:
branches:
- main
pull_request:
branches:
- main
jobs:
tests:
runs-on: ubuntu-latest
env:
GO111MODULE: on

steps:  

  - name: Checkout Source

    uses: actions/checkout@v3

    

  - name: Run Gosec Security Scanner

    uses: securego/gosec@master

    with:

      # we let the report trigger content trigger a failure using the GitHub Security features.

      args: '-no-fail -fmt json -out gosec-results.json ./...'

      run: time gosec ./...

      

  - name: Upload GoSec results

    uses: actions/upload-artifact@v4

    with:

      name: gosec-results

      path: gosec-results.json

2. And for few repositories it is showing the Gosec under the Scanning alerts. Like below

<img width="366" alt="Screenshot 2024-05-14 at 10 17 51 AM" src="https://github.com/securego/gosec/assets/143704329/f80ba787-e11f-4733-b595-32e531285266">

3.But here the main issue is its not showing for other repos. 
 can i get any solution for this. Thank you 
regards
Revanth

**Comment by ccojocar** [comment]
Thank you for opening this issue but this is out of scope.

**Comment by Revanthathreya** [comment]
Hello Ccojocar, 
Ohh is it ! Thanks for letting me know. But i am really stuck with it, can i get any help ? or any suggestions what to do ? That would be really appreciated. 'm looking forward to hearing your positive note. 
Thankyou 
regards
Revanth
