### ISSUE TITLE
Add an option to set the Go version

### ISSUE THREAD

**Issue by ldez** [securego/gosec#1143]
### Summary 

Hello,

I know that my request is really specific to golangci-lint, and if you don't want to do that I will understand.

The new way for gosec to detect the Go version has a huge impact on golangci-lint performances.

- #1119

The best solution for us is to have an option to set the Go version to bypass the usage of `go list`.

### Steps to reproduce the behavior

https://github.com/golangci/golangci-lint/issues/4735

### gosec version

v2.20.0

### Go version (output of 'go version')

```console
$ go version
go version go1.22.3 linux/amd64
```

### Operating system / Environment

Not dependent on the OS

**Comment by ccojocar** [comment]
The new approach is using the `go list` to parse the go version first from the local go module file, if this is not found will fall back to runtime version.  Is `go list` introducing performance issues? 

I am thinking to keep the current behaviour as default and introduce an environment variable to bypass the go list parsing something like `GOSECNOLOCALVERSION`. Would this work for you?

**Comment by ldez** [comment]
> Is `go list` introducing performance issues?

Yes because golangci-lint loads the rules for each package, so a `go list` is done a lot of times (nb of rules that require the Go version)*(nb of packages).

> I am thinking to keep the current behaviour as default and introduce an environment variable to bypass the go list parsing something like `GOSECNOLOCALVERSION`. Would this work for you?

An env var can work.

Note: currently, only 2 rules (G601 and G113) use the `GoVersion` function but the more you will use and more you will also be impacted by this performance problem.

**Comment by ccojocar** [comment]
@ldez I added an environment variable which should disabled the parsing of Go version from module file present in the project. Please have a look at the [README](https://github.com/securego/gosec?tab=readme-ov-file#go-version).

**Comment by ldez** [comment]
@ccojocar I was expected to be able to set the go version through the env var because the `runtime` version will not be right.

```go
	if env, ok := os.LookupEnv("GOSECNOLOCALVERSION"); ok {
		return parseGoVersion(strings.TrimPrefix(env, "go"))
	}
```
