### ISSUE TITLE
can we get a patch release out to support go 1.22 fixes?

### ISSUE THREAD

**Issue by omercnet** [securego/gosec#1173]
re https://github.com/securego/gosec/issues/1166
the latest release is missing some key fixes to work with 1.22
can you trigger a patch release to include the latest changes form head branch?

**Comment by Aswin3405** [comment]
> re #1166 the latest release is missing some key fixes to work with 1.22 can you trigger a patch release to include the latest changes form head branch?

I too upvote on this. Am also looking forward for a fix already available on the head branch. [This](https://github.com/securego/gosec/commit/ac75d44f5635e83e6e91347f7350f1b3c87ee5af) one.

**Comment by ccojocar** [comment]
I'll do soon, thanks!
