### ISSUE TITLE
G115 should be architecture-agnostic for int and uint

### ISSUE THREAD

**Issue by rittneje** [securego/gosec#1195]
Currently, G115 uses the host architecture's definition of `int` and `uint` for determining which conversions are safe. For example, on a 64-bit host, it treats `int` as `int64` and `uint` as `uint64`.

This means it can ignore overflows that happen when cross-compiling. For example, the following snippet may overflow when compiling for a 32-bit target.
```go
func foo(x int64) int {
	return int(x)
}
```

Please note that pessimistically treating `int` as `int32` and `uint` as `uint32` is not sufficient, as doing so would cause the following snippet to pass even though it may overflow when compiling for a 64-bit target.
```go
func bar(x int) int32 {
	return int32(x)
}
```

However, as a nice-to-have, if the file in question has a suffix or build constraint such that all possible architectures have the same `int` or `uint` size, then it should treat them as analogous to the corresponded sized type. For example, the following is safe:
```go
//go:build amd64 || arm64

package foobar

func foo(x int64) int {
	return int(x)
}
```

And the above would also be safe without the `//go:build` directive if it were in a file whose name ended with `_amd64.go` or `_arm64.go`.

**Comment by ccojocar** [comment]
@rittneje Thanks for raising this issue but we don't plan to support scanning for cross compilation.
