### ISSUE TITLE
Invalid SARIF format reported by CodeQL upload-sarif

### ISSUE THREAD

**Issue by komish** [securego/gosec#1224]
### Summary 

I have the same issue outlined here #1220 . I've been searching through all the referenced issues and must be missing the conclusion at which I should arrive. My apologies if it's something obvious.

This was closed with references to issues that don't seem to actually describe a fix other than "it's working". Rolling back to a previous version of gosec seems to be the only path that works for me, as I've tested the latest version of the action, as well as manually installing gosec binaries at both the latest release and the master branch with no change. They all produce the issue.

I do not use the securego/gosec action, I just tried it to see if it's working (didn't seem to work for me).

In my GitHub actions, I install the gosec tool directly from this repository. I've also replicated this locally (as in, I've installed various versions of gosec and generated my SARIF, then  I ran the codeql/upload-sarif Validation logic locally).

I's unclear whether the schema def that's been added to gosec needs to be used by the codeql repositories and we need to chase this down there, or if there's an issue with the file that's used here.

Any guidance is much appreciated.

### gosec version

master @ https://github.com/securego/gosec/commit/30049320058a3d116f9f0d3a98c7fdf3fedc20af
2.21.2

### Go version (output of 'go version')

1.22.6

### Operating system / Environment

N/A

### Expected behavior

I expect the generated SARIF to be considered valid by the codeql/upload-sarif logic

### Actual behavior

It's not considered valid.

**Comment by ccojocar** [comment]
Did you use the master version of GitHub action? It works fine with gosec build. See the details https://github.com/securego/gosec/issues/1220#issuecomment-2352290354

**Comment by komish** [comment]
I’ll test again to be sure, but as mentioned, I don’t use the GitHub action for gosec in my pipelines.

**Comment by komish** [comment]
Confirmed, working for me. Thanks for your help here @ccojocar.
