### ISSUE TITLE
Error: Unable to upload "gosec-results.sarif" as it is not valid SARIF

### ISSUE THREAD

**Issue by maryamtahhan** [securego/gosec#1234]
We've been having consistent failures with our gosec github workflow since updating from 2.20.0  to any newer versions:

https://github.com/sustainable-computing-io/kepler/actions/runs/11015749623/job/30589569438#step:5:5058 

Going to revery back to 2.20.0 but not sure why this is still failing...

**Comment by maryamtahhan** [comment]
We were tracking master: https://github.com/sustainable-computing-io/kepler/pull/1778/files

That's when the failures started. I reverted to 2.20.0 as this was the last stable build we had

**Comment by ccojocar** [comment]
@maryamtahhan This is not master:
<img width="481" alt="image" src="https://github.com/user-attachments/assets/213480da-491b-4088-8d82-d01e772af494">

You use the 2.21.2 version of the action which underneath uses 2.21.1 version of gosec. You need to use the @master version of the GitHub action if you want to have it working.

**Comment by maryamtahhan** [comment]
thanks @ccojocar for getting back to me. If you expand `Run Gosec Security Scanner` in that same job, you should see `Run securego/gosec@master`

![Screenshot 2024-09-25 at 12 59 09](https://github.com/user-attachments/assets/14cc349b-f693-4c57-93e6-70454b78a265)

I will try the latest master again, hopefully it will work

**Comment by maryamtahhan** [comment]
Thanks - Latest master is working https://github.com/sustainable-computing-io/kepler/actions/runs/11048752021/job/30692810903
