### ISSUE TITLE
G201 G202 is not check

### ISSUE THREAD

**Issue by onepiece-dz** [securego/gosec#1260]
### Summary 
G201 G202 is not check.  risk code: 
func GetUserByID(id string) ([]User, error) {
	var users []User
	// 直接拼接字符串生成 SQL 查询，存在注入风险
	db2.Raw(fmt.Sprintf("SELECT * FROM users WHERE id = '%s'", id)).Find(&users)

	_, _ = GetUserByID2(db2, id)
	return users, nil
}

func GetUserByID2(db *gorm.DB, id string) ([]User, error) {
	var users []User
	// 直接拼接查询字符串，存在注入风险
	db.Raw("SELECT * FROM users WHERE id = " + id + "").Find(&users)
	return users, nil
}

### gosec version
v2

**Comment by ccojocar** [comment]
This rule only supports the standard library. Not sure from which module/package the `db2.Raw` is originating.
