### ISSUE TITLE
Provide detailed documentation for each rule

### ISSUE THREAD

**Issue by mmlb** [securego/gosec#127]
It'd be great to have a shellcheck like wiki with some more info on each check, why its bad and what the possible fixes are. If this sounds like a good idea, I can start it off with the minimal info.

**Comment by gcmurphy** [comment]
+1 Thanks for the suggestion. Will add this to the backlog.

**Comment by y0ssar1an** [comment]
Can this be given a higher priority? We currently have no idea if the issues reported by `gas` are real or worth fixing.

See [`staticcheck.io`](https://staticcheck.io/docs/staticcheck) for inspiration, although a GitHub wiki would be more than enough.

**Comment by gcmurphy** [comment]
Just as an update I've created the repository github.com/securego/securego.github.io and registered the securego.io domain for this purpose. I'm hoping to get some spare time to work on this soon.

**Comment by alukyan** [comment]
Yes, this is needed. It looks like some rules are too broad to flag.
Example is G304 - gosec flags all lines where we read a file pointed by a variable, like `contents, err := ioutil.ReadFile(cacheFile)`
What is supposed fix? Hardcode the names?

**Comment by MVrachev** [comment]
Indeed that's something I think would be great. 
The way [Bandit](https://github.com/PyCQA/bandit) (open source security linter for Python) does it is great.
It gives you a field in the json generated output with more info: 
![image](https://user-images.githubusercontent.com/16246778/50085833-d6001d80-0203-11e9-8c3d-3682fb4893ce.png)

It would be sooo useful if we have similar thing in Gosec.

**Comment by paulfurley** [comment]
What's the status of this issue? Is there any (draft?) content written anywhere? Thanks!

**Comment by MVrachev** [comment]
I am helping with the documentation. We have documentation for a small subset of the rules you can read more here:
https://securego.io/

**Comment by ping035627** [comment]
@MVrachev, excuse me,  about "G304: Potential file inclusion via variable ", "ioutil.ReadFile(filename)", what is the right way? I don't find it in https://securego.io/, thanks very much.

**Comment by MVrachev** [comment]
Yes, we need to work more on the documentation.
I was really busy this last month but I will continue to work on the documentation.

**Comment by haroldHT** [comment]
@MVrachev @ping035627 HI, what is the right way to solve 'G304: Potential file inclusion via variable'?

**Comment by szuecs** [comment]
I also see a lot of G304, which are mostly file parameters to `ioutil.ReadFile` that we read from trusted configuration sources. Right now I would exclude this filter.

**Comment by ccojocar** [comment]
@MVrachev @gcmurphy What's the current status of the documentation? Some rules seem to have some guidelines https://securego.io/docs/rules/rule-intro.html. Are you actively working on adding more docs?

**Comment by MVrachev** [comment]
I am slowly working on this when I have time.

**Comment by Jacalz** [comment]
I would like this fixed too. I am having troubles figuring out how to actually fix G304 :slightly_frowning_face:

**Comment by dpritchett** [comment]
Googling G304 led me here. The answer is now added at https://securego.io/docs/rules/g304.html

The fix appears to be "wrap your file path string in a call to `filepath.Clean()`, e.g. 

```diff
-                       loadResult.loadCachedJSON(cacheFilePath)
+                       loadResult.loadCachedJSON(filepath.Clean(cacheFilePath))
```

Thanks for `gosec` by the way, great tool!

**Comment by gliptak** [comment]
G110 is missing at https://securego.io/docs/rules/g110.html

**Comment by jstangroome** [comment]
I very much appreciate the effort that would be required to retrospectively provide detailed documentation to the existing rules.

Would it be a good starting point instead to implement a Pull Request policy that no new rules will be merged without detailed documentation? For example, these newly introduced rules lack docs: https://github.com/securego/gosec/pull/1486

Also I notice the https://github.com/securego/securego.github.io has been archived, does this mean that https://securego.io/docs/rules/rule-intro is now dead? If so, what is the new recommended location for detailed rule documentation going forward?

**Comment by ccojocar** [comment]
The website was discontinued, there is https://github.com/securego/gosec/blob/master/RULES.md which tried to cover this gap. We can add more details if needed.
