### ISSUE TITLE
Option to pass build parameters

### ISSUE THREAD

**Issue by ecunal** [securego/gosec#157]
Is there an option to pass build parameters to `gas` as passed to `go build` command?

There are some source files in our repository that don't get built unless some tags are passed, e.g. we build them with `go build -tags "debug"`. Since we cannot pass the tags to gas, they are not checked. Are there any ways to pass them, if not, is it reasonable to implement it? Thanks!

**Comment by gcmurphy** [comment]
Thanks for reporting this. Currently we use the [defaultBuildContext()](https://golang.org/src/go/build/build.go?s=450:3568#L280), which accepts *some* build configuration via environment variables, however it doesn't look like build tags are accepted. I'll look at introducing some options for build flags.

**Comment by ccojocar** [comment]
Closing this issue since now build tags can be provided to the `gosec`.
