### ISSUE TITLE
SQL String concatenation with string constants

### ISSUE THREAD

**Issue by wongherlung** [securego/gosec#169]
Currently the following example SQL query constructs will trigger rule `G202`.

```golang
const allowed = ">=3" // Could be in another file
...
query := `SELECT name FROM  users WHERE status ` + allowed
```

Another example:
```golang
var allowed string
switch role {
case "admin":
    allowed = "<3"
case "user":
    allowed = ">=3"
}
query := `SELECT name FROM  users WHERE status ` + allowed
```

Would it possible/feasible to allow `gas` to ignore such SQL string concatenation constructs as they are inherently safe?

I don't mind trying to do a PR for `gas` to safely ignore such cases.

**Comment by cosmincojocar** [comment]
@wongherlung How do you make sure that the string which is being concatenated is not a taint input which can lead to a SQL injection in other cases? It seems safe to ignore the rule in your example, but what about other combinations?

It is probably safe for consts but not for variables to ignore this rule. I guess, we need some data flow analysis in order to make a better judgment.

**Comment by gcmurphy** [comment]
We should be able to ignore identifiers that resolve const or basic literals assuming they do not contain dangerous values (maybe something along the lines of [TryResolve](https://github.com/GoASTScanner/gas/blob/master/resolve.go). However to solve for the more general case a more advanced data flow / taint analysis type functionality would need to be introduced to gas. Something like that is likely a long way off unfortunately.

**Comment by wongherlung** [comment]
> However to solve for the more general case a more advanced data flow / taint analysis type functionality would need to be introduced to gas. Something like that is likely a long way off unfortunately.

agreed. Okay then. Then I'll work on a PR that just ignore identifiers that resolve to constants.
