### ISSUE TITLE
Reintroduce 'skip' flag

### ISSUE THREAD

**Issue by johnmcdnl** [securego/gosec#172]
In earlier versions of gas there was an optional 'skip' flag that allowed users to skip packages/folders.

This was an extremely useful flag, as I have a small subset of packages and example scripts that I don't want to run through gas, but don't want to have to pollute the code with #nosec tags.

gas -skip *examples* ./...

**Comment by gcmurphy** [comment]
I'm open to doing this but it has been a big source of bugs / misunderstanding in the past.  In the meantime you can do something like this: 

`go list ./... | grep -v examples | xargs -I {} gas $GOPATH/src/{}`

**Comment by SophisticaSean** [comment]
I'll probably reimplement this as using the above workaround is 1) slower and 2) doesn't group the issues output so you have to scroll thru the entire history to try and find the issues.

**Comment by ccojocar** [comment]
This is fixed by https://github.com/securego/gosec/pull/353. I am going to close it.
