### ISSUE TITLE
Support scanning files passed via stdin

### ISSUE THREAD

**Issue by ericwb** [securego/gosec#193]
### Summary 
This is a feature request for Gas to be able to scan files piped into stdin and not strict files given as an argument.

### Steps to reproduce the behavior
N/A

### Gas version
N/A

### Go version (output of 'go version')
go version go1.9.4 darwin/amd64

### Operating system / Environment
Mac OS X 10.12.6

### Expected behavior
N/A

### Actual behavior
N/A

**Comment by gcmurphy** [comment]
Gas current works at the package level by using the go build toolchain. This informs the type checker and provides better symbol resolution. The old version worked by only check individual files but this lead to a number of edge cases where things were missed or reported as false positives.  I'm unsure if we can support this model but will think about it.

**Comment by ericwb** [comment]
The reason for the request is so that we can create a SublimeLinter plugin for gas so that go files are automatically scanned in your Sublime IDE.  To work with SublimeLinter, it's more ideal to take stdin as input.

**Comment by gcmurphy** [comment]
Makes sense. FWIW there is already a sublime plugin for [gometalinter](https://github.com/alecthomas/gometalinter#editor-integration) which includes gas as one of the linters.

**Comment by dominikh** [comment]
You may want to look into https://godoc.org/golang.org/x/tools/go/buildutil#ParseOverlayArchive

**Comment by ccojocar** [comment]
I am closing this since it seems to be a bit outdated and in the current implementation is not much justified. It is possible to use either the golangci-lint or the golint output format to integrate gosec into an editor. Thanks
