### ISSUE TITLE
Excluding from vendor/ doesn't work as promised

### ISSUE THREAD

**Issue by purpleidea** [securego/gosec#202]
### Summary 

As per main readme: https://github.com/GoASTScanner/gas#excluding-files

> Gas will ignore dependencies in your vendor directory any files that are not considered build artifacts by the compiler (so test files).

### Steps to reproduce the behavior

Run it. Proof can be seen here:

https://travis-ci.org/purpleidea/mgmt/jobs/369934341#L1758

### Gas version

git master

### Go version (output of 'go version')

1.9.x

### Operating system / Environment

GNU/Linux

### Expected behavior

Skips vendor/

### Actual behavior

It does not skip vendor.

**Comment by cosmincojocar** [comment]
@purpleidea somehow you don't have the latest gas from master installed on Travis server. I run locally your `test-goastscanner.sh` script, but no packages from vendor folder were analyzed. Please could you double check and confirm this? Thanks

**Comment by purpleidea** [comment]
@cosmincojocar It runs this script:

https://github.com/purpleidea/mgmt/blob/feat/gas-scanner/misc/make-deps.sh#L101

As per your docs. If that's incorrect, then perhaps it's a different docs bug?

**Comment by gcmurphy** [comment]
Looks like you are also installing gometalinter there. This includes a vendored version of gas. I suspect  that is getting run.

**Comment by ccojocar** [comment]
The latest version of `gosec` ignores now the `vendor` folder. Closing this issue.
