### ISSUE TITLE
Gas ignore top directory when it is a symlink

### ISSUE THREAD

**Issue by allavena** [securego/gosec#203]
### Summary 
My code root is a symlink (due to gitlab setup). In other words, $GOPATH/gitlab.corp.com/group/our_project is a symlink to /wherever_gitlabl_clones_data

### Steps to reproduce the behavior

From the repo directory, if I run a gas ./..., nothing is found, I get a 

warning: ignoring symlink /$GOPATH/etc/our_project
warning: "gitlab.corp.com/group/our_project/..." matched no packages

I've tried a few variants of gas /$GOPATH/etc/our_project, gas /$GOPATH/etc/our_project/...  but never to a successful resolution. Example:
gas  project/...  does nothing and objects to the symlink
gas  project  runs, however, it does not handle the sub packages and I miss some errors.

### Gas version
Not sure, gas -h show empty version git tag and build date. 
I did do a go get -u  github.com/GoASTScanner/gas/cmd/gas/... a few minutes ago

### Go version (output of 'go version')
go version go1.10.1 darwin/amd64

### Operating system / Environment
Darwin/MacOS

### Expected behavior
I think if the project root is a symlink, gas should run normally. 

PS: thanks for building a very useful tool.

**Comment by luv2code** [comment]
seems like it is a deeper issue than what's in `gas`. The stdlibs do not follow symlinks. see: https://github.com/golang/go/issues/17451

However, the workaround suggested in that comment thread works for me (I also use gitlab ci ).  
Use `mount -o bind` instead of `ln -s`. Here is the snippet I'm using:
```yaml
before_script:
  - PROJECT_PATH=$GOPATH/src/gitlab.corp.com/group/proj
  - mkdir -p $PROJECT_PATH
  - mount -o bind `pwd` $PROJECT_PATH
  - cd $PROJECT_PATH
```

**Comment by allavena** [comment]
Thanks for the mount -o bind suggestion. 

Mmm. I'll make a fool of myself and state that I think I disagree with the behaviour of the stdlibs. I think filepath.Walk should traverse symlinks (or there should be another call that does), as ignoring symlinks is not sufficient anyhow to avoid loops (you could still have a file system loop with bind). 

As for gas, as a user, I find it non-intuitive behaviour that symlinks are skipped, whether top level or subdirectories (although all the examples I come up with are rather dirty code practices), as this is not standard linux behaviour. 

Still, as the reporter, I think a 'WONT-FIX' makes sense given the existing libs, I would suggest a mention of mount -o bind in the ReadMe.

**Comment by gcmurphy** [comment]
Presently gosec relies on go build tools. If they don't support it I'm not sure we can either.
