### ISSUE TITLE
Option to suppress issues which have medium and low priority

### ISSUE THREAD

**Issue by thivyae** [securego/gosec#212]
Want an option to suppress errors which are medium and low and not to fail the build/execution

Go version  go version go1.10.3 darwin/amd64
 Operating system / Environment -MAC

Expected behavior  - Want an option to suppress errors which are medium and low so that it does not  fail the build/execution
Actual behavior - Even medium and low issues fail the build execution

**Comment by ccojocar** [comment]
Thanks for this issue. This makes totally sense. We will add this options.
