### ISSUE TITLE
gosec returns non-zero status code after successful scan

### ISSUE THREAD

**Issue by raghunath24** [securego/gosec#230]
### gosec version
gosec 1.0.0

### Go version (output of 'go version')
go 1.10.3

### Operating system / Environment
darwin/amd64

### Expected behavior
it is expect to return zero after successful scan.  

### Actual behavior

[$gosec wokspace/...  #scan performs successfully and displays the summary.
](url)
[$ echo $?     #checking the last run command status it returns with an non zero error message.
](url)1

gosec scan when performed in standalone should be good, but when used it in as part of CI it fails the job.

**Comment by ccojocar** [comment]
@raghunath24 I am trying to reproduce this issue but for me returns `0`:
```
$gosec cmd/...
[gosec] 2018/08/19 20:01:45 including rules: default
[gosec] 2018/08/19 20:01:45 excluding rules: default
[gosec] 2018/08/19 20:01:45 Searching directory: /Users/cosmin/go/src/github.com/securego/gosec/cmd/gosec
[gosec] 2018/08/19 20:01:45 Searching directory: /Users/cosmin/go/src/github.com/securego/gosec/cmd/gosecutil
[gosec] 2018/08/19 20:01:45 Searching directory: /Users/cosmin/go/src/github.com/securego/gosec/cmd/tlsconfig
[gosec] 2018/08/19 20:01:46 Checking package: main
[gosec] 2018/08/19 20:01:46 Checking file: /Users/cosmin/go/src/github.com/securego/gosec/cmd/gosec/filelist.go
[gosec] 2018/08/19 20:01:46 Checking file: /Users/cosmin/go/src/github.com/securego/gosec/cmd/gosec/main.go
[gosec] 2018/08/19 20:01:46 Checking file: /Users/cosmin/go/src/github.com/securego/gosec/cmd/gosec/sort_issues.go
[gosec] 2018/08/19 20:01:46 Checking file: /Users/cosmin/go/src/github.com/securego/gosec/cmd/gosec/version.go
[gosec] 2018/08/19 20:01:46 Checking package: main
[gosec] 2018/08/19 20:01:46 Checking file: /Users/cosmin/go/src/github.com/securego/gosec/cmd/gosecutil/tools.go
[gosec] 2018/08/19 20:01:46 Checking package: main
[gosec] 2018/08/19 20:01:46 Checking file: /Users/cosmin/go/src/github.com/securego/gosec/cmd/tlsconfig/header_template.go
[gosec] 2018/08/19 20:01:46 Checking file: /Users/cosmin/go/src/github.com/securego/gosec/cmd/tlsconfig/rule_template.go
[gosec] 2018/08/19 20:01:46 Checking file: /Users/cosmin/go/src/github.com/securego/gosec/cmd/tlsconfig/tlsconfig.go
Results:

Summary:
   Files: 8
   Lines: 997
   Nosec: 12
  Issues: 0

$ echo $?
0
```

What is your setup? How do you run it? 

Please could you try to do a scan against the gosec source code and check which is the exit code?

**Comment by raghunath24** [comment]
@ccojocar  i have pulled up the latest code and tried against gosec. It works perfectly well. Tried on other project i have, where it was not able to import packages in between but successfully completed the scan. (This was the place where i got status 1) Is this behaviour expected?  

[$gosec project/... 
](url)
Sample: 
/app.go:9:2: could not import project/setup (cannot find package "project/setup" in any of:
	/usr/local/go/src/project/setup (from $GOROOT)
...
Summary:
   Files: xx
   Lines: xx
   Nosec: x
  Issues: xx

Other situation which i came across is when using the [$ gosec -h](url) (which results in status 2)

[echo $?
2](url)

**Comment by ccojocar** [comment]
>i have pulled up the latest code and tried against gosec. It works perfectly well. Tried on other project i have, where it was not able to import packages in between but successfully completed the scan. (This was the place where i got status 1) Is this behaviour expected?

I would say in this case, it makes sense because was an error. The scan cannot be properly completed if there are packages which cannot be imported. This is an indication to the user, to install the missing packages.

>Other situation which i came across is when using the $ gosec -h (which results in status 2)

In this case, in don't have a strong opinion. For me is fine either way.

**Comment by raghunath24** [comment]
Got you. Thanks for update. I guess we can close this one.
