### ISSUE TITLE
Go Modules support 

### ISSUE THREAD

**Issue by kr** [securego/gosec#234]
### Summary 

Now that Go 1.11 is released with module support, more Go code throughout the ecosystem will be written as modules. Currently, gosec is unable to analyze code in modules. It would be great to update it to do so.

If this is something the gosec project is interested in, we (my company) are very interested in contributing a patch.

### Steps to reproduce the behavior

Here's an example. (For a real-world sample module, I followed along with https://dave.cheney.net/2018/07/14/taking-go-modules-for-a-spin on @davecheney's httpstat package, and pushed the changes to https://github.com/kr/httpstat/tree/mod.)

You can check out this module outside your `GOPATH` directory:

```
$ pwd
/Users/kr/demo
$ echo $GOPATH
/Users/kr/lib/go
$ git clone -b mod https://github.com/kr/httpstat.git
$ cd httpstat
$ go test
PASS
ok  	github.com/davecheney/httpstat	0.013s
```

But gosec isn't happy:

```
$ gosec *.go
[gosec] 2018/08/28 16:34:08 including rules: default
[gosec] 2018/08/28 16:34:08 excluding rules: default
2018/08/28 16:34:08 main.go is not within the $GOPATH and cannot be processed
```

### gosec version

`7fd94463edcbf12df2b5579682c003c3bffd6749`

### Go version (output of 'go version')

```
go version go1.11 darwin/amd64
```

### Operating system / Environment

```
$ go env GOOS GOARCH
darwin
amd64
```

### Expected behavior

Gosec analyzes the code and reports possible errors, as usual.

### Actual behavior

Error message.

**Comment by gcmurphy** [comment]
Will look at moving to https://godoc.org/golang.org/x/tools/go/packages to address this issue.

**Comment by ccojocar** [comment]
Yap, package loading was updated in 1.11 https://golang.org/doc/go1.11#gopackages.

**Comment by MVrachev** [comment]
I tried it today and is still not fixed.
I downloaded the latest version of Golang and reinstalled gosec but still I get errors from gosec when I scan code outside the GOPATH.

**Comment by d0znpp** [comment]
```
docker run -it -v /tmp/src/xxx_api/:/go/src/xxx_api securego/gosec ./...
[gosec] 2018/10/05 18:41:33 including rules: default
[gosec] 2018/10/05 18:41:33 excluding rules: default
2018/10/05 18:41:33 ./... is not within the $GOPATH and cannot be processed
```

**Comment by ricardoatsouza** [comment]
I am having quite a hard time to use `gosec` with modules. It doesn't quite work with `GO111MODULE=on`. For example, when `gosec` is running, I see a lot of errors like: `could not import X`:

```
/go/src/gitlab.com/<my-go-repo>/main.go:5:2: could not import strings (go/build: importGo strings: exit status 2
go: cannot find GOROOT directory: /Users/cosmin/.gvm/gos/go1.11.1

)
/go/src/gitlab.com/<my-go-repo>/main.go:4:2: could not import fmt (go/build: importGo fmt: exit status 2
go: cannot find GOROOT directory: /Users/cosmin/.gvm/gos/go1.11.1

)
...
```

Once I turn off `GO111MODULE`, everything works just as fine. Not sure if there is something I am missing, but the go module support would probably solve this as well.

Please, let me know if I should create a new issue specifically for this.

**Comment by ccojocar** [comment]
To support Go modules, we will need to switch to the new language parser introduced by Go team in Go 1.11 as @gcmurphy mentioned above. 

I am not sure if this new language parser is backward compatible with Go 1.10. Probably we will need to support two language parsers for a while.

**Comment by sjbodzo** [comment]
Any update on support for Go modules? A couple of months back we ripped dep out of all of our projects, and I'd hate to have to put it back in to run gosec.

**Comment by songjiayang** [comment]
Really want this feature.
