### ISSUE TITLE
Rule with id G104 doesn't work on Ubuntu

### ISSUE THREAD

**Issue by MVrachev** [securego/gosec#242]
### Summary 
I have two test files which are recognized on my Mac by gosec with security problems with rule_id G104.
When I run gosec on the same files with OS Ubuntu 18.04 gosec doesn't find these security flaws.

### Steps to reproduce the behavior

Normal run of gosec on files with security problems which should be caught with rule with id 104.

### gosec version

Latest commit:  ec32ce6  

### Go version (output of 'go version')

I don't have go language installed at all. I use gosec binary on Ubuntu.

### Operating system / Environment

Ubuntu 18.04.1 LTS

### Expected behavior

Detect the security problems and report for them.

### Actual behavior

Miss them as if there is no problem.

**Comment by MVrachev** [comment]
Golang version on my Mac: go version go1.11 darwin/amd64

Golang version on Ubuntu: go version go1.11 linux/amd64

Test files: 
[testFiles.zip](https://github.com/securego/gosec/files/2418613/testFiles.zip)

When I run the scan on Mac I get: 
Summary:
   Files: 2
   Lines: 49
   Nosec: 0
  Issues: 7

On Linux I get: 

Summary:
   Files: 2
   Lines: 49
   Nosec: 0
  Issues: 4

The issues the Linux missed are these:

"severity": "LOW",
		{	"confidence": "HIGH",
			"rule_id": "G104",
			"details": "Errors unhandled.",
			"file": "badTestFile.go",
			"code": "os.Chmod(\"/etc/passwd\", 0777)",
			"line": "26"
		},
		{
			"severity": "LOW",
			"confidence": "HIGH",
			"rule_id": "G104",
			"details": "Errors unhandled.",
			"file": "badTestFile.go",
			"code": "os.Chmod(\"~/.bashrc\", 0777)",
			"line": "27"
		},
		{
			"severity": "LOW",
			"confidence": "HIGH",
			"rule_id": "G104",
			"details": "Errors unhandled.",
			"file": "randNumTest.go",
			"code": "good, _ := rand.Read(nil)",
			"line": "10"
		}

Maybe is something connected with a config option which bypass security problems with severity which is LOW ?

**Comment by ccojocar** [comment]
I run a scan using the `gosec` in a docker container which is based on alpine Linux and returns 7 issues, the same like on MacOS:
```
$docker run -it --rm -v "$GOPATH/src/github.com:/go/src/github.com" -w /go/src/github.com/ccojocar/samples securego/gosec ./...
[gosec] 2018/09/28 09:02:29 including rules: default
[gosec] 2018/09/28 09:02:29 excluding rules: default
[gosec] 2018/09/28 09:02:30 Searching directory: /go/src/github.com/ccojocar/samples
[gosec] 2018/09/28 09:02:30 Checking package: app
[gosec] 2018/09/28 09:02:30 Checking file: /go/src/github.com/ccojocar/samples/badTestFile.go
[gosec] 2018/09/28 09:02:30 Checking file: /go/src/github.com/ccojocar/samples/randNumTest.go
Results:

[/go/src/github.com/ccojocar/samples/badTestFile.go:15] - G101: Potential hardcoded credentials (Confidence: LOW, Severity: HIGH)
  > password := "f62e5bcda4fae4f82370da0c6f20697b8f8447ef"


[/go/src/github.com/ccojocar/samples/badTestFile.go:19] - G102: Binds to all network interfaces (Confidence: HIGH, Severity: MEDIUM)
  > net.Listen("tcp", "0.0.0.0:2000")


[/go/src/github.com/ccojocar/samples/badTestFile.go:26] - G302: Expect file permissions to be 0600 or less (Confidence: HIGH, Severity: MEDIUM)
  > os.Chmod("/etc/passwd", 0777)


[/go/src/github.com/ccojocar/samples/badTestFile.go:27] - G302: Expect file permissions to be 0600 or less (Confidence: HIGH, Severity: MEDIUM)
  > os.Chmod("~/.bashrc", 0777)


[/go/src/github.com/ccojocar/samples/badTestFile.go:26] - G104: Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > os.Chmod("/etc/passwd", 0777)


[/go/src/github.com/ccojocar/samples/badTestFile.go:27] - G104: Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > os.Chmod("~/.bashrc", 0777)


[/go/src/github.com/ccojocar/samples/randNumTest.go:10] - G104: Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > good, _ := rand.Read(nil)


Summary:
   Files: 2
   Lines: 47
   Nosec: 0
  Issues: 7
```

I would recommend to use the official docker image to avoid any installation issues. I think, it might be something in your ubuntu installation, which is difficult to figure out. I will close this issue for now, if you get more details, which narrow down the problem on `gosec` side, please don't hesitate to provide them here and to re-open this issue.

**Comment by MVrachev** [comment]
Yes but this is not only problem on the Virtual Machine which runs Ubuntu but also it's a problem when I run gosec on Heroku.  There I miss the same three errors which I catch on my local machine. 
Heroku operation system is based on Ubuntu again.

I use binary file out there is it possible this could be the problem?
