### ISSUE TITLE
Can't scan a single file

### ISSUE THREAD

**Issue by MVrachev** [securego/gosec#244]
### Summary 

I tried to scan a single go file in a folder containing  three go files.
I was super surprised when I found out that by default gosec scans the whole folder.
I searched for an argument which will let me to scan a single file but I didn't found any.

### Steps to reproduce the behavior

Run gosec in a folder with more than one go files.

### gosec version

I have gosec installed from commit : ec32ce6

### Go version (output of 'go version')

go version go1.11 darwin/amd64

### Operating system / Environment

macOS High Sierra

### Expected behavior

Scan a single file and give me output for a single file.

### Actual behavior

Scans the whole folder.

**Comment by ccojocar** [comment]
`gosec` scans only entire packages. It used to scan individual files but due to dependencies issues we decided to scan only packages. This is not in the scope right now, therefore I am going to close it. Thanks
