### ISSUE TITLE
Gas returns no error even if it could not run

### ISSUE THREAD

**Issue by SamWhited** [securego/gosec#250]
### Summary 

When gosec cannot complete its run because of a missing dependency, it returns success.

### Steps to reproduce the behavior

```
$ gosec -quiet ./...                                      
/home/sam/go/src/github.com/prometheus/client_golang/prometheus/summary.go:23:2: could not import github.com/beorn7/perks/quantile (cannot find package "github.com/beorn7/perks/quantile" in any of:
        /home/sam/Projects/go/src/github.com/beorn7/perks/quantile (from $GOROOT)       
        /home/sam/go/src/github.com/beorn7/perks/quantile (from $GOPATH))               
$ echo $?
0
```

### gosec version

2cc6838ca3c1e79cf82074ecc6c572a649ee2b1b

### Go version (output of 'go version')

    go version devel +fb061b5e11 Sat Sep 15 14:58:35 2018 +0000 linux/amd64

### Operating system / Environment

    Linux 4.18.10-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 26 09:48:22 UTC 2018 x86_64 GNU/Linux

### Expected behavior

gosec couldn't perform its checks, it should error so that, for example, CI doesn't think it ran successfully.

### Actual behavior

No error. Everything appears to have worked fine.

**Comment by MVrachev** [comment]
I have the same problem when I scan with Gosec invalid files with syntax or other mistakes.

**Comment by MVrachev** [comment]
Hi, can you check do you have the same problem again with the latest 1.3 version of Gosec?

**Comment by SamWhited** [comment]
I can't even reproduce it with the old version anymore; might have been related to some more specific version, or maybe I updated at some point and didn't notice that it was fixed.
