### ISSUE TITLE
gosec uses wrong GOROOT path and fails to find stdlib packages

### ISSUE THREAD

**Issue by fho** [securego/gosec#259]
### Summary
I'm trying to use gosec in the docker container `simplesurance/debian-build:20181029.1012.55`. In the image Golang 1.11. is installed in /usr/local/go.

When I run gosec it can't find the STDLIB packages in `/usr/local/go`. The go commands can and `go env` looks correct:

```
root@4ae5abd85b83:/go/src/github.com/fho/test# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build820916954=/tmp/go-build -gno-record-gcc-switches"
```

The `$GOROOT` env variable is not set.
When i set the `export GOROOT=$(go env GOROOT)` gosec works. 
Despite it  should use the GOROOT value then `go env` shows when the env variable is unset.

### Steps to reproduce the behavior
```
docker run -i -t simplesurance/debian-build:20181029.1012.55 bash
mkdir -p $GOPATH/src/github.com/fho/test
echo -e 'package main\nimport "fmt"\nfunc main(){\nfmt.Println("Hello")\n}' | goimports > $GOPATH/src/github.com/fho/test/main.go
cd $GOPATH/src/github.com/fho/test
rm /usr/local/bin/gosec
curl -sSL https://github.com/securego/gosec/releases/download/1.1.0/gosec_1.1.0_linux_amd64.tar.gz -o - | tar -C /usr/local/bin/ -xzvf -
gosec ./...
```
### gosec version
1.1.0

### Go version (output of 'go version')
go version go1.11.1 linux/amd64
### Operating system / Environment
Debian
### Expected behavior
gosec runs without errors, finds stdlib packages
### Actual behavior
```
root@4ae5abd85b83:/go/src/github.com/fho/test# gosec ./...
[gosec] 2018/10/29 09:39:21 including rules: default
[gosec] 2018/10/29 09:39:21 excluding rules: default
[gosec] 2018/10/29 09:39:21 Searching directory: /go/src/github.com/fho/test
/go/src/github.com/fho/test/main.go:3:8: could not import fmt (cannot find package "fmt" in any of:
	/Users/cosmin/.gvm/gos/go1.10.3/src/fmt (from $GOROOT)
	/go/src/fmt (from $GOPATH))
[gosec] 2018/10/29 09:39:21 Checking package: main
[gosec] 2018/10/29 09:39:21 Checking file: /go/src/github.com/fho/test/main.go
Results:

Summary:
   Files: 1
   Lines: 7
   Nosec: 0
  Issues: 0
```

**Comment by ccojocar** [comment]
@fho Have you tried the official Docker image? For instance the gosec source code can be analysed as follows:

```
docker run -it -v $GOPATH/src/github.com/securego/gosec:/go/src/github.com/securego/gosec securego/gosec /go/src/github.com/securego/gosec/...
```
It works for me without errors.

**Comment by ccojocar** [comment]
Thanks for following up!

**Comment by erikh** [comment]
This is still broken in 1.2's github release. Can we get a release? Downloading these repositories as a part of my CI process is quite expensive and I can't use the image in this scenario.

**Comment by duxbuse** [comment]
It seems this is also the issue when using the GitHub action.

**Comment by ccojocar** [comment]
We did this fix to GitHub action which still needs a release in order to be effective. https://github.com/securego/gosec/pull/503

The release will come out soon!
