### ISSUE TITLE
gosec: does not work when GOPATH is '/'

### ISSUE THREAD

**Issue by fho** [securego/gosec#260]
### Summary 
We are using gosec in a dockerimage. Our Go Code is mounted into the container and we use `/` as GOPATH.
This works well with the Golang tools (and all linters we are currently using) but gosec fails to handle `/` as GOPATH correctly.

### Steps to reproduce the behavior
```

curl -sSL https://github.com/securego/gosec/releases/download/1.1.0/gosec_1.1.0_linux_amd64.tar.gz -o - | tar -C /tmp/ -xzvf -
mkdir -p /src/github.com/fho/test
export GOPATH=/
echo -e 'package main\nimport "fmt"\nfunc main(){\nfmt.Println("Hello")\n}' | goimports > $GOPATH/src/github.com/fho/test/main.go
cd /src/github.com/fho/test
go run github.com/fho/test -> worksgo run github.com/fho/test -> works
go build main.go  -> works
gosec ./... -> fails
```

### gosec version
1.1.0

### Go version (output of 'go version')
go version go1.11.1 linux/amd64

### Operating system / Environment
ArchLinux

### Expected behavior
gosec runs successfully 

### Actual behavior
```
[root@ltop test]# pwd
/src/github.com/fho/test
[root@ltop test]# gosec  ./...
[gosec] 2018/10/29 11:11:22 including rules: default
[gosec] 2018/10/29 11:11:22 excluding rules: default
2018/10/29 11:11:22 ./... is not within the $GOPATH and cannot be processed
```

```
# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build702245632=/tmp/go-build -gno-record-gcc-switches"

```

**Comment by renatosuero** [comment]
Hey, @fho I had the same problem(in my case I'm using docker). I don't know if it can be useful to you, but try something like this

docker run --rm -i -v $GOPATH/src/github.com/renatosuero/myrepo:/go/src/github.com/renatosuero/myrepo securego/gosec /go/src/github.com/renatosuero/myrepo

Using docker the workdir of the container is /go/src/github.com/securego/gosec , so you need to define the project path to run the app.

I hope it can help you :)

**Comment by gcmurphy** [comment]
Hoping to fix this as a part of addressing gomodule support.

**Comment by bacarell** [comment]
Hello gcmurphy, 
I am looking for any way to successfully execute a gosec scan. Where can I put the code so that gosec can find it?  This seems like a catch 22.  Thank you in advance.

$GOPATH = /home/jenkins/workspace/CICDBeta/GoProjects:/go

File to be scanned: 
-rw-r--r-- 1 jenkins jenkins   74 Apr 17 16:24 helloWorld.go

Actual command being attempted:
gosec -nosec=true /home/jenkins/workspace/CICDBeta/GoProjects/*.go

Response:
2019/04/17 16:25:08 /home/jenkins/workspace/CICDBeta/GoProjects/helloWorld.go is not within the $GOPATH and cannot be processed

**Comment by ccojocar** [comment]
@tam7t This should be fixed now after refactoring the analyser for Go modules. I am going to close.
