### ISSUE TITLE
SQL String concatenation issues are ignored when multiple strings are concatenated 

### ISSUE THREAD

**Issue by fho** [securego/gosec#264]
### Summary 
If a SQL query string is a concatenation of multiple strings gosec does not complain.

### Steps to reproduce the behavior
Check the following code snippet with `gosec`:
```
package main

import "database/sql"

func main() {
	query("; DELETE * FROM TABLE;")
}

func query(param string) {
	clt, _ := sql.Open("postgres", "")

	clt.Query("SELECT * FROM table" + "WHERE" + param)
}
```

### gosec version
Commit 41809946d461bcf365ab440a5d79bfbd1ce2ebbf
### Go version (output of 'go version')
go version go1.11.2 linux/amd64
### Operating system / Environment
Linux
### Expected behavior
Gosec finds issue `G202: SQL string concatenation (Confidence: HIGH, Severity: MEDIUM)`
### Actual behavior
Gosec does not find an issue.

**Comment by gcmurphy** [comment]
Thanks for finding this. Will try to get to it soon.
