### ISSUE TITLE
G104: Whitelisting does not work on types

### ISSUE THREAD

**Issue by thsnr** [securego/gosec#267]
### Summary 

G104 contains a [whitelist](https://github.com/securego/gosec/blob/master/rules/errors.go#L81) of functions and methods to ignore. However whitelisting of type methods seems to be broken and only works for package functions.

More specifically, only the `fmt` whitelist is working and `bytes.Buffer`, `strings.Builder`, and `io.PipeWriter` are not.

### Steps to reproduce the behavior

Run `gosec` on the following file:
```go
package main

import (
        "bytes"
        "fmt"
        "io"
        "os"
        "strings"
)

func main() {
        new(bytes.Buffer).WriteString("*bytes.Buffer")
        fmt.Fprintln(os.Stderr, "fmt")
        new(strings.Builder).WriteString("*strings.Builder")
        _, pw := io.Pipe()
        pw.CloseWithError(io.EOF)
}
```

### gosec version

master (2695567)

### Go version (output of 'go version')

go version go1.11 linux/amd64

### Operating system / Environment

Debian buster

### Expected behavior

All whitelisted functions are ignored and no G104 errors are reported.

### Actual behavior

The whitelisted cases are still reported as unchecked errors:
```
[/go/src/main/main.go:12] - G104: Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > new(bytes.Buffer).WriteString("*bytes.Buffer")


[/go/src/main/main.go:14] - G104: Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > new(strings.Builder).WriteString("*strings.Builder")


[/go/src/main/main.go:16] - G104: Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > pw.CloseWithError(io.EOF)
```

**Comment by plo-** [comment]
Any update on this issue?

**Comment by plo-** [comment]
Anyone?

**Comment by gcmurphy** [comment]
Sorry. Been hard to find time to work on this. There does definitely look like a problem with the whitelist functionality. There is a discrepancy between how [other rules](https://github.com/securego/gosec/blob/master/rules/readfile.go#L101) use the call list (explicitly specifying package path). It could explain why "fmt" and "fmt.Println" etc work and bytes.Buffer doesn't. Will need to look at this as could be related to #291

**Comment by plo-** [comment]
Any progress?

**Comment by plo-** [comment]
Thanks :) Any progress so far?
