### ISSUE TITLE
Add more lines in rule code section 

### ISSUE THREAD

**Issue by oxdef** [securego/gosec#268]
### Summary 
For more readability it will be great to add more lines in the rule code section (like in [Bandit](https://github.com/PyCQA/bandit))

### Steps to reproduce the behavior
1. Scan some code and get report

### Expected behavior
```json
{
		"severity": "HIGH",
		"confidence": "HIGH",
		"rule_id": "G402",
		"details": "TLS InsecureSkipVerify set true.",
		"file": "request.go",
		"code": "122 //some previous code\n 123 InsecureSkipVerify: true\n 124 //...",
		"line": "123"
}
```
### Actual behavior
```json
{
		"severity": "HIGH",
		"confidence": "HIGH",
		"rule_id": "G402",
		"details": "TLS InsecureSkipVerify set true.",
		"file": "request.go",
		"code": "InsecureSkipVerify: true",
		"line": "123"
}
```

**Comment by gcmurphy** [comment]
We extract the code segment from the file by using the positional coordinates reported by the AST node here: https://github.com/securego/gosec/blob/master/issue.go#L107

It should be possible to add more context there.
