### ISSUE TITLE
Documentation about how to use config file

### ISSUE THREAD

**Issue by MVrachev** [securego/gosec#269]
### Summary 
I want to set up a config file for Gosec. I see it is possible because there is a flag: "-conf string : Path to optional config file" but it is unclear for me what should be the syntax of that file.
Can you give an example? 

I want ot have the ability to set some of those options (it will be cool all to support all of them): 
https://github.com/PyCQA/bandit#per-project-command-line-args

So my question is can you documented it somewhere? 

### Expected behavior
Easy to understand with an example documentation on how to set up custom config file.

### Actual behavior
I don't find anywhere a documentation about it.

**Comment by NishikaDeSilva** [comment]
Hi, 

Is there are any documentation on how to write a configuration file for GoSec? 

In README.md there are few examples but I can't find a detailed explanation on how to write it.

**Comment by varkey98** [comment]
Please add a list of rules that would be supported for exclusion in the config file, or how to use them.
