### ISSUE TITLE
G104: Doesn't understand _ assignments

### ISSUE THREAD

**Issue by cyphar** [securego/gosec#270]
### Summary 

It's a very common pattern in Go code that `_ = foo()` indicates that the error is being **explicitly** ignored (for whatever reason). However, `gosec` will still give you errors despite this:

```
[/home/cyphar/.local/src/github.com/openSUSE/umoci/oci/layer/unpack.go:128] - G104: Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > _ = fsEval.RemoveAll(rootfsPath)
```

(And obviously this happens if the error is in a tuple-style return as well.)

### gosec version
12400f9a1ca705a17c4aa3728e631e563025a188

### Go version (output of 'go version')
```
go version go1.11.4 linux/amd64
```
### Operating system / Environment
openSUSE Tumbleweed

### Expected behavior

`_ = foo()` should result in the warning being suppressed -- since the error is *not* "unhandled".

### Actual behavior

`_ = foo()` is incorrectly classified as an unhandled error (G104).

**Comment by cyphar** [comment]
In fact, the G104 implementation actually [**explicitly** considers `_` to be an unhandled error](https://github.com/securego/gosec/blob/master/rules/errors.go#L61-L63). This seems quite silly.

```
if id, ok := stmt.Lhs[pos].(*ast.Ident); ok && id.Name == "_" {
	return gosec.NewIssue(ctx, n, r.ID(), r.What, r.Severity, r.Confidence), nil
}
```

**Comment by henvic** [comment]
I agree. I just ran into this false positive myself. If you are ignoring _ IMHO gosec should assume you know what you are doing.

**Comment by cyphar** [comment]
I'll submit a PR, the patch is fairly trivial.

**Comment by gcmurphy** [comment]
For the purposes of code auditing I _want_ to know if somebody is explicitly ignoring an error via "_". 
That is why this rule exists. To help identify logic errors that are introduced by poor error handling. 

However I understand if people don't want this as the default behavior. So we should avoid making it the default behavior but make it something that is configurable.

**Comment by ccojocar** [comment]
Shell we add a `global.audit` flag, which enables this check?
