### ISSUE TITLE
G105 issue cannot be fixed?

### ISSUE THREAD

**Issue by kevholditch** [securego/gosec#283]
### Summary 
I get an error G105 - Use of math/big.Int.Exp function should be audited for modulus == 0 (Confidence: HIGH, Severity: LOW) but I can't see any way to fix it?

### Steps to reproduce the behavior
code sample:
```
import "math/big"

lower := new(big.Int)
lower.Exp(big.NewInt(2), big.NewInt(255), nil)
```

I would expect no error as modulas is hard coded to `nil` which means ignored

### gosec version
1.2.0
### Go version (output of 'go version')
go version go1.11.2 linux/amd64
### Operating system / Environment
ubuntu 18
### Expected behavior
Have a way to get rid of this error, not sure if its even valid as setting m==nil explictitly ignores m according to the exported func
### Actual behavior
no way to get rid of warning

**Comment by gcmurphy** [comment]
Thanks for reporting this. I believe this rule was originally introduced to detect https://github.com/golang/go/issues/15184. We can certainly do some better analysis of arguments here. I'm wondering if this rule is still applicable since this should've been addressed in the go runtime now? @ccojocar thoughts?

**Comment by ccojocar** [comment]
I need to check if this rule is still relevant.

**Comment by hrharder** [comment]
Checking in on the status of this? We have to do `// nolint:gosec` on this line for a pretty standard operation. 

As far as I know the below is sound, and the only way to do `x**y` with `big.Int`.
```go
var x, two, zero = big.NewInt(9), big.NewInt(2), big.NewInt(0)
x.Exp(nine, two, zero)
```

See [playground.](https://play.golang.org/p/6mV65OZB79V)
