### ISSUE TITLE
gosec report G204

### ISSUE THREAD

**Issue by lookingcamel** [securego/gosec#292]
### Summary 
When I use this style of coding:

func MyCmd(cmd string, args string...){
    exec.Command(cmd,args...)
}

go sec report G204 of this line,
How can I fix this report?

**Comment by gcmurphy** [comment]
Hi @lookingcamel.

G204 is really intended for assisting in code audits. It doesn't necessarily indicate a bad behaviour, but something that should be checked for potential command execution.  If you're sure that the code in use is not vulnerable to this type of attack you can [annotate your code](https://github.com/securego/gosec#annotating-code
) to avoid reporting that error at that particular line. 

You can also disable the rule at runtime via `gosec -exclude=G204`.  Hope that helps.

**Comment by ping035627** [comment]
@gcmurphy excuse me, many G204 alarms are reported in the k8s source code, I want to know what kind of situation would there be such risks? Thanks!

**Comment by gcmurphy** [comment]
I've given an example here of a case where command line injection is possible in Go:  https://github.com/securego/gosec/issues/204#issuecomment-384474356. Does that help? Also please consider joining us on Slack for support type questions such as this. GitHub issues are more intended for bug reports and feature tracking.

**Comment by ping035627** [comment]
Your answer is helpful, thanks very much! See later on Slack . :)
