### ISSUE TITLE
G404: Use of weak random number generator (math/rand instead of crypto/rand)

### ISSUE THREAD

**Issue by ping035627** [securego/gosec#294]
### Summary 
import “math/rand”, but gosec report errors.
package scalability

import (
	"fmt"
	"math"
	"math/rand"
...
）
func GenerateConfigsForGroup(...） {
...
if kind == randomKind {
			kind = knownKinds[rand.Int()%len(knownKinds)]
		}
...
}
### Steps to reproduce the behavior
root@k8s-E9000:/home/k8s# ./gosec $in/test/e2e/scalability/load.go > gosec.csv

[/home/k8s/workspace/inter/src/k8s.io/kubernetes/test/e2e/scalability/load.go:544] - G404: Use of weak random number generator (math/rand instead of crypto/rand) (Confidence: MEDIUM, Severity: HIGH)
  > rand.Int()

### gosec version
1.3.0

### Go version (output of 'go version')
1.11.1

**Comment by ping035627** [comment]
@gcmurphy

**Comment by gcmurphy** [comment]
I believe what the reporter is saying here is that: 

`func Int() int` is in math/rand whilst `func Int(rand io.Reader, max *big.Int) (n *big.Int, err error)` is in `"crypto/rand"`. It should be possible to tell the difference.

**Comment by ping035627** [comment]
But it report “Confidence: MEDIUM, Severity: HIGH”, and there are also similar errors in k8s codes.

**Comment by ping035627** [comment]
@gcmurphy, Excuse me, when using crypto/rand, what situations will not be alarmed? I found that in some places in the k8s code, Int () gosec using "crypto / rand" did not report an alarm, and in some places it did.

**Comment by gcmurphy** [comment]
There is an open bug https://github.com/securego/gosec/issues/291 related to this.

**Comment by ping035627** [comment]
I want to know how to fix code about the "G404: Use of weak random number generator (math/rand instead of crypto/rand)" alrm,  if we can't use Int() of "crypto / rand", or what's the right way use Int() of "crypto / rand"? thanks very much!

**Comment by ccojocar** [comment]
@ping035627 You can generate a random integer with `crypto/rand` as follows:
```Go
package main

import (
	"crypto/rand"
	"math/big"
	"fmt"
)

func main() {
	n, err := rand.Int(rand.Reader, big.NewInt(1000))
	if err != nil {
		fmt.Println("error:", err)
		return
	}
	fmt.Printf("random number: %d\n", n.Int64())

}
```

**Comment by ccojocar** [comment]
@ping035627 Do you need more help? Can we close this issue?

**Comment by ping035627** [comment]
ok, thanks very much!
