### ISSUE TITLE
G101: Potential hardcoded credentials

### ISSUE THREAD

**Issue by ping035627** [securego/gosec#295]
### Summary 
Gosec reports error when the consts containing "Secret" or "token".

type SecretType string
const (
         .......
	SecretTypeServiceAccountToken SecretType = "kubernetes.io/service-account-token"
        SecretTypeDockercfg SecretType = "kubernetes.io/dockercfg"
)

### Steps to reproduce the behavior
[/pkg/apis/core/types.go:4417], - G101: Potential hardcoded credentials , Confidence: LOW, Severity: HIGH, > SecretTypeDockercfg SecretType = "kubernetes.io/dockercfg"

[/pkg/apis/core/types.go:4398], - G101: Potential hardcoded credentials , Confidence: LOW, Severity: HIGH, > SecretTypeServiceAccountToken SecretType = "kubernetes.io/service-account-token"
### gosec version
1.3
### Go version (output of 'go version')
1.11.1

**Comment by gcmurphy** [comment]
This is marked as low confidence and `Potential hardcoded credentials`. It is intended for this to be audited by a human to confirm and if a false positive add the appropriate [annotation](https://github.com/securego/gosec#annotating-code) to confirm. The rule actually looks for what are considered high entropy strings as per the zxcvbn implementation. 

It is possible to tweak the [entropy settings and identifier pattern] (https://github.com/securego/gosec/blob/master/rules/hardcoded_credentials.go#L107) via a configuration file to get less false positives if you're interested in that option.
