### ISSUE TITLE
gosec sonarqube format reports a wrong path for .go files when located in inner folders

### ISSUE THREAD

**Issue by andrea-tortosa** [securego/gosec#315]
### Summary 
gosec sonarqube format reports a wrong path for .go files when located in inner folders

### Steps to reproduce the behavior
Running 
gosec -fmt=sonarqube -out gosec-report.json ./... 
within a cloned repo containing a 
helloWorld.go file in a GoProjects folder

helloworld.go file content is:
```go
package main
import "fmt"
func main() {
        var password = "f62e5bcda4fae4f82370da0c6f20697b8f8447ef"
        fmt.Printf("hello, world\n")
}
```

Here is the std output:
```
[gosec] 2019/05/07 09:53:46 Including rules: default
[gosec] 2019/05/07 09:53:46 Excluding rules: default
[gosec] 2019/05/07 09:53:46 Import directory: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/GoProjects
[gosec] 2019/05/07 09:53:47 Checking package: main
[gosec] 2019/05/07 09:53:47 Checking file: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/GoProjects/helloWorld.go
```

and the output file:
```json
{
	"issues": [
		{
			"engineId": "gosec",
			"ruleId": "G101",
			"primaryLocation": {
				"message": "Potential hardcoded credentials",
				"filePath": "/home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/helloWorld.go",
				"textRange": {
					"startLine": 6,
					"endLine": 6
				}
			},
			"type": "VULNERABILITY",
			"severity": "BLOCKER",
			"effortMinutes": 5
		}
	]
}
```

As you can see the output file does not include the GoProjects folder and as a consequence of this sonarqube does not upload this result on the server.
Everything works fine if the same file is located directly in the root repo.

### gosec version
Installed a few minutes ago through go get github.com/securego/gosec/cmd/gosec/... 
and latest release in github.com is 2.0.0

### Go version (output of 'go version')
1.12.3

### Operating system / Environment
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

### Expected behavior
FilePath in output file includes the GoProjects folder

### Actual behavior
FilePath in output file DOES NOT include the GoProjects folder

**Comment by andrea-tortosa** [comment]
@gcmurphy @ccojocar can you please look at this or route it ? Am I missing something in the process to have this taken into account ? I did not see any update or label assignement or comment from 3 days. Thanks a lot in advance

**Comment by gcmurphy** [comment]
@kmcrawford would you mind looking at this? I'm sure if it's related to your work with  https://github.com/securego/gosec/pull/288 or if it something related to the switch to go modules.

**Comment by kmcrawford** [comment]
@andrea-tortosa can you recreate this issue using the json format? 
`gosec -fmt=json -out gosec-report.json ./...`

**Comment by andrea-tortosa** [comment]
@kmcrawford no, this only occurs with sonarqube format

sonarqube output:
[gosec] 2019/05/14 09:40:28 Including rules: default
[gosec] 2019/05/14 09:40:28 Excluding rules: default
[gosec] 2019/05/14 09:40:28 Import directory: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/GoProjects
[gosec] 2019/05/14 09:40:30 Checking package: main
[gosec] 2019/05/14 09:40:30 Checking file: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/GoProjects/helloWorld.go
#####sonarqube output
{
	"issues": [
		{
			"engineId": "gosec",
			"ruleId": "G101",
			"primaryLocation": {
				"message": "Potential hardcoded credentials",
				"filePath": "/home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/helloWorld.go",
				"textRange": {
					"startLine": 6,
					"endLine": 6
				}
			},
			"type": "VULNERABILITY",
			"severity": "BLOCKER",
			"effortMinutes": 5
		}
	]
}

json output:
[gosec] 2019/05/14 09:40:30 Including rules: default
[gosec] 2019/05/14 09:40:30 Excluding rules: default
[gosec] 2019/05/14 09:40:30 Import directory: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/GoProjects
[gosec] 2019/05/14 09:40:31 Checking package: main
[gosec] 2019/05/14 09:40:31 Checking file: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/GoProjects/helloWorld.go
#####json output
{
	"Golang errors": {
		"/home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/GoProjects/helloWorld.go": [
			{
				"line": 6,
				"column": 6,
				"error": "password declared but not used"
			}
		]
	},
	"Issues": [
		{
			"severity": "HIGH",
			"confidence": "LOW",
			"rule_id": "G101",
			"details": "Potential hardcoded credentials",
			"file": "/home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/GoProjects/helloWorld.go",
			"code": "password = \"f62e5bcda4fae4f82370da0c6f20697b8f8447ef\"",
			"line": "6"
		}
	],
	"Stats": {
		"files": 1,
		"lines": 8,
		"nosec": 0,
		"found": 1
	}
}

**Comment by kmcrawford** [comment]
Ok I see. For sonarqube to work the path needs to be relative to what would be in the github repo since that’s all sonarqube knows about.  Does your project in github have a nested go project?

**Comment by andrea-tortosa** [comment]
I did some tests and I think sonarqube accepts absolute path or relative path with respect to the github repo root. The point is that if the file is into a GoProjects folder in the repo root, filepath must be set to the absolute path or to "filePath":"GoProjects/helloWorld.go". In every case GoProject folder must be part of filePath value if the file is into it. A value like "filePath": "helloWorld.go" could be acceptable only if the file is in the repo root.
The project I've mentioned above, and having helloWorld.go in GoProjects folder, is a sample one but I've looked at a real project and the github repo root is full of inner folders having *.go files, to which the issue here described applies.

**Comment by kmcrawford** [comment]
I'm not sure your test project structure is valid.  If I did a `go get github.ibm.com/andrea-tortosa/CICDBeta`  I don't believe go will build your project correctly.

**Comment by andrea-tortosa** [comment]
In my repo there are helloWorld.go

package main
import "fmt"
func main() {
        var password = "f62e5bcda4fae4f82370da0c6f20697b8f8447ef"
        fmt.Printf(password)
}

and Goprojects/helloWorld.go (that s the same file) and gosec -fmt=sonarqube -out gosec-report1.json ./... returns

########## GOSEC ##########
[gosec] 2019/05/14 21:17:02 Including rules: default
[gosec] 2019/05/14 21:17:02 Excluding rules: default
[gosec] 2019/05/14 21:17:02 Import directory: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/Goprojects
[gosec] 2019/05/14 21:17:04 Checking package: main
[gosec] 2019/05/14 21:17:04 Checking file: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/Goprojects/helloWorld.go
[gosec] 2019/05/14 21:17:04 Import directory: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta
[gosec] 2019/05/14 21:17:05 Checking package: main
[gosec] 2019/05/14 21:17:05 Checking file: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/helloWorld.go
#####sonarqube output
{
	"issues": [
		{
			"engineId": "gosec",
			"ruleId": "G101",
			"primaryLocation": {
				"message": "Potential hardcoded credentials",
				"filePath": "/home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/helloWorld.go",
				"textRange": {
					"startLine": 6,
					"endLine": 6
				}
			},
			"type": "VULNERABILITY",
			"severity": "BLOCKER",
			"effortMinutes": 5
		},
		{
			"engineId": "gosec",
			"ruleId": "G101",
			"primaryLocation": {
				"message": "Potential hardcoded credentials",
				"filePath": "/home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/helloWorld.go",
				"textRange": {
					"startLine": 6,
					"endLine": 6
				}
			},
			"type": "VULNERABILITY",
			"severity": "BLOCKER",
			"effortMinutes": 5
		}
	]
}

So the path is absolute (while in your case relative) and no filePath in the issue has Goprojects.
I definitely cannot understand what I m doing wrong.
I'm installing with .travis.yml

dist: xenial
sudo: required
language: go
go:
 - "1.12.3"
install:
 - git fetch --unshallow || true
 - go get github.com/securego/gosec/cmd/gosec/...
script:
 - ./scannerExec.sh

with scannerExec.sh having 
echo "########## GOSEC ##########"
gosec -fmt=sonarqube -out gosec-report1.json ./... || true
echo "#####sonarqube output"
cat gosec-report1.json

**Comment by andrea-tortosa** [comment]
I have renamed the Goprojects folder in test and it works fine, so the issue is with the Goprojects (or GoProjects) folder.

**Comment by andrea-tortosa** [comment]
If I rename ./test/helloWorld.go in ./projectFolder1/helloWorld.go I fall in the same issue. I definitely do not understand why some inner folders are not correctly managed ...

**Comment by andrea-tortosa** [comment]
I even got a case where previously correctly managed ./projects/projects/helloWorld.go has met the issue to then come back to work correctly.

**Comment by gcmurphy** [comment]
To debug this I suggest we log / printf the `rootPath`:
https://github.com/securego/gosec/pull/288/files#diff-0c95320f16dcfd667bc6d54332a8e51cR346

And also the `issue.File` here:
https://github.com/securego/gosec/pull/288/files#diff-346bc538756d1db6a67748b7feea6f39R122

Also is there anything in your GOPATH or other go related environment variables that you can share?

**Comment by andrea-tortosa** [comment]
```go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/travis/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/travis/gopath"
GOPROXY=""
GORACE=""
GOROOT="/home/travis/.gimme/versions/go1.12.3.linux.amd64"
GOTMPDIR=""
GOTOOLDIR="/home/travis/.gimme/versions/go1.12.3.linux.amd64/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build681385729=/tmp/go-build -gno-record-gcc-switches"```

**Comment by andrea-tortosa** [comment]
When the folder is correctly managed 

[gosec] 2019/06/14 16:02:38 Including rules: default
[gosec] 2019/06/14 16:02:38 Excluding rules: default
[gosec] 2019/06/14 16:02:38 Import directory: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta
[gosec] 2019/06/14 16:02:38 Checking package: main
[gosec] 2019/06/14 16:02:38 Checking file: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/goodbyeworld.go
[gosec] 2019/06/14 16:02:38 Import directory: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/test
[gosec] 2019/06/14 16:02:39 Checking package: main
[gosec] 2019/06/14 16:02:39 Checking file: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/test/helloWorld.go
**rootPath is . **
in saveOutput **issue file is /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/test/helloWorld.go** {
	"issues": [
		{
			"engineId": "gosec",
			"ruleId": "G101",
			"primaryLocation": {
				"message": "Potential hardcoded credentials",
				"filePath": "/home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/test/helloWorld.go",

**Comment by andrea-tortosa** [comment]
when the folder is not correctly managed 

[gosec] 2019/06/14 16:04:18 Including rules: default
[gosec] 2019/06/14 16:04:18 Excluding rules: default
[gosec] 2019/06/14 16:04:18 Import directory: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/GoProjects
[gosec] 2019/06/14 16:04:19 Checking package: main
[gosec] 2019/06/14 16:04:19 Checking file: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/GoProjects/helloWorld.go
[gosec] 2019/06/14 16:04:19 Import directory: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta
[gosec] 2019/06/14 16:04:20 Checking package: main
[gosec] 2019/06/14 16:04:20 Checking file: /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/goodbyeworld.go
**rootPath is GoProjects**
in saveOutput **issue file is /home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/GoProjects/helloWorld.go** {
	"issues": [
		{
			"engineId": "gosec",
			"ruleId": "G101",
			"primaryLocation": {
				"message": "Potential hardcoded credentials",
				"filePath": "/home/travis/gopath/src/github.ibm.com/andrea-tortosa/CICDBeta/helloWorld.go",

So the issue seems to be that rootpath is sometimes different from . and in that case replaced with nothing. I think the line could be

```FilePath: strings.Replace(issue.File, rootPath+"/", "", 1)```

that has no effect on .
Just to remind: if the formatted output does not have a real path to the file, SonarQube won't upload that issue.

**Comment by ccojocar** [comment]
@andrea-tortosa Please have a look at the PR which is fixing the file path in Sonarqube report, and let me know if it works for you? Thanks

**Comment by andrea-tortosa** [comment]
@ccojocar I've tried both with your branch and master and it works fine to me ! Thanks a lot
