### ISSUE TITLE
G102 Bind to all interfaces false positive

### ISSUE THREAD

**Issue by sergey-shambir** [securego/gosec#319]
### Summary 

G102 gives false positive when I use named constant to specify bind address.

### Steps to reproduce the behavior

Just use constant instead of literal with `net.Listen`:

```go
const (
	// ServiceGRPCPort - port for GRPC API
	serviceGRPCPort = ":8081"
)

func main() {
    // ...
    grpcListener, grpcErr := net.Listen("tcp", serviceGRPCPort)
    if err != nil {
        return errors.Wrapf(grpcErr, "failed to listen port %s", serviceGRPCPort)
    }
    // ...
}
```

### gosec version

gosec embedded into golangci-lint v1.16.0 (revision from 1 Sep 2018 according to [go.mod](https://github.com/golangci/golangci-lint/blob/d437ac86293ff0e18e8b2b153d65f1622ac58806/go.mod).

### Go version (output of 'go version')

`go version go1.12.1 linux/amd64`

### Operating system / Environment

Debian 9.

### Expected behavior

gosec checks to constant value (and optionally claims when there is variable or expression instead of constant)

### Actual behavior

gosec just checks literal with regular expression

**Comment by gcmurphy** [comment]
From the `net` package docs [here](https://golang.org/pkg/net/#Listen): 

> For TCP networks, if the host in the address parameter is empty or a literal unspecified IP address, Listen listens on all available unicast and anycast IP addresses of the local system.

The constant ":8081" is a literal unspecified IP address so the connection in the reproducer will listen on all available network interfaces. So I think this is working as intended unless I'm missing something.

**Comment by sergey-shambir** [comment]
Yes, you're right ;)
Thanks a lot!
