### ISSUE TITLE
Can anyone explain to me what the purpose of the G305 rule is? And how to improve it, thank you

### ISSUE THREAD

**Issue by githubyb** [securego/gosec#324]

**Comment by MVrachev** [comment]
I am helping slowly helping with the implementation of good documentation.
Until it's ready you can always look at the `gosec/testutils/source.go` file for examples.

Here are the examples for rule G305:
https://github.com/securego/gosec/blob/196edd34b659a90544c6ceaf30dae554da6e4203/testutils/source.go#L783

**Comment by gcmurphy** [comment]
The rule is attempting to detect the behaviour described in: https://snyk.io/research/zip-slip-vulnerability.The way it works it to check if filepath.Join uses any argument derived from type zip.File. Right now that is a pretty basic check but should be fairly effective.

**Comment by githubyb** [comment]
I think I already know the risks involved in decompressing files, thank you for your work.

**Comment by jackytck** [comment]
If the path derived from filename is already checked (as in https://snyk.io/research/zip-slip-vulnerability), this rule also flags it as vulnerable.
