### ISSUE TITLE
SQL String formatting with string constants

### ISSUE THREAD

**Issue by bytheway** [securego/gosec#325]
### Summary 

Currently using formatting with a constant argument will trigger G201 (this was fixed in SQL Concatenation in #169, #247)

### Steps to reproduce the behavior
```
package main

import "fmt"

const (
  Table = "Events"
)

func main() {
  fmt.Sprintf("SELECT count(*) FROM %s", Table)
}
```

### gosec version
master

### Go version (output of 'go version')

go version go1.12.2 darwin/amd64

### Operating system / Environment

macOS Mojave (10.14.5)

### Expected behavior

Constructing SQL statements with *printf should be allowed with constants.

### Actual behavior

G201: SQL string formatting (Confidence: HIGH, Severity: MEDIUM)

**Comment by gcmurphy** [comment]
Fixed in #326
