### ISSUE TITLE
vuln not detected because of dependency code is not in the workspace

### ISSUE THREAD

**Issue by andrea-tortosa** [securego/gosec#337]
### Summary 
gosec sonarqube format returns
```
{
	"issues": []
}
```
when it should not because a vulnerability is in the code.

### Steps to reproduce the behavior
Running
```
gosec -fmt=sonarqube -out gosec-report.json ./... 
```
within a cloned repo integrated with Travis and just containing a main.go file as:

```go
package main

import (	
	"fmt"	
	"github.com/streadway/amqp"
)

func main() {	
	var password = "f62e5bcda4fae4f82370da0c6f20697b8f8447ef"
	fmt.Printf(password)
}
```
it gets the behavior above described. If the file is modified to 
```go
package main

import (	
	"fmt"	
	"math"
)

func main() {	
	var password = "f62e5bcda4fae4f82370da0c6f20697b8f8447ef"
	fmt.Printf(password)
}
```
the following is correctly returned
```
{
	"issues": [
		{
			"engineId": "gosec",
			"ruleId": "G101",
			"primaryLocation": {
				"message": "Potential hardcoded credentials",
				"filePath": "main.go",
				"textRange": {
					"startLine": 9,
					"endLine": 9
				}
			},
			"type": "VULNERABILITY",
			"severity": "BLOCKER",
			"effortMinutes": 5
		}
	]
}
```
The reason of the behavior is the dependency code is not available in the workspace to be scanned (being the code deployed with a git clone). However the available code should be scanned and the existing vulnerability detected instead of getting NPE and return an empty array (see issue #333),
Used Sonar scanner cli version is sonar-scanner-4.0.0.1744-linux.

### gosec version
Installed a few minutes ago through go get github.com/securego/gosec/cmd/gosec/... 
and latest release in github.com is 2.0.0

### Go version (output of 'go version')
1.12.3

### Operating system / Environment
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

### Expected behavior
G101 vulnerability should be detected because gosec should scan the available code instead of getting an empty array

### Actual behavior
G101 vulnerability is not detected and an empty array is returned

**Comment by gcmurphy** [comment]
This is interesting as I'm unable to reproduce this locally via the current `master` or even with `2.0.0` install. 

```go
package main

import (
	"fmt"
	"github.com/doesnt/exist"
)

func main() {
	var password = "f62e5bcda4fae4f82370da0c6f20697b8f8447ef"
	fmt.Printf(password)
}
```

Running the current master (after doing a `GO111MODULE=on make`)

```
▶ ./gosec ~/tmp/test/...
[gosec] 2019/07/16 09:32:53 Including rules: default
[gosec] 2019/07/16 09:32:53 Excluding rules: default
[gosec] 2019/07/16 09:32:53 Import directory: /Users/grantmurphy/tmp/test
[gosec] 2019/07/16 09:32:54 Checking package: main
[gosec] 2019/07/16 09:32:54 Checking file: /Users/grantmurphy/tmp/test/main.go
Results:

Golang errors in file: [/Users/grantmurphy/tmp/test/main.go]:

  > [line 5 : column 2] - "github.com/doesnt/exist" imported but not used

  > [line 5 : column 2] - could not import github.com/doesnt/exist (invalid package name: "")



[/Users/grantmurphy/tmp/test/main.go:9] - G101: Potential hardcoded credentials (Confidence: LOW, Severity: HIGH)
  > password = "f62e5bcda4fae4f82370da0c6f20697b8f8447ef"


Summary:
   Files: 1
   Lines: 11
   Nosec: 0
  Issues: 1
```

And with sonarqube output: 
```
 ./gosec -fmt=sonarqube ~/tmp/test/...
[gosec] 2019/07/16 09:33:33 Including rules: default
[gosec] 2019/07/16 09:33:33 Excluding rules: default
[gosec] 2019/07/16 09:33:33 Import directory: /Users/grantmurphy/tmp/test
[gosec] 2019/07/16 09:33:34 Checking package: main
[gosec] 2019/07/16 09:33:34 Checking file: /Users/grantmurphy/tmp/test/main.go
{
	"issues": [
		{
			"engineId": "gosec",
			"ruleId": "G101",
			"primaryLocation": {
				"message": "Potential hardcoded credentials",
				"filePath": "main.go",
				"textRange": {
					"startLine": 9,
					"endLine": 9
				}
			},
			"type": "VULNERABILITY",
			"severity": "BLOCKER",
			"effortMinutes": 5
		}
	]
}%                                                                                                                                                                            
```

Out of interest what happens if you just do a plain gosec run without specifying sonarqube as the output format?

**Comment by andrea-tortosa** [comment]
The issue occurs the same even without specifying sonarqube as the output format. 
I have however realized that I reproduce the issue with GO111MODULE=auto and not with GO111MODULE=on (dependencies are not locally downloaded in both cases).

**Comment by ccojocar** [comment]
The dependencies are automatically downloaded only when `GO111MODULE=on` is set. Can we close this issue?

**Comment by andrea-tortosa** [comment]
I do not see `github.com/streadway/amqp` dependency downloaded in any case of `export GO111MODULE=off/auto/on` looking at `ls -la /home/travis/gopath/src/github.com/*` 
The same path is instead populated with the dependencies if I run `go get -d` for that repo before to scan and when the dependencies are downloaded everything works fine whatever is the value of `GO111MODULE`
The key point is that -- if dependencies are not explicitly downloaded -- gosec runs correctly when `export GO111MODULE=on` while it exits abnormally in other cases since it does not detect the vulnerability that is in the custom code. 
The potential problem is that it should detect the vulnerability existing in the custom code also when `export GO111MODULE=off/auto` and dependencies are not downloaded.

**Comment by ccojocar** [comment]
Yes, `gosec` expects that the dependencies are already available. We can add a note in the documentation to make it clear. What do you think? 

It would be great if we could keep the dependencies management outside of `gosec` because this will bring more complexity into the tool. There are other tools as you mentioned `go get -d` in case the dependencies need to be fetched.

**Comment by andrea-tortosa** [comment]
ok, I agree, a note in the documentation would help a lot. thx
