### ISSUE TITLE
False positive: SQL Injection

### ISSUE THREAD

**Issue by jaipradeesh** [securego/gosec#341]
### Summary

G201 raised as a false positive here -- https://github.com/jaipradeesh/stripe-cli/blob/f4c886e696d0fb26757e05d1024ceafafa3aaaa4/pkg/cmd/delete.go#L27

### Steps to reproduce the behavior

Run G201

### gosec version

`2.0.0`

### Go version (output of 'go version')

```
go version
go version go1.12.7 darwin/amd64
```

### Operating system / Environment

```
macOS Mojave -- v 10.14.6
```

**Comment by ccojocar** [comment]
I created #345 as a follow up for this issue. Do you think can we close this for now?
