### ISSUE TITLE
Add the possibility to change the '#nosec' comment to something else

### ISSUE THREAD

**Issue by Krlier** [securego/gosec#344]
### Summary 
It would be great if we were able to change the `nosec` commentary to any other that a developer provides.

### Steps to reproduce the behavior
1. Scan a golang code and get the report

### Expected behavior
```go
import "md5" // #dontanalyze


func main(){

    /* #dontanalyze */
    if x > y {
        h := md5.New() // this will also be ignored
    }

}
```

### Actual behavior
```go
import "md5" // #nosec


func main(){

    /* #nosec */
    if x > y {
        h := md5.New() // this will also be ignored
    }

}
```

What do you guys think of this addition? I'm willing to help code this change!

**Comment by ccojocar** [comment]
What's the advantage of having a custom directive name for excluding the warnings?

 In that case, it is probably required to keep the configuration specific per project and to load it before the scan. This can complicate the things and create confusion.

**Comment by Krlier** [comment]
Thanks for the quick response, @ccojocar!

I'm currently working in [huskyCI](https://github.com/globocom/huskyCI), a tool that allows you to perform security tests inside your CI, and we are currently using open source checks such as: GoSec for Golang, Bandit for Python and Brakeman for Ruby. Using huskyCI, the developer no longer needs to worry about which security test is appropriate for the language he is currently working with.

The feature I'm trying to develop for huskyCI is inspired on you guys, my ideia is to create an all languages wide directive name that excludes warnings, something along the lines of `#nohusky`. The lines with this tag would be excluded from huskyCI's final output, no matter the programming language the tool is currently running on.

Due to the fact that GoSec's output doesn't show comments in the `Code` field, I am in need of an alternative to implement the feature above. One of the possibilities I thought, was to change GoSec's directive name, this way the developer could use the tag for huskyCI and it would be able handle it.

When I thought on how to implement it on Gosec, my first thought was to pass it as command line parameter, something like this:
```sh
gosec -nosectag='#nohusky' ./...
``` 
If no string is provided for `-nosectag`, then the default string, `nosec`, should be used.

**Comment by ccojocar** [comment]
Thanks for clarification! I understand now why you need to configure it. The proposed implementation sounds good to me. It would be great if you could prepare a PR for it.
