### ISSUE TITLE
Improve accuracy of SQL rule

### ISSUE THREAD

**Issue by ccojocar** [securego/gosec#345]
### Summary 

The sql rule is using only a regexp expression to identify when is a SQL query into a constant string. 

https://github.com/securego/gosec/blob/4b59c948083cd711b6a8aac8f32721b164899f57/rules/sql.go#L204

This generates quite some false positives (See issues  #341 and #264). It would be great to improve its accuracy. There are various options to achieve this:
 - Improve the heuristic of the rule by checking more acuratly the context - see @gcmurphy's suggestions in the comments below 
- Investigate if a SQL parser can validate additionally the syntax in certain use cases when the query can be reconstructed - possible SQL parse https://github.com/xwb1989/sqlparser. 

### Expected behavior

Reduce the number of false positive warnings generated by the rule.

### Actual behavior

It doesn't really differentiate between a plain string starting with a SQL keyword (e.g. SELECT) and a valid SQL query.

**Comment by gdhameeja** [comment]
I'd like to work on this.

**Comment by ccojocar** [comment]
Great! Feel free to join our slack channel if you have any question.

**Comment by gcmurphy** [comment]
The places where we're creating issues are typically when a SQL query is being constructed by concatenation or string interpolation. In the examples below the SQL query we're matching on will not likely be considered valid by the SQL parser would they?

`q :=  fmt.Sprintf("SELECT * from foo where bar = %s", untrustedVar)`

or 

` q := "SELECT * from foo where bar = " + untrustedVar`

There might be a way around this but just an initial thought around actual parsing of the SQL syntax. The other potential issue is DB compatibility, but I'm less worried about that TBH. 

There's potentially a couple of things we could do to improve the confidence of the rule. Simple things like checking if 'database/sql' is imported of if the matched string is being used in a db.Query or db.Exec call could help reduce false positives.

**Comment by ccojocar** [comment]
My initial thinking was that we can somehow reconstruct the query and run it through a SQL parser to validate it, but I realise that it is not really possible when parts of the query are stored in various variables - they are only available at runtime. 

I agree that adding some better heuristic in the detection can improve significantly the rule accuracy. 

I am going to change the title to reflect better the scope of this work.

**Comment by ccojocar** [comment]
@gcmurphy I updated also the description to point first to you suggestions. Thanks for reviewing this!

**Comment by ccojocar** [comment]
Fixed by https://github.com/securego/gosec/pull/479
