### ISSUE TITLE
Please consider creating semver compatible tags

### ISSUE THREAD

**Issue by SamWhited** [securego/gosec#347]
Right now the tags are of the form `2.0.0` which is incompatible with Go Modules which expects `v2.0.0`. Please consider adding tags with the `v` prefix so that I can pin to a specific version of gosec in my own go.mod files easier (eg. for running this in CI and making sure I always run with the same version of gosec).

This can be done for 1.x versions without breaking anything. For `2.0.0` there is a slight problem in that modules also expects that import paths will have a `/v2` prefix. Since this is not the case but a go.mod file is present, it would end up with a `+incompatible` import, which isn't the end of the world but it would also be nice if the version suffix could be fixed.

Thank you for your consideration.

**Comment by ccojocar** [comment]
@SamWhited Thanks for pointing this out! I updated the release instructions in the README. The next release will use a `v` prefix for tag.
