### ISSUE TITLE
G201 and G202 (SQL query construction) do not detect lowercase SQL keywords

### ISSUE THREAD

**Issue by nchelluri** [securego/gosec#369]
### Summary 
(I tested this for G201 but inspected the code for G202 and believe it has the same issue.)

G201 will detect SQL string formatting when I have `fmt.Sprintf("SELECT * FROM TEST UNION %s", "SELECT * FROM test")` in my code. However, it will not detect when I have `fmt.Sprintf("select * from test union %s", "select * from test")` in my code. I believe this is a bug.

See: https://github.com/securego/gosec/blob/2.0.0/rules/sql.go#L184 and https://github.com/securego/gosec/blob/2.0.0/rules/sql.go#L94

### Steps to reproduce the behavior
Create a file `sql.go` with the following content:
```
package main

import "fmt"

func sqlConstructionLowercase() string {
	return fmt.Sprintf("select * from test union %s", "select * from test")
}

func sqlConstructionUppercase() string {
	return fmt.Sprintf("SELECT * FROM TEST UNION %s", "SELECT * FROM test")
}

func main() {
	fmt.Println(sqlConstructionLowercase())
	fmt.Println(sqlConstructionUppercase())
}
```

Run `gosec` on it:

```
vagrant@ct100-test:~/dev/gosec/sql $ ../gosec .
[gosec] 2019/09/12 11:48:21 Including rules: default
[gosec] 2019/09/12 11:48:21 Excluding rules: default
[gosec] 2019/09/12 11:48:21 Import directory: /home/vagrant/dev/gosec/sql
[gosec] 2019/09/12 11:48:21 Checking package: main
[gosec] 2019/09/12 11:48:21 Checking file: /home/vagrant/dev/gosec/sql/sql.go
Results:


[/home/vagrant/dev/gosec/sql/sql.go:10] - G201: SQL string formatting (Confidence: HIGH, Severity: MEDIUM)
  > fmt.Sprintf("SELECT * FROM TEST UNION %s", "SELECT * FROM test")


Summary:
   Files: 1
   Lines: 16
   Nosec: 0
  Issues: 1

vagrant@ct100-test:~/dev/gosec/sql $ 
```

Only the uppercased version is shown as a problem. Both should be.

### gosec version
```
VERSION: 2.0.0
GIT TAG: 2.0.0
BUILD DATE: 2019-05-02T15:22:02Z
```

### Go version (output of 'go version')
```
go version go1.12.9 linux/amd64
```

### Operating system / Environment
Ubuntu 18.04.3 LTS

### Expected behavior
Lowercased SQL keywords are still inspected for SQL string formatting and SQL string concatenation problems.

### Actual behavior
SQL strings composed of lowercase SQL keywords are not inspected for SQL string formatting and SQL string concatenation problems.

**Comment by lukasaron** [comment]
I would propose to fix this bug with the easy fix - add flag into the regular expression to add the ability to match patterns case-insensitive. The whole improvement about the SQL heuristic can be done as a new feature.

**Comment by ccojocar** [comment]
I think only switching the query regex to a case insensitive matche will lead to a lot of false positives because this rule is matching the text in all `Sprint` functions family. I tried this in the past. 

I think we can improve this a bit by looking for `db.Query` call, and the track back the first argument which is the query string. If this argument originates from a Sprintf  kind of function we can apply regexp case insensitive on the argument.

**Comment by ccojocar** [comment]
Fixed by https://github.com/securego/gosec/pull/479
