### ISSUE TITLE
Build Tag Option is not respected

### ISSUE THREAD

**Issue by nishils** [securego/gosec#393]
### Summary 
Gosec does not appear to respect build tags passed via the tags flag. I have confirmed that my code can be built but gosec sees an error when building the codebase.

### Steps to reproduce the behavior
Code Samples

hello.go
```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("hello, from the vulnerable app" + DB_USER)
}
```

config_prod.go
```
// +build prod

package main

const (
	DB          = "localhost"
	DB_USER     = "prod"
	DB_PASSWORD = "hhend77dyyydbh&^psNSSZ)JSM--_%"
)
```
Just to note the above password isn't real. I am simply trying to trigger gosec into a issuing a finding.

### gosec version
Head of master

### Go version (output of 'go version')
`go1.12.4 darwin/amd64`

### Operating system / Environment
OSX

### Expected behavior
It successfully uses the build tag.

### Actual behavior
```
➜  buildtags_goapp git:(support-gosec-options) ✗ gosec -tags=prod ./...
[gosec] 2019/09/26 14:46:02 Including rules: default
[gosec] 2019/09/26 14:46:02 Excluding rules: default
[gosec] 2019/09/26 14:46:02 Import directory: <some_path>/buildtags_goapp
[gosec] 2019/09/26 14:46:02 Checking package: main
[gosec] 2019/09/26 14:46:02 Checking file: <some_path>/buildtags_goapp/hello.go
Results:

Golang errors in file: [<some_path>/buildtags_goapp/hello.go]:

  > [line 8 : column 49] - undeclared name: DB_USER



Summary:
   Files: 1
   Lines: 9
   Nosec: 0
  Issues: 0
```

If I run `go build -tags dev ./...`, I get a successful build.

**Comment by ccojocar** [comment]
The tags seems to be propagated to the packages loader and further down to the complier driver but somehow they get ignored. 

https://github.com/securego/gosec/blob/832d7bb398c29cc172e4648455513ddfad983e8c/analyzer.go#L139

Checking the `packages` tests and this seems the expected way to provide the build tags:
https://github.com/golang/tools/blob/7c411dea38b0106295d041581abb0a958e571b7d/go/packages/packages_test.go#L481

We need to investigate a bit more to find where is the issue.
