### ISSUE TITLE
A bug when the analyser get code line ?

### ISSUE THREAD

**Issue by yxyhack** [securego/gosec#397]
parsing errors in pkg "main": parsing line: **strconv.Atoi: parsing** "\\Users\\Tester\\go\\src\\github.com\\vitelabs\\go-vite\\cmd\\printer\\main.go": invalid syntax

**Comment by ccojocar** [comment]
Can you run `go build` successfully on that file? Can you provider the snippet of code?

**Comment by ccojocar** [comment]
This looks to me like a compilation issue. I am going to close it for now. Please feel free to open it again with more details. Thanks!
