### ISSUE TITLE
Cant Install gosec

### ISSUE THREAD

**Issue by irvana** [securego/gosec#401]
### Summary 
Cannot get gosec -> `go get  github.com/securego/gosec/cmd/gosec` 

### Steps to reproduce the behavior
just run  `go get  github.com/securego/gosec/cmd/gosec` 

### gosec version
i believe it will refer to your last release
### Go version (output of 'go version')
1.10
```
# golang.org/x/tools/go/gcexportdata
../../../golang.org/x/tools/go/gcexportdata/gcexportdata.go:103:12: undefined: gcimporter.IExportData
```

### Operating system / Environment
Ubuntu 16.04
### Expected behavior
run smoothly
### Actual behavior
can't install it

**Comment by ccojocar** [comment]
We don't support Go version 1.10 anymore ttps://github.com/securego/gosec/blob/master/.travis.yml. 

Please try with 1.11 and feel free to reopen this issue if you have the same error. Thanks!
