### ISSUE TITLE
go get @v2.1.0 as a module fails

### ISSUE THREAD

**Issue by kylebrandt** [securego/gosec#404]
### Summary 

Go Modules are fun.

Reference issues: https://github.com/securego/gosec/issues/347 https://github.com/securego/gosec/issues/234

### Steps to reproduce the behavior

With go 1.13, outside of GOPATH

```
$ go get github.com/securego/gosec@v2.1.0
go: finding github.com/securego/gosec v2.1.0
go: finding github.com/securego/gosec v2.1.0
go get github.com/securego/gosec@v2.1.0: github.com/securego/gosec@v2.1.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

> module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

As per The [go wiki](https://github.com/golang/go/wiki/Modules#semantic-import-versioning):

> If the module is version v2 or higher, the major version of the module must be included as a /vN at the end of the module paths used in go.mod files (e.g., module github.com/my/mod/v2, require github.com/my/mod/v2 v2.0.1) and in the package import path (e.g., import "github.com/my/mod/v2/mypkg"). This includes the paths used in go get commands (e.g., go get github.com/my/mod/v2@v2.0.1. Note there is both a /v2 and a @v2.0.1 in that example. One way to think about it is that the module name now includes the /v2, so include /v2 whenever you are using the module name).

So I think it is that everything is not in a v2 folder, but the tags are at v2 (or the mod file doesn't have /v2 and v2 import statements in the file: https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by sam-github** [comment]
I just ran into this, trying to fix the version of gosec I use with the approach in https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module, and pin my gosec version to the latest tag, v2.2.0.

```
% go list -u -m github.com/securego/gosec
go: finding github.com/securego/gosec latest
github.com/securego/gosec v0.0.0-20200129084146-17df5b370244
% go list -u -m github.com/securego/gosec/v2
go list -m: module github.com/securego/gosec/v2: not a known dependency
% GOBIN=$PWD/bin go install github.com/securego/gosec/v2
go: finding github.com/securego/gosec latest
can't load package: package github.com/securego/gosec/v2: module github.com/securego/gosec@latest found (v0.0.0-20200129084146-17df5b370244), but does not contain package github.com/securego/gosec/v2
```

go modules are convinced that gosec is still a v0.0.0, at least with v1.13:
```
% go version 
go version go1.13.4 linux/amd64
```

**Comment by ccojocar** [comment]
Thanks for input. I'll try to have a look at this as soon as I'll have some spare cycles. I am happy to accept any contributions in case you have time to come up with something which fix Go modules for v2.

**Comment by jpopadak** [comment]
Seems to have the same issue but looks to be an issue with using Go 1.13 and not properly following the `v2` subfolder idea required by Go. 
If anything is > v1.x.x, then there needs to be a folder in the root named `v2` of which has all the necessary files needed for v2 of that API. Most people copy and paste all Go files into v2 and then modify as needed for v2.

https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
