### ISSUE TITLE
Question regarding release plan

### ISSUE THREAD

**Issue by julianthome** [securego/gosec#413]
This is not really an issue in relation to the `gosec` source code 😄 

I was just wondering whether there is some sort of release plan for `gosec` because the time-frame between releases that are published so far seems to vary from 1 to 6 months (https://github.com/securego/gosec/releases) and I could not find a hint in the documentation in which way releases are planned (time frames between releases, criteria for building a new release, how a release is prepared, etc.).  

Thank you very much for your help.

**Comment by ccojocar** [comment]
We didn't follow a defined release timeline. it was manly trigger by the amount of changes in master because the contributions frequency is not constant.

**Comment by julianthome** [comment]
Ok, thanks a lot for the explanation @ccojocar 👍

**Comment by julianthome** [comment]
Would it be possible to prepare a new release? I am just asking because we would like to integrate a release which includes the changes from https://github.com/securego/gosec/pull/405 into the gosec wrapper we use at GitLab.

 Thank you very much again for your help and kind regards,
  Julian

**Comment by ccojocar** [comment]
I will do a minor release as soon as soon as the opened PRs gets merged. Thanks! I am going to close this for now.

**Comment by julianthome** [comment]
Great! Thank you very much @ccojocar 👍
