### ISSUE TITLE
Add rules for regular expressions (regexp)

### ISSUE THREAD

**Issue by dcu** [securego/gosec#414]
### Summary 
Add some rules for regular expressions like: https://github.com/attackercan/regexp-security-cheatsheet

Especially ^$ can introduce some security issues when validating data

**Comment by ccojocar** [comment]
I think this would be a useful addition. Probably leveraging the opcode by the regexp parser will be best. https://golang.org/pkg/regexp/syntax/#Op.

This might be also interested to have a look at https://github.com/substack/safe-regex.

**Comment by gcmurphy** [comment]
FWIW Go is reasonably safe wrt ReDOS type attacks - see https://checkmarx.com/blog/redos-go/.

**Comment by ccojocar** [comment]
Not clear what is the security value of such a rule in the context of Go which is quite safe with respect to regular expressions. Closing for now.
