### ISSUE TITLE
no way to solve pprof issue

### ISSUE THREAD

**Issue by bmon** [securego/gosec#418]
### Summary 
When using pprof, there is no way to "correctly" enable the pprof endpoints such that G108 is not triggered. #257 references an [article](https://mmcloughlin.com/posts/your-pprof-is-showing) which states exposing the default router on a non standard "port is a simple an effective option" to avoiding the security issues highligted in the article, however even the sample, secure code provided in the article will trigger G108.

### Steps to reproduce the behavior
```go
// main.go
package main

import (
	"fmt"
	"log"
	"net/http"
	_ "net/http/pprof"
)

func main() {
	// Pprof server.
	go func() {
		log.Fatal(http.ListenAndServe("localhost:8081", nil))
	}()

	// Application server.
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Hello World!")
	})
	log.Fatal(http.ListenAndServe(":8080", mux))
}
```
### gosec version
df484bf
### Go version (output of 'go version')
go version go1.13.4 linux/amd64
### Operating system / Environment
linux
### Expected behavior
Importing `net/http/pprof` and exposing the `DefaultServeMux` on a non-standard port (i.e 6060) will not trigger G108.
### Actual behavior
Importing `net/http/pprof` always triggers G108.

**Comment by gcmurphy** [comment]
The pprof rule is designed to be a warn / audit class of rule. It is unlikely that we will be able to detect the disarming of it in a reliable way. e.g. How can we definitively tie the "localhost:8081" to pprof in the example above? 

A work around will be to add a `// #nosec` comment to import of "net/http/pprof".
