### ISSUE TITLE
Files not clickable to Goland

### ISSUE THREAD

**Issue by jtorvald** [securego/gosec#424]
### Summary 
Most of the linters start with the path to the file:linenumber this gets clickable in Goland. The way gosec uses [path] prevents files with row numbers being clickable.

### Steps to reproduce the behavior
run the command

### gosec version
latest

### Go version (output of 'go version')
go version go1.13.5 darwin/amd64

### Operating system / Environment
MacOS

### Expected behavior
/path/to/file:500

### Actual behavior
[/path/to/file:500]

**Comment by rung** [comment]
Hi, 

I just made new issue (https://github.com/securego/gosec/issues/423)
and the file paths on Goland will be clickable if gosec has the same format as golint.

When maintainers(@ccojocar) says ok, I'll send new PR.

![image](https://user-images.githubusercontent.com/1150301/71493996-34d08c00-2887-11ea-8404-cf11859ad857.png)

Thank you.

**Comment by ccojocar** [comment]
@rung happy to see a PR for this. Thanks!

**Comment by ccojocar** [comment]
fixed by https://github.com/securego/gosec/pull/428

**Comment by jtorvald** [comment]
@rung @ccojocar  Thanks!
