### ISSUE TITLE
G204: false positive on exec.CommandContext's ctx

### ISSUE THREAD

**Issue by carnott-snap** [securego/gosec#436]
### Summary
G204 does not play nice with the required `context.Context` that `exec.CommandContext` takes as its first parameter:
```go
package exec // import "os/exec"

func CommandContext(ctx context.Context, name string, arg ...string) *Cmd
    CommandContext is like Command but includes a context.

    The provided context is used to kill the process (by calling
    os.Process.Kill) if the context becomes done before the command completes on
    its own.
```

### Steps to reproduce the behaviour
```go
exec.CommandContext(contex.Background(), "git", "rev-parse", "--show-toplevel")
```

### gosec version
`v0.0.0-20200103095621-79fbf3af8d83`

### Go version (output of 'go version')
`go version go1.13.7 linux/amd64`

### Operating system / Environment
`linux/amd64`

### Expected behaviour
The `context.Context` parameter should be excluded from this lint.

### Actual behaviour
```
G204: Subprocess launched with function call as argument or cmd arguments (gosec)
```

**Comment by ccojocar** [comment]
Thanks for reporting this! It looks like a bug which we could easily fix.
