### ISSUE TITLE
Feature request: support colored output

### ISSUE THREAD

**Issue by oxdef** [securego/gosec#456]
### Summary 
It will be great if `gosec` support colored output like `grep` one.  

### Steps to reproduce the behavior
Try to inspect source code for security problems with `gosec -fmt=text  ./...`

### Expected behavior
We can use terminal color codes to color text output if special CLI flag is specified, e.g. `-color`

### Actual behavior
Plain text output with information about findings

**Comment by marcosinger** [comment]
Hi @oxdef & @ccojocar,

As a newcomer, I'd like to help on that task, but I have a few questions about it:

- which report's part we want to add color? file-path and summary items are good enough?
- which color schema use on those elements? I was thinking of using the user's terminal color schema, and I'm aware there is a `LSCOLORS` environment variable on Linux to try to get this information, but I'm not sure if it will work on other OSs / specific terminal apps;

I'm OK to start it in an easy way, defining some default colors (e.g., blue for files on `Checking file`, green for zero values on `Nosec` and `Issues`) and evolve this on future steps.

Let me know what do you think so I could plan this :)
Thanks!

**Comment by ccojocar** [comment]
Hi @marcosinger, I don't have a strong opinion about this. Fell free to create a pull request and we can iterate on it. Thanks

**Comment by oxdef** [comment]
@marcosinger Thanks for this contribution!
