### ISSUE TITLE
[Feature]Can our end-user as a contributor for the `secure.io` rules intro document?

### ISSUE THREAD

**Issue by Aisuko** [securego/gosec#461]
### Summary 

Hi, guys thanks for development the mazing project to help golang developer check the code statically. But I saw issue #127(especially G304) and I'm struggling with this issue too. The community document just includes four rules, so could you please open the community document(https://securego.io). And I believe that more contributor would like to contribute more e.g explaining, example for the rules

**Comment by ccojocar** [comment]
@Aisuko Thanks for bringing this up. Fell free to send any doc improvements in a pull request to https://github.com/securego/securego.github.io.  This is where we keep the docs site which gets redeployed as a GitHub page. 

I am going to close this issue. Also you can join the slack team if you have any other questions. We are happy to help you and really appreciate any contribution to the docs. 

Thanks again!
