### ISSUE TITLE
No CWE for G601

### ISSUE THREAD

**Issue by tko** [securego/gosec#482]
The README states
> ### CWE Mapping
> 
> Every issue detected by `gosec` is mapped to a [CWE (Common Weakness Enumeration)](http://cwe.mitre.org/data/index.html) which describes in more generic terms the vulnerability. The exact mapping can be found  [here](https://github.com/securego/gosec/blob/53be8dd8644ee48802114178cff6eb7e29757414/issue.go#L49).

However, rule G601 isn't mapped to any CWE there. And on quick glance some G1xx and G3xx rules listed in readme are also missing.

**Comment by ccojocar** [comment]
This was recently fixed. Please check https://github.com/securego/gosec/blob/826db1cfecece26abb660b13e18fb619e02deb11/issue.go#L79.

**Comment by tko** [comment]
Ah. The README is still linking to old version though, https://github.com/securego/gosec/blob/53be8dd8644ee48802114178cff6eb7e29757414/issue.go#L49

**Comment by ccojocar** [comment]
Thanks! I updated the README.
