### ISSUE TITLE
G404: Rule does not include `rand.Intn()`

### ISSUE THREAD

**Issue by dpeckett** [securego/gosec#486]
### Summary 

G404 rule does not include `rand.Intn()` or other `rand` methods. Should the rule be extended?

### Steps to reproduce the behavior

Create a file `main.go` with the following content:

```go
package main
import "math/rand"
func main() {
	bad := rand.Intn(10)
	println(bad)
}
```
gosec will pass the code and not raise an issue.

### gosec version

```
v2.3.0
```

### Go version (output of 'go version')

```
go version go1.14.4 linux/amd64
```

### Operating system / Environment

```
linux/amd64
```

### Expected behavior

The rule G404 should match `rand.Intn()` invocations / potentially all rand methods.

### Actual behavior

The rule G404 only matches `rand.Read()` and `rand.Int()`.

**Comment by ccojocar** [comment]
Yeah, I added more functions to the blacklist.

**Comment by dpeckett** [comment]
Awesome, thanks mate.

**Comment by bconway** [comment]
Just ran into this today with the latest update to golangci-lint. Why are you including `Intn()` if there is no `crypto` alternative to it? Is the intent that users should rewrite their own `Intn()` using `crypto`? I would suggest that would lead to worse results in the long run.
