### ISSUE TITLE
G304: os.Open() and. os.OpenFile()

### ISSUE THREAD

**Issue by MrHappyCPP** [securego/gosec#488]
### Summary 

Is there a particular reason why an error G304 is thrown with os.Open() but not with os.OpenFile()?
Since os.Open() is only a wrapper for os.OpenFile(), this seems strange to me.

### gosec version
current master

### Expected behavior
G304 is created for os.Open() and os.OpenFile()

### Actual behavior
G304 only thrown for os.Open(someString)

**Comment by ccojocar** [comment]
That call was missed from the rule. Thanks for bringing this up. I raised a PR which it will add it.

**Comment by MrHappyCPP** [comment]
@ccojocar thx
