### ISSUE TITLE
GitHub action error: could not read Username

### ISSUE THREAD

**Issue by IratxeGarrido** [securego/gosec#490]
### Summary 
My goal is to create a GitHub actions workflow that runs gosec against one of our repositories. The repository can only be accessed using an ssh key and uses dependencies from other private repositories. I was able to run the tool locally (MacOS) without problems but not as a GitHub action. I have created a secret in the repository with a private key that allows me to access the repository. The webfactory/ssh-agent should allow me to extend this functionality to other repositories but gosec is still not working.
### Steps to reproduce the behavior
This is the go.yml file that is running.
```
name: Run Gosec
on:
  push:
    branches:
      - SPR-8551-gosec-in-github-actions
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
        #with:
        #  repo-token: ${{ SSH_PRIVATE_KEY }}
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.3.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
```
### gosec version
2.263
### Go version (output of 'go version')
go version go1.14.3 darwin/amd64
### Operating system / Environment
The action is running Ubuntu 18.04.4
```
2020-06-17T12:56:42.6972391Z Current runner version: '2.263.0'
2020-06-17T12:56:42.7002024Z ##[group]Operating System
2020-06-17T12:56:42.7003399Z Ubuntu
2020-06-17T12:56:42.7004365Z 18.04.4
2020-06-17T12:56:42.7005357Z LTS
2020-06-17T12:56:42.7006359Z ##[endgroup]
2020-06-17T12:56:42.7007437Z ##[group]Virtual Environment
2020-06-17T12:56:42.7008233Z Environment: ubuntu-18.04
2020-06-17T12:56:42.7009132Z Version: 20200604.1
2020-06-17T12:56:42.7010044Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200604.1/images/linux/Ubuntu1804-README.md
```
### Expected behavior
I want to generate a json file with the tool's output like this one:
```
{
	"Golang errors": {},
	"Issues": [
		{
			"severity": "HIGH",
			"confidence": "HIGH",
			"cwe": {
				"ID": "200",
				"URL": "https://cwe.mitre.org/data/definitions/200.html"
			},
			"rule_id": "G108",
			"details": "Profiling endpoint is automatically exposed on /debug/pprof",
			"file": "----",
			"code": "----",
			"line": "8",
			"column": "2"
		},
...
```
### Actual behavior
```
 Golang errors in file: [.]:
   > [line 0 : column 0] - loading files from package ".": err: exit status 1: stderr: go: github.com/spring-media/la-go-libs@v0.0.0-20180416143156-b67e5d09b543: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/12a3445848fe55462c3531bba68e7d690857223e1092ad0b98a415cea159a669: exit status 128:
2020-06-17T12:57:16.7749630Z 	fatal: could not read Username for 'https://github.com': terminal prompts disabled

 Golang errors in file: [init/cli]:
   > [line 0 : column 0] - loading files from package "init/cli": err: exit status 1: stderr: go: github.com/spring-media/la-go-libs@v0.0.0-20180416143156-b67e5d09b543: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/12a3445848fe55462c3531bba68e7d690857223e1092ad0b98a415cea159a669: exit status 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled


 Golang errors in file: [init/config]:
 
   > [line 0 : column 0] - loading files from package "init/config": err: exit status 1: stderr: go: github.com/spring-media/la-go-libs@v0.0.0-20180416143156-b67e5d09b543: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/12a3445848fe55462c3531bba68e7d690857223e1092ad0b98a415cea159a669: exit status 128:
2020-06-17T12:57:16.7766909Z 	fatal: could not read Username for 'https://github.com': terminal prompts disabled

...
```

**Comment by ccojocar** [comment]
There is a complete example at https://github.com/ccojocar/go-with-github-workflow/blob/master/.github/workflows/ci.yml which might be useful but it doesn't use the ssh key but the token set by the action.

**Comment by ccojocar** [comment]
Does normal `go build` works? I suspect that this issue is related to the GitHub access when the modules are being resolved. Can you perform any other authenticated git actions (e.g. push/pull) outside of gosec but in the action? This is not something specific to gosec but rather Github action or go build related. 

I would try to use something like GOPRIVATE (https://stackoverflow.com/questions/58305567/how-to-set-goprivate-environment-variable) to resolve the private dependencies. 

I am closing this for now since is related to how the git authentication is configured which is not handled by gosec. Also we defer the package loading to Go standard library. This means that if the go build works successfully, gosec is also able to parse and analyse the code.
