### ISSUE TITLE
Add a rule to catch the usage of insecure template.HTML/CSS...

### ISSUE THREAD

**Issue by ccojocar** [securego/gosec#496]
### Summary 

Create a rule to detect the usage of insecure tmplate.HTML, CSS, HTMLAttr, JS, JSStr, Sercset types. They are documented as a security risk. See https://golang.org/pkg/html/template/#HTML.

Also see this discussion https://twitter.com/empijei/status/1275177219011350528

**Comment by sladyn98** [comment]
@ccojocar I could try giving this a shot, any ideas on how I could get started. Thanks :+1:

**Comment by ccojocar** [comment]
There is this basic rule which needs to be improved in order to catch the assignment to all the types mentioned above. https://github.com/securego/gosec/blob/master/rules/templates.go. 

Something like:
```
var myHtml template.HTML := "some text"
```

needs to be flagged as warning.

You can add additional test samples to verify the changes to the rule in https://github.com/securego/gosec/blob/6bcd89aa6b1cc8a448f99d51886ac29703eb1804/testutils/source.go#L1104.

**Comment by empijei** [comment]
To be fair assigning a string literal to template.JS and template.CSS might be acceptable. This is not true for template.HTML and it is definitely not true for any string that is not a literal.

You can read more about this [in a package that implements this pattern](https://github.com/google/safehtml) or in my [more detailed explanation of it](https://blogtitle.github.io/go-safe-html/)
