### ISSUE TITLE
hitting error (invalid package name: "") on repo have multiple go.mod

### ISSUE THREAD

**Issue by WLun001** [securego/gosec#501]
### Summary 
Hitting error `invalid package name: ""` on repo with multiple `go.mod`

### Steps to reproduce the behavior

Repo strucutre
```
.root
  |- cli 
  |   | - cli-name 
  |       |- go.mod
  | - go.mod
```
Run `gosec` on root
```sh
gosec ./...
```

after awhile

```sh
Golang errors in file: [some-path/cmd/generate.go]:

  > [line 21 : column 2] - could not import github.com/spf13/cobra (invalid package name: "")

```

### gosec version
Not sure what is the version, it prints nothing
```sh
gosec -version

Version:
Git tag:
Build date:
```

### Go version (output of 'go version')
```sh
go version go1.14.3 darwin/amd64
```
### Operating system / Environment
MacOS 10.15.4

### Expected behavior
Should able to resolve packages

### Actual behavior
Unable to resolve packages on repo with multiple `go.mod`

**Comment by ccojocar** [comment]
Hi @WLun001, This is not an idiomatic go project layout. You need to have one module per repository. See this docs for more details https://github.com/golang-standards/project-layout. 

Also note that gosec relies on go standard library packages to load the modules.  So if it fails, it means that your project doesn't follow the standards.

I am going to close this because gosec is not going to support this project structure. Thanks!

**Comment by WLun001** [comment]
@ccojocar thanks for the suggestion, I have refactor my project layout and it worked!

**Comment by nitinvalake** [comment]
@ccojocar Facing same issue with private repos.

In my project we have used private repositories and while running gosec command it is giving "unknown revision" error for those private repos.

**Comment by lootek** [comment]
fd

> Hi @WLun001, This is not an idiomatic go project layout. You need to have one module per repository. See this docs for more details https://github.com/golang-standards/project-layout.
> 
> Also note that gosec relies on go standard library packages to load the modules. So if it fails, it means that your project doesn't follow the standards.
> 
> I am going to close this because gosec is not going to support this project structure. Thanks!

The repo you're referring to is NOT an official Go project structure - see https://github.com/golang-standards/project-layout/issues/117

Also, it's perfectly valid to have one git repo with many Go modules - see the OFFICIAL docs https://golang.org/doc/modules/managing-source#tools

**Comment by Emptyless** [comment]
for anyone facing this issue, #1100 fixes the aforementioned issue, the PR is closed but I'll keep the branch open and will try to keep it in sync
