### ISSUE TITLE
set exclude-dir in a config file

### ISSUE THREAD

**Issue by Creator1024** [securego/gosec#505]
### Summary 
How can I set `exclude-dir` in a config file

### Steps to reproduce the behavior
I want to set `exclude-dir` in a config file with a replacement of  `gosec -exclude-dir=/project/cache/.go  ./...`

```
# /tmp/gosec.conf
{
        "exclude-dir": "/project/cache/.go/"
}
```

And then, run with `gosec -conf /tmp/gosec.conf ./...` .
But I don't know how to write this config file correctly.

### gosec version
Version: 2.2.0
Git tag: v2.2.0
Build date: 2020-01-30T09:32:55Z

### Go version (output of 'go version')
go version go1.14.4 linux/amd64

### Operating system / Environment
CentOS7.6

**Comment by desprit** [comment]
It's closed but no examples. Is it an "exclude-dir" option in config? Or maybe "exclude_dir"? A string, an array?
