### ISSUE TITLE
Proposal: Write log to stdout and not stderr

### ISSUE THREAD

**Issue by nbcohen99** [securego/gosec#511]
### Summary 

I understand there is a flag to write the log to a file instead of stderr, but is there a reason why the log is not written to stdout by either a flag or by default? I feel as though messages such as "2020/08/05 15:29:41 Import directory: C:\..." should be written to the stdout instead? 

### gosec version

2.4.0

### Go version (output of 'go version')

go1.14.4 windows/amd64

### Operating system / Environment

Windows 10

### Expected behavior

Log messages get produced to stdout

### Actual behavior

Log messages get produced to stderr

**Comment by ccojocar** [comment]
Yeah, we should write the logs to stdout. This will be fixed. Thanks for reporting this!

**Comment by gcmurphy** [comment]
I touch on this here - https://github.com/securego/gosec/pull/514#issuecomment-675513939

I think this would break some situations where we are piping output to another program and expecting a well structured format.

**Comment by ccojocar** [comment]
Closing this because we want to keep the logging output on stderr for the reason mentioned above. Thanks!
