### ISSUE TITLE
Issue in calling a function from DLL in GO Lang

### ISSUE THREAD

**Issue by Testcase4** [securego/gosec#515]
Problem Description : There is dll( A1.dll- compiled in C++) in which a function is defined as
EXPORT void S3(HWND hwnd, HINSTANCE hinst, LPSTR lpszCmdLine, int nCmdShow){}

A1.dll
`// dllmain.cpp : Defines the entry point for the DLL application.
#include "pch.h"
#include
//#include

#define EXPORT extern "C" __declspec(dllexport)

EXPORT void S3(HWND hwnd, HINSTANCE hinst, LPSTR lpszCmdLine, int nCmdShow)
{
MessageBox(NULL, TEXT("Hello World"),
TEXT("In a DLL"), MB_OK);
}
**I want to load this DLL using GO lang. For this I am writing below program:**package main

import (
"fmt"
"syscall"
"golang.org/x/sys/windows"
)

func main() {
dll, err := syscall.LoadDLL("A1.dll")
proc, err := dll.FindProc("S3")
_, _, dllError := proc.Call()
fmt.Println("calling S3")
fmt.Printf("Error, err: %s\n", dllError)
fmt.Printf("Error, err: %s\n", err)
}`

This is not working. Also I am not able to understand that here how to pass the parameter in call function according to function S3 definition. Could anybody help me in understanding this issue?

**Comment by ccojocar** [comment]
This issue doesn't seem to be related to gosec any ways. Closing it.

**Comment by Testcase4** [comment]
Hi 
Could you please help me in debugging this issue?

Setup : Visual Studio Code ( Windows 10)

Debug Console Output

API server listening at: 127.0.0.1:22699
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xd9c069]

goroutine 1 [running]:
syscall.(*DLL).FindProc(0x0, 0xdf3ff4, 0x6, 0x0, 0x0, 0x0)
C:/Go/bin/src/syscall/dll_windows.go:115 +0x109
main.main()
c:/Users/Dell/Desktop/hello.go:17 +0xf3
