### ISSUE TITLE
gosec docker image not working with imported packages

### ISSUE THREAD

**Issue by DanielVango** [securego/gosec#517]
### Summary 
The gosec docker image appears to be unable to interpret package imports, throwing "could not import [package path] (invalid package name: "")" for most imports.

### Steps to reproduce the behavior
Minimal test file (main.go):
```
package main

import (
	"fmt"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
)

func main() {
	ses := session.Must(
		session.NewSession(&aws.Config{
			Region: aws.String("us-east-1"),
		}),
	)
	fmt.Println(*ses.Config.Region)
}
```

after creating the above test file, run `go mod init` and `go mod vendor`

Then run
`docker run --rm -it -e GO111MODULE=on -v $(pwd):/go/test_dir securego/gosec:v2.4.0 ./test_dir/...`
or
`docker run --rm -it -v $(pwd):/go/test_dir securego/gosec:v2.4.0 ./test_dir/...`
(presence or absence of GO111MODULE has no effect)

You will see errors such as `[line 6 : column 2] - could not import github.com/aws/aws-sdk-go/aws (invalid package name: "")`

Note that running gosec locally with `gosec .` will complete successfully, finding no errors.

### gosec version

2.4.0

### Go version (output of 'go version')
The gosec docker image claims to use go version 1.14.6
https://hub.docker.com/layers/securego/gosec/v2.4.0/images/sha256-5c5117a29dfe066a94281cf09d16e20b003d6c7e8ec256c57c24eaf61d11a513?context=explore

For what it's worth, my docker version is `19.03.13-beta2`

### Operating system / Environment

linux/amd64

### Expected behavior
Gosec successfully reports no errors, as below (output taken from local run of gosec):
```[gosec] 2020/08/24 17:43:45 Including rules: default
[gosec] 2020/08/24 17:43:45 Excluding rules: default
[gosec] 2020/08/24 17:43:45 Import directory: [some path]/gomodtest
[gosec] 2020/08/24 17:43:50 Checking package: main
[gosec] 2020/08/24 17:43:50 Checking file: [some path]/gomodtest/main.go
Results:


Summary:
   Files: 1
   Lines: 17
   Nosec: 0
  Issues: 0
```

### Actual behavior

Gosec reports errors related to file imports:
```
[gosec] 2020/08/24 21:47:27 Including rules: default
[gosec] 2020/08/24 21:47:27 Excluding rules: default
[gosec] 2020/08/24 21:47:27 Import directory: /go/test_dir
[gosec] 2020/08/24 21:47:27 Checking package: main
[gosec] 2020/08/24 21:47:27 Checking file: /go/test_dir/main.go
Results:

Golang errors in file: [/go/test_dir/main.go]:

  > [line 6 : column 2] - could not import github.com/aws/aws-sdk-go/aws (invalid package name: "")

  > [line 7 : column 2] - could not import github.com/aws/aws-sdk-go/aws/session (invalid package name: "")



Summary:
   Files: 1
   Lines: 17
   Nosec: 0
  Issues: 0
```
Note that even though the Issues count is zero, gosec still returns an exit code of 1, indicating failure.

Update, discovered while writing this: if you override the entrypoint to get inside the gosec container (do `docker run --entrypoint sh --rm -it -v $(pwd):/go/test_dir securego/gosec:v2.4.0`, you will find that running `gosec ./test_dir/...` will return the errors above, but `cd`ing into test_dir and running `gosec ./...` there will succeed. This clearly isn't the way the image is intended to be used, however, since the default working directory is `/go`, and putting anything with a `go.mod` directly under /go will throw an error along the lines of "$GOPATH/go.mod should not exist". Also, when run locally, gosec is able to succeed no matter where it is invoked from.

**Comment by ccojocar** [comment]
gosec uses the go build underlying packages, it seems that somehow it doesn't like when the current working directory is not set in the folder where the scan runs. When setting the current working directory with ` -w /go/test_dir/` in the docker run options, the scan seems to be successful:

```
docker run --rm -it -w /go/test_dir/ -v $(pwd):/go/test_dir securego/gosec:v2.4.0 /go/test_dir/...
[gosec] 2020/08/31 08:58:18 Including rules: default
[gosec] 2020/08/31 08:58:18 Excluding rules: default
[gosec] 2020/08/31 08:58:18 Import directory: /go/test_dir
[gosec] 2020/08/31 08:58:27 Checking package: main
[gosec] 2020/08/31 08:58:27 Checking file: /go/test_dir/main.go
Results:


Summary:
   Files: 1
   Lines: 17
   Nosec: 0
  Issues: 0
```

I'll update the README with this information. Thanks for looking into it.

**Comment by DanielVango** [comment]
I did discover this workaround; any clues what the underlying issue might be? If gosec is using the "current working directory" internally for something, instead of the passed path, I can see that potentially breaking all kinds of scripts

**Comment by ccojocar** [comment]
This limitation is not in gosec itself. I think is more how go packages resolves the go modules. As I said above, we use the go build and ast packages.
