### ISSUE TITLE
Could a Release for Go 1.15 be made?

### ISSUE THREAD

**Issue by oliver-hohn** [securego/gosec#534]
### Summary 

Hi there,

We've been planning to update some of our projects to Go 1.15, however we've noticed that there is no release (and Docker image) that includes the changes from: https://github.com/securego/gosec/pull/520. I was wondering whether it would be possible to create a release with those changes?
I'm aware that in the README there are instructions to install the CLI via cURL. However, based on our CI setup, it is preferred for us to use a Docker image instead of manually downloading the CLI in CI.

Thank you very much.

_PS: Apologies if a ticket for this already exists. I could not find it._

**Comment by ccojocar** [comment]
I'll do a release soon. Thanks for raising this issue.

**Comment by ccojocar** [comment]
I am closing this because we will create soon a release.

**Comment by oliver-hohn** [comment]
Apologies for chasing @ccojocar, do you know when a release will be planned? Anything I could help with to get the release out? Thank you.

**Comment by ccojocar** [comment]
I'll try to do one today. Sorry for the delay, I have been off.

**Comment by ccojocar** [comment]
@oliver-hohn `v2.5.0` is released. Thanks for pining!

**Comment by oliver-hohn** [comment]
@ccojocar Thank you for handling the release!
