### ISSUE TITLE
`nosec` doesn't work

### ISSUE THREAD

**Issue by kylidboy** [securego/gosec#535]
### Summary 
"gosec -nosec=true ./..."  does not work,
"gosec -exclude -nosec=true ./..."  works,

### gosec version
Installed by "go get"

### Go version (output of 'go version')
go version go1.15 linux/amd64

### Operating system / Environment
No LSB modules are available.
Distributor ID: Linuxmint
Description:    Linux Mint 20
Release:        20
Codename:       ulyana

### Expected behavior
"gosec -nosec=true ./..."  should work

### Actual behavior
"gosec -nosec=true ./..."  does not work,
"gosec -exclude -nosec=true ./..."  works,

**Comment by ccojocar** [comment]
This looks like a bug to me which need a look.

**Comment by gcmurphy** [comment]
I think I need to clarify the "doesn't work" part. As per the help:

```
  -nosec
    	Ignores #nosec comments when set
```

So if you supply the -nosec flag, or -nosec=true gosec will ignore any `#nosec` annotations and report any errors.
If you supply the arguments in this order: 

`-exclude -nosec` you will see the following log message: 

```
[gosec] 2020/11/02 20:53:49 Excluding rules: -nosec
```
Which means that the `-nosec` flag is being considered as a rule to exclude. This obviously won't exclude any actual rules. I'm not sure if this is a common issue with Go's command line argument parsing or something we've introduced..

@ccojocar thoughts?

**Comment by ccojocar** [comment]
@gcmurphy Thanks for digging into it. I am not sure either 😄. It seems that something is not quite right with the command line arguments parsing.

**Comment by nanikjava** [comment]
@kylidboy do you have sample to reproduce this issue ? want to test it out and see if I can put in a fix.

**Comment by nanikjava** [comment]
@ccojocar what fix need to be put for this ? happy to help out in putting in the fix.

**Comment by ccojocar** [comment]
@nanikjava I would try to have a look at the argument parsing to see what's going on when there are the combinations mentioned above:
- `-exclude -nosec=true` => should return a warning when `exclude` option has no arguments and `nosec` option should be set appropriately
-   `-nosec=true` => should work (nosec flag should be set)

**Comment by nanikjava** [comment]
@ccojocar Looked at the code for `-exclude`. According to the doc https://pkg.go.dev/flag the following is considered as valid

`-exclude=Gxxx`
`-exclude -nosec=true`
`-exclude=`

this means that if a user is passing parameter as `-exclude -nosec=true` the `flag.Parse()` will automatically assign the value `-nosec=true` as the value for `-exclude`

Stepping through the Go `flag` package there seems no way to enforce that the `=` have to be supplied with parameters.

Thoughts ?

**Comment by ccojocar** [comment]
I think that we can implement some custom validation for each flag, or maybe is time to switch over to cobra (https://github.com/spf13/cobra).

**Comment by nanikjava** [comment]
Tried a simple validation for parsing and this works

```
package main

import (
	"errors"
	"flag"
	"fmt"
	"strings"
)

type excludeType string

func (f *excludeType) String() string {
	return fmt.Sprint(*f)
}

func (f *excludeType) Set(value string) error {
	if strings.Contains(value, "-") {
		return errors.New("")
	}
	return nil
}

var excludeFlag excludeType

func main() {
	excludeFlag = "exclude"
	flag.Var(&excludeFlag, "exclude", `Comma separated list of rules IDs to exclude. (see rule list)`)
	flag.Parse()
}
```

WYT ?

**Comment by ccojocar** [comment]
It looks good. I would name it more generically, something like `validatedFlag`,  and I would use it also with the other flags with which this kind of issue can occur. I am looking forward to see a PR. Thanks!
