### ISSUE TITLE
Gosec "Local Installation" section of README.md has wrong/outdated URL

### ISSUE THREAD

**Issue by Miguel-Otero-IBM** [securego/gosec#540]
### Summary

The "Local Installation" section in the README.md file has a URL that is outdated. It contains a reference to a subdirectory (`v2/`) that no longer exists.

### Steps to reproduce the behavior

Execute the "Local installation" step as per the current README.md in master branch:

    go get github.com/securego/gosec/v2/cmd/gosec

### gosec version

master branch 

### Go version (output of 'go version')

go version go1.15.3 linux/amd64

### Operating system / Environment

Docker image golang:latest

### Expected behavior

`gosec` is installed properly

### Actual behavior

The following error appears:

cannot find package "github.com/securego/gosec/v2/cmd/gosec" in any of:
	/usr/local/go/src/github.com/securego/gosec/v2/cmd/gosec (from $GOROOT)
	/go/src/github.com/securego/gosec/v2/cmd/gosec (from $GOPATH)

Removing the `/v2/` part of the URL appears to fix the issue.

**Comment by ccojocar** [comment]
Thanks for raising this issue but this is how Go modules handle major versions. See https://github.com/securego/gosec/blob/208b73eec4ba8bca74b48cdbb38056821ba6300f/go.mod#L1

**Comment by jollyrogue** [comment]
This is still a problem.

I'm pretty sure the v2 folder is supposed to physically exist.

https://blog.golang.org/v2-go-modules

**Comment by jimmynalqa** [comment]
This issue is still not fixed, I'm having the same error message when I'm installing gosec locally in windows 
```
C:\Users\AAAAA>go get -u github.com/securego/gosec/v2/cmd/gosec
package github.com/securego/gosec/v2/cmd/gosec: cannot find package "github.com/securego/gosec/v2/cmd/gosec" in any of:
        c:\go\src\github.com\securego\gosec\v2\cmd\gosec (from $GOROOT)
        C:\Users\AAAAA\go\src\github.com\securego\gosec\v2\cmd\gosec (from $GOPATH)
```
When I try to check, this is the valid path ```C:\Users\AAAA\go\src\github.com\securego\gosec\cmd\gosec``` there is no ```...\v2\...``` folder is exists in my machine
