### ISSUE TITLE
gosec returns "unknown revision" error for private dependencies

### ISSUE THREAD

**Issue by nitinvalake** [securego/gosec#541]
### Summary 
When we run gosec ./... command locally it works fine but when we run same command on remote machine then it gives "UNKNOWN REVISION" error.

### Steps to reproduce the behavior
Create project with external private dependencies. Put code on remote machine and try running gosec ./... command

12:53:46  
12:53:47  2020-11-04 07:23:47,060 [   INFO] [gosec] 2020/11/04 07:23:47 Import directory: /go/src/push_notification_service/services/mocks
12:53:47  
12:53:47  2020-11-04 07:23:47,318 [   INFO] [gosec] 2020/11/04 07:23:47 Import directory: /go/src/push_notification_service/app
12:53:47  
12:53:47  2020-11-04 07:23:47,580 [   INFO] Results:
12:53:47  
12:53:47  Golang errors in file: [app]:
12:53:47  
12:53:47    > [line 0 : column 0] - loading files from package "app": err: exit status 1: stderr: go: github.com/abc/catalyst_sdk@v1.0.12: reading github.com/abc/catalyst_sdk/go.mod at revision v1.0.12: unknown revision v1.0.12
12:53:47  
12:53:47  
12:53:47  
12:53:47  Golang errors in file: [cmd]:
12:53:47  
12:53:47    > [line 0 : column 0] - loading files from package "cmd": err: exit status 1: stderr: go: github.com/abc/catalyst_sdk@v1.0.12: reading github.com/abc/catalyst_sdk/go.mod at revision v1.0.12: unknown revision v1.0.12

### gosec version
2.5.0

### Go version (output of 'go version')
go version go1.14.1 linux/amd64

### Operating system / Environment
linux/amd64

### Expected behavior
It should run properly without any errors

### Actual behavior
Not working with private dependencies.

**Comment by ccojocar** [comment]
@nitinvalake Do you have the go modules set up in that projects? I would run `go mod init` and also try a `go build` before running the gosec tool.

**Comment by nitinvalake** [comment]
@ccojocar Yes go modules is setup in project. Will try running go build before running gosec.

Thank You :) for your reply.

**Comment by nitinvalake** [comment]
@ccojocar Tried running `gosec` after `go build` but getting same error.

**Comment by ccojocar** [comment]
@ccojocar Does `go build` work properly? Can you also maybe try to run once `go mod download` to check if all the modules of the project are properly downloaded? Can you update the go version to 1.15.x (this shouldn't be a requirement)?

**Comment by nitinvalake** [comment]
@ccojocar We are using vendor with go module to maintain dependencies. So our build command is like this `go build -mod vendor`.

Can we run gosec with vendor?

**Comment by ccojocar** [comment]
Thanks for clarifications! This might be the issue. `gosec` doesn't pass that argument down into the `build flags`. It used to work with the vendor folder but before go modules introduction.

**Comment by nitinvalake** [comment]
> Thanks for clarifications! This might be the issue. `gosec` doesn't pass that argument down into the `build flags`. It used to work with the vendor folder but before go modules introduction.

If this is the cases, I have to download all the modules there right?

**Comment by ccojocar** [comment]
Yeah, I think that the workaround to get it working. 

I would close this pull request since the vendoring approach is not that common anymore with the go modules.
