### ISSUE TITLE
Hope the community will provide a sample solution for gosec Rules

### ISSUE THREAD

**Issue by LinshanYu** [securego/gosec#543]
### Summary 
The gosec rules official website（https://securego.io/docs/rules/rule-intro.html) provides too few examples, and most of them do not provide relevant solutions
### Steps to reproduce the behavior
The following gosec rules does not provide a solution:
       G110: Potential DoS vulnerability via decompression bomb
       G204: Subprocess launched with variable
       G402: TLS InsecureSkipVerify set true.
### gosec version
latest
### Go version (output of 'go version')
go1.12.7 amd64
### Operating system / Environment
amd64 Ubuntu
### Expected behavior
Hope to provide a corresponding solution for every gosec rules

**Comment by ccojocar** [comment]
Hi @LinshanYu, Thank for reporting this but is a duplicate of #127.
