### ISSUE TITLE
Some sample code does not compile

### ISSUE THREAD

**Issue by cbandy** [securego/gosec#549]
### Summary 

The documentation on `github.com/securego/gosec/v2/testutils.CodeSample` says
> CodeSample encapsulates a snippet of source code that compiles, and how many errors should be detected

However, not all the code in these samples compiles. I think I see a test that is _supposed_ to verify this, so my concern is that tests are incorrect.

https://github.com/securego/gosec/blob/9fe0b2e21afb166f331098c282aa5de6c96d3253/rules/rules_test.go#L35-L41

### Steps to reproduce the behavior

1. Copy the first value of `SampleCodeG601` and paste it in Go playground: https://play.golang.org/p/MfxutjCC9YO
2. Press "Run" to find that it does not compile.

### gosec version

v2.5.0 and HEAD.

### Expected behavior

I expected the sample to run (and show what G601 protects against).

### Actual behavior

> Go build failed.

```
./prog.go:15:13: cannot use &item (type **string) as type *string in return argument
./prog.go:15:13: cannot use item (type *string) as type string in return argument
./prog.go:17:1: missing return at end of function
./prog.go:24:31: undefined: c_start
```

**Comment by ccojocar** [comment]
Thanks for reporting this. Please could you send a pull request which fixes the test samples which doesn't compile and it suppose to? I'll be happy to merge it in.

**Comment by ccojocar** [comment]
Fixed by https://github.com/securego/gosec/pull/554
