### ISSUE TITLE
G402 (CWE-295) rule does not support multiple packages

### ISSUE THREAD

**Issue by AlexanderYastrebov** [securego/gosec#551]
### Summary 

G402 rule stores TLS `actualMinVersion` in `insecureConfigTLS` which persists across multiple package scans:
https://github.com/securego/gosec/blob/9fe0b2e21afb166f331098c282aa5de6c96d3253/rules/tls.go#L87-L96

Therefore result of `checkVersion` depends on package order and may or may not lead to the `NewIssue`:
https://github.com/securego/gosec/blob/9fe0b2e21afb166f331098c282aa5de6c96d3253/rules/tls.go#L135-L147

`gosec` with `./...` argument scans packages in undefined order:
https://github.com/securego/gosec/blob/9fe0b2e21afb166f331098c282aa5de6c96d3253/helpers.go#L397-L413

which leads to flaky results.

The problem apparently was introduced by #493

### Steps to reproduce the behavior

```
$ gosec -version
Version: 2.5.0
Git tag: v2.5.0
Build date: 2020-10-26T11:52:22Z
$ tree
.
├── p0
│   └── p0.go
└── p1
    └── p1.go

2 directories, 2 files
$ cat p0/p0.go
```
```go
package p0

import "crypto/tls"

var v uint16 = 0
var c = &tls.Config{MinVersion: v}
```
```
$ cat p1/p1.go
```
```go
package p1

import "crypto/tls"

var c = &tls.Config{MinVersion: 0x0304}
```
```
$ gosec ./p0 ./p1 
[gosec] 2020/12/21 22:42:13 Including rules: default
[gosec] 2020/12/21 22:42:13 Excluding rules: default
[gosec] 2020/12/21 22:42:13 Import directory: /tmp/gh-551/p0
[gosec] 2020/12/21 22:42:13 Checking package: p0
[gosec] 2020/12/21 22:42:13 Checking file: /tmp/gh-551/p0/p0.go
[gosec] 2020/12/21 22:42:13 Import directory: /tmp/gh-551/p1
[gosec] 2020/12/21 22:42:14 Checking package: p1
[gosec] 2020/12/21 22:42:14 Checking file: /tmp/gh-551/p1/p1.go
Results:


[/tmp/gh-551/p0/p0.go:6] - G402 (CWE-295): TLS MinVersion too low. (Confidence: HIGH, Severity: HIGH)
    5: var v uint16 = 0
  > 6: var c = &tls.Config{MinVersion: v}



Summary:
   Files: 2
   Lines: 11
   Nosec: 0
  Issues: 1

$ gosec ./p1 ./p0 
[gosec] 2020/12/21 22:42:19 Including rules: default
[gosec] 2020/12/21 22:42:19 Excluding rules: default
[gosec] 2020/12/21 22:42:19 Import directory: /tmp/gh-551/p1
[gosec] 2020/12/21 22:42:19 Checking package: p1
[gosec] 2020/12/21 22:42:19 Checking file: /tmp/gh-551/p1/p1.go
[gosec] 2020/12/21 22:42:19 Import directory: /tmp/gh-551/p0
[gosec] 2020/12/21 22:42:19 Checking package: p0
[gosec] 2020/12/21 22:42:19 Checking file: /tmp/gh-551/p0/p0.go
Results:


Summary:
   Files: 2
   Lines: 11
   Nosec: 0
  Issues: 0

```

`p0.go` uses variable to set `MinVersion`, `p1.go` uses valid `MinVersion` constant. 
If `p0` package is scanned before `p1` version check fails.
If `p1` is scanned before `p0` it sets `actualMinVersion` to valid version and `p0` version check passes. 

The problem seems to be related to #528 

### gosec version

v2.5.0

### Expected behavior

`gosec` reliably detects TLS issues regardless of package order

### Actual behavior

Depending on package order TLS issues may be undetected

**Comment by AlexanderYastrebov** [comment]
A test case to reproduce
```diff
diff --git testutils/source.go testutils/source.go
index 2686840..c556981 100644
--- testutils/source.go
+++ testutils/source.go
@@ -1999,6 +1999,16 @@ func main() {
                fmt.Println(err)
        }
 }`}, 1, gosec.NewConfig()}, {[]string{`
+package main
+
+import "crypto/tls"
+
+var d = &tls.Config{MinVersion: 0x0304}
+
+var v uint16 = 0
+var c = &tls.Config{MinVersion: v}
+
+`}, 1, gosec.NewConfig()}, {[]string{`
 // Insecure max version
 package main
 import (
```

**Comment by ccojocar** [comment]
This look like a bug. The rule seems to maintain the previous state between the package analysis. We need to reset this state.
