### ISSUE TITLE
Could you clarify affiliation with Facebook Open Source?

### ISSUE THREAD

**Issue by nikolaydubina** [securego/gosec#560]
On your website here it says it is from Facebook Open Source: https://securego.io/
<img width="981" alt="image" src="https://user-images.githubusercontent.com/2933061/105452481-5df56300-5cb9-11eb-83fa-cdacda4dff68.png">

But official Facebook GitHub org does not show this project.
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/2933061/105452569-7f564f00-5cb9-11eb-816b-3d5b9b26fe4c.png">

**Comment by ccojocar** [comment]
Hi @nikolaydubina, There is not affiliation with Facebook Open Source, I think that the website template might have been taken from there.

**Comment by nikolaydubina** [comment]
Thank you for clarification!
