### ISSUE TITLE
Do we have some gosec file examples?

### ISSUE THREAD

**Issue by eddynaka** [securego/gosec#567]
Hi,

we are creating a converter in https://github.com/microsoft/sarif-sdk to generate a sarif file from a gosec file.

I searched but I couldn't find examples to test.

Can you generate a few, pls?

Thank you!

cc: @yongyan-gh

**Comment by ccojocar** [comment]
Hi @eddynaka, gosec outputs the results in multiple file formats including `sarif`. It doesn't require any conversion, just select the appropriate formatter. Please have a look at this GitHub action which runs gosec with the sarif output formatter: https://github.com/securego/gosec#integrating-with-code-scanning.
