### ISSUE TITLE
Why G404 on this code?

### ISSUE THREAD

**Issue by frederikhors** [securego/gosec#568]
### Summary 
I have this code in my hobby project:

```go
import (
	"math/rand"
	"time"
)

func getRandomBool() bool {
  return rand.Int31()&(1<<30) == 0
}

func getRandomInt(min, max int) int {
  return rand.Intn(max-min+1) + min
}

func getRandomDate(min, max int64) time.Time {
  delta := max - min

  sec := rand.Int63n(delta) + min

  return time.Unix(sec, 0)
}
```

Why is [gosec](https://github.com/securego/gosec) complaining about each line with `rand...`?

`G404: Use of weak random number generator (math/rand instead of crypto/rand) (gosec)`

I think it thinks this code is for generating something super secret: which is not!

Am I wrong?

### gosec version
Latest golangci-lint 1.36.0

### Go version (output of 'go version')
go version go1.15.7 windows/amd64

**Comment by ccojocar** [comment]
gosec warns you that the code does not use `crypto/rand` which is the secure way to generate random numbers. Maybe in this case is not required but the tool is not able to comprehend the context of your code if is security sensitive or not.

You can ignore this warning if you want to still use the `math/rand` with `#nosec` directive.
