### ISSUE TITLE
Detect directory traversal http.Dir("/")

### ISSUE THREAD

**Issue by kaihendry** [securego/gosec#569]
### Summary 

By following an example like https://golang.org/pkg/net/http/#NewFileTransport and allowing a user to traverse the file system from "/", it could be quite a security issue. For e.g. /proc/*/environ could be downloaded

### Steps to reproduce the behavior

https://github.com/kaihendry/badpath

### gosec version

Version: 2.6.1
Git tag: v2.6.1
Build date: 2021-01-22T10:39:07Z

### Go version (output of 'go version')

go version go1.15.8 linux/amd64

### Operating system / Environment

I use Arch btw

### Expected behavior

Maybe a warning?

### Actual behavior

No issue

**Comment by irateswami** [comment]
> I use Arch btw
:sunglasses:

**Comment by irateswami** [comment]
Would a warning suffice for using `http.Dir` to mount root be enough? Seems fairly simple.
