### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by felipe-avelar** [securego/gosec#578]
### Summary 
The github action for gosec uses the latest docker image published on docker hub, since there was a problem with sarif in the image published, gosec still throws an error when using GH actions.

### Steps to reproduce the behavior
1. Use gosec's github action in any repository

### Expected behavior
Gosec should runs and list errors after sarif being uploaded

### Actual behavior
GH actions fails returning a  invalid sarif file message

**Comment by ccojocar** [comment]
We will release a new version as soon as the support for go 1.16 is ready.

**Comment by ccojocar** [comment]
Fixed by https://github.com/securego/gosec/releases/tag/v2.7.0
