### ISSUE TITLE
gosec giving “could not import C (no metadata for C)” golang error

### ISSUE THREAD

**Issue by rakeshkumarofcl** [securego/gosec#589]
### Summary
I am working on a Golang project which uses CGO. 
Running gosec on that project gives following error due to which our pipeline is failing

```
Golang errors in file: [/home/usr/example/project.go]:

[line 22 : column 8] - could not import C (no metadata for C)
```

While go build command successfully builds the project means there is no golang error.

### gosec version
Version: 2.4.0
Git tag: v2.4.0
Build date: 2020-07-24T07:54:54Z

### Go version (output of 'go version')
go version go1.13.6 linux/amd64
Same behavior observed on go1.14 linux/amd64

### Operating system / Environment
Observed same behavior on CentOS7 and Golang:1.14-stretch (Docker image)

### Expected behavior
gosec should not give golang error because `go build` command is successfully building the project means there is no golang issue.

### Actual behavior
gosec ./.. fails with following error 
```
Golang errors in file: [/home/usr/example/project.go]:

[line 22 : column 8] - could not import C (no metadata for C)
```

**Comment by rakeshkumarofcl** [comment]
This is not an issue.
We found out that our C code is present in `.c` and `.h` files in package directory, where .h file containing only function prototypes. And we are including only .h file in go files (cgo). 
`go build` and `go test` commands are working because both of these commands when see `.c` and `.h` in package directory, compiles and link them.
But gosec is a SAST tool, it doesn't compile code. So `gosec` scan was getting only function prototypes not definition due to which it was throwing golang error `could not import C (no metadata for C)`.
Including the whole code in comments (CGO) worked. Now gosec works fine.

**Comment by docktermj** [comment]
@rakeshkumarofcl When you say:
> Including the whole code in comments (CGO) worked.
What was it that you actually did?   i.e. what is "whole code"?

**Comment by rakeshkumarofcl** [comment]
@docktermj to resolve the issue we also included '.c' files in cgo while running gosec. 
So here, by whole code means while running gosec we included all the .c and .h files (using #include) in cgo part of go package.

**Comment by docktermj** [comment]
@rakeshkumarofcl Thank you for the follow-up.   We now have a working system.   In our GitHub Action, we copy all of the `*.h` files from their original locations into the directories having our go and CGO code.

Here's what it looks like:

https://github.com/Senzing/g2-sdk-go-base/blob/8bde5e564ab9b78f3bc894b455bdddf8288399c9/.github/workflows/go-test.yaml#L48-L56

Keep up the good work!
