### ISSUE TITLE
G101: false negatives

### ISSUE THREAD

**Issue by dmorawetz** [securego/gosec#597]
### Summary 
I just came across gosec and I wanted to test it. So I just created a simple test file (see below) and was surprised that no issues were reported. Variable names "token", "secret", "pwd" worked, but I would expect the list to be more complete. I also would expect it to find passwords generated by `openssl rand -base64 32`.

```go
package main

import "log"

func main() {
	pw := "ErcYFlt6UzHWr281heQFUZlvH5/vLXnLU/rL2sLdBqOHQUltj/WXmgTiEOBB37G0NIw037Ts75Z6kCgKGDyCFA=="
	hex := "ff2317d70699f808e5fd7ac9a798789c15efb5db5ea8fb654826085303a8e8f399d3bab30ce453c50b36b7a61c5678b59dd6e1d393b4e869707d35c4cdb40487"
	const cred = "kjasflkjweroi908234"
	apiKey := "eroiuweroisdfpoiwer"
	bearer := "Bearer: 2lkjdfoiuwer092834kjdwf09"
	log.Println(pw)
	log.Println(apiKey)
	log.Println(bearer)
	log.Println(hex)
	log.Println(cred)
}

```
### Steps to reproduce the behavior
- Copy code above in test.go in a folder test
  - without the folder gosec complained about `> [line 0 : column 0] - importing dir "test.go": cannot find package "." in:
        test.go` which is also weird since `go run` works
- Run `gosec test`

### gosec version
2.7.0

### Go version (output of 'go version')
go version go1.16.3 linux/amd64

### Operating system / Environment
5.4.112-1-MANJARO #1 SMP PREEMPT Wed Apr 14 07:47:45 UTC 2021 x86_64 GNU/Linux

### Expected behavior
Report hard-coded credentials

### Actual behavior
Does not report any issues

**Comment by ccojocar** [comment]
The secrets rule use some entropy based detection which is not perfect. It covers right now only a reduced set of keywords in order to reduce the amount of false positives. Any improvements are welcome!

**Comment by nanikjava** [comment]
@ccojocar How does this look ?

```
[gosec] 2021/07/18 17:46:18 Including rules: default
[gosec] 2021/07/18 17:46:18 Excluding rules: default
[gosec] 2021/07/18 17:46:18 Import directory: /home/temp/packages/src/github.com/nanikjava/src/gosec
[gosec] 2021/07/18 17:46:19 Checking package: main
[gosec] 2021/07/18 17:46:19 Checking file: /home/temp/packages/src/github.com/nanikjava/src/gosec/main.go
Results:


[/home/xxx/src/gosec/main.go:10] - G101 (CWE-798): Potential hardcoded credentials (Confidence: LOW, Severity: HIGH)
    9:  apiKey := "eroiuweroisdfpoiwer"
  > 10:         bearer := "Bearer: 2lkjdfoiuwer092834kjdwf09"
    11:         log.Println(pw)



[/home/xxx/src/gosec/main.go:9] - G101 (CWE-798): Potential hardcoded credentials (Confidence: LOW, Severity: HIGH)
    8:  const cred = "kjasflkjweroi908234"
  > 9:  apiKey := "eroiuweroisdfpoiwer"
    10:         bearer := "Bearer: 2lkjdfoiuwer092834kjdwf09"



[/home/xxx/src/gosec/main.go:8] - G101 (CWE-798): Potential hardcoded credentials (Confidence: LOW, Severity: HIGH)
    7:  hex := "ff2317d70699f808e5fd7ac9a798789c15efb5db5ea8fb654826085303a8e8f399d3bab30ce453c50b36b7a61c5678b59dd6e1d393b4e869707d35c4cdb40487"
  > 8:  const cred = "kjasflkjweroi908234"
    9:  apiKey := "eroiuweroisdfpoiwer"



[/home/xxx/src/gosec/main.go:6] - G101 (CWE-798): Potential hardcoded credentials (Confidence: LOW, Severity: HIGH)
    5: func main() {
  > 6:  pw := "ErcYFlt6UzHWr281heQFUZlvH5/vLXnLU/rL2sLdBqOHQUltj/WXmgTiEOBB37G0NIw037Ts75Z6kCgKGDyCFA=="
    7:  hex := "ff2317d70699f808e5fd7ac9a798789c15efb5db5ea8fb654826085303a8e8f399d3bab30ce453c50b36b7a61c5678b59dd6e1d393b4e869707d35c4cdb40487"



Summary:
  Gosec  : dev
  Files  : 1
  Lines  : 16
  Nosec  : 0
  Issues : 4

```

Happy to open a PR for this if this is what we are after ?

**Comment by dmorawetz** [comment]
@nanikjava awesome! that's what I would expect 🙂

**Comment by nanikjava** [comment]
@ccojocar PR ready for review. Let me know if I need to add more test or changes as it's my first time so possibly I missed something :).

Thanks

**Comment by ccojocar** [comment]
Fixed by https://github.com/securego/gosec/pull/666
