### ISSUE TITLE
Use multiple output formats

### ISSUE THREAD

**Issue by ShreyasSubhedar** [securego/gosec#598]
### Summary 

I want multiple output formats to be generated  + stdout format while running the gosec.
### Steps to reproduce the behavior

`GO111MODULE=on ./bin/gosec -fmt=text -out=text.txt -fmt=json -out=result.json ./...`
### gosec version
latest
### Go version (output of 'go version')
v1.16
### Expected behavior
All provided formats need to be generated with stdout
### Actual behavior
Only last `-out` is been generated

**Comment by mmorel-35** [comment]
What's wrong with looping on the tool call, in pseudo-code :
```bash
runs = [{"fmt" :"text", "out" :"file.txt" }, {"fmt" :"json", "out" :"file.json" } ] 
for run in runs 
   GO111MODULE=on ./bin/gosec -fmt=run.fmt -out=run.out
   cat run.out 
endfor
```

**Comment by ShreyasSubhedar** [comment]
I agree, but in my opinion, running the analysis twice just to generate multiple file format isn’t the best approach! Where
we can always save the output in different format!

And also running it multiple times creates multiple `[gosec]`  logs

```
[gosec] 2021/05/08 20:44:07 Checking package: yaml < 1st time
[gosec] 2021/05/08 20:44:07 Checking file: /Users/shreyas.subhedar/Documents/GitHub/gosec/report/yaml/writer.go
[gosec] 2021/05/08 20:44:07 Import directory: /Users/shreyas.subhedar/Documents/GitHub/gosec
[gosec] 2021/05/08 20:44:07 Checking package: gosec
[gosec] 2021/05/08 20:44:07 Checking package: yaml < 2nd time
[gosec] 2021/05/08 20:44:07 Checking file: /Users/shreyas.subhedar/Documents/GitHub/gosec/report/yaml/writer.go
[gosec] 2021/05/08 20:44:07 Import directory: /Users/shreyas.subhedar/Documents/GitHub/gosec
[gosec] 2021/05/08 20:44:07 Checking package: gosec
```

**Comment by mmorel-35** [comment]
If you allow multiple kind of output then you may have to change the command parameters to look like `-json=file.json -sarif=report.sarif...`

Having multiple logs for the same analysis seems too much indeed. But another idea would be to implement a command convert from json to any other format.
So there would be only one analysis which would output a json file and then a call to the convert command for every other format you might need.

**Comment by ShreyasSubhedar** [comment]
Ill try my best to achieve it!

**Comment by mmorel-35** [comment]
What do you think about using [cobra](https://github.com/spf13/cobra) to handle commands and flags?

**Comment by ShreyasSubhedar** [comment]
Yeah its awesome !

**Comment by ccojocar** [comment]
It would make sense to converted to cobra, but I would create another issue for this work.

**Comment by ArnPellesGit** [comment]
@ccojocar I could attempt to fix this if this is still an issue?

**Comment by ccojocar** [comment]
Closing this since it can be handled with a script, and is not cleared what is the value of supporting this feature in gosec. Thanks
