### ISSUE TITLE
As a gosec user, I want my output is saved in a file as well as stdout.

### ISSUE THREAD

**Issue by ShreyasSubhedar** [securego/gosec#600]
For a CICD pipeline when pipeline is failing because of gosec results, I am getting either stdout or formatted file output. I am not able to see both set both the output formats at the same time.

By enabling the stdout while using any formatted output user can check the logs to quickly find out what is wrong and file output can be saved as an artifact.

I may going to file a PR  for this.

**Comment by ccojocar** [comment]
Thanks for this issue! I am happy to accept your pull request.

**Comment by ShreyasSubhedar** [comment]
The PR associated to the issue:- 
https://github.com/securego/gosec/pull/611
