### ISSUE TITLE
Add Support for Apple M1 CPU in install.sh

### ISSUE THREAD

**Issue by andercs** [securego/gosec#617]
### Summary 

At the moment, the `install.sh` script complains when attempting to install in a Docker container on a new Macbook Pro with the M1 chip instead of the classic Intel chip. (It may also complain when running the `install.sh` natively on the Macbook, not sure haven't tried.)

### Steps to reproduce the behavior

1. Create a Dockerfile in the Golang project with the following lines
```
FROM golang:1.16

RUN curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b "$(go env GOPATH)/bin" v2.7.0
```
3. Run `docker build -t go-m1-support-error .`

### gosec version

2.7.0

### Go version (output of 'go version')

`go version go1.16.4 darwin/arm64`

### Operating system / Environment

MacBook Pro (13-inch, M1, 2020)
Apple M1 CPU (Darwin/ARM64)

### Expected behavior

It installs `gosec` as expected.

### Actual behavior

It fails with the error:
```
securego/gosec crit platform linux/arm64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/securego/gosec/issues/new
```

**Comment by andrewmarklloyd** [comment]
I am still experiencing the same behavior as @andercs using the same Macbook Pro model and steps to reproduce.
