### ISSUE TITLE
Error: Invalid SARIF. Missing 'results' array in run.

### ISSUE THREAD

**Issue by wolfeidau** [securego/gosec#649]
### Summary 

I have been using the `securego/gosec` GitHub action for a few months now without issue then on the 2021/05/30 it started failing.

See https://github.com/wolfeidau/hotwire-golang-website/runs/2702656984?check_suite_focus=true

### Steps to reproduce the behavior

https://github.com/wolfeidau/hotwire-golang-website/blob/master/.github/workflows/scan.yml

### gosec version

`securego/gosec@master`

**Comment by ccojocar** [comment]
Fixed by https://github.com/securego/gosec/pull/650
