### ISSUE TITLE
Proposal: Closing files

### ISSUE THREAD

**Issue by elgohr** [securego/gosec#657]
Based on https://www.joeshaw.org/dont-defer-close-on-writable-files/ , I would like to add a new rule.
Would this be welcome as a PR or is behaviour like this out of scope?

**Comment by ccojocar** [comment]
Hi @elgohr , There is already a rule which catches this issue: https://github.com/securego/gosec/blob/master/rules/bad_defer.go. Did you have a look at it? I think was based on the blog post mentioned above. Thanks

**Comment by elgohr** [comment]
Maybe I should write another test for this role then. This rule will also be ok, when the error from close is handled in the defer function (even if the file is not synced with the filesystem).

**Comment by ccojocar** [comment]
It would be great if you could write another test. I will be happy to merge it. Thanks!
