### ISSUE TITLE
Proposal: New branch to enable FIPS 140-2 spec in weak crypto

### ISSUE THREAD

**Issue by push7joshi** [securego/gosec#662]
Would adding the list of disallowed ciphers as a new branch be helpful?
It seems many enterprise users will be able to run static scans to start off their efforts in FIPS compliance goals.

**Comment by ccojocar** [comment]
I am happy to accept a pull request for this. There are a few weak cyphers marked here 	https://github.com/securego/gosec/blob/514f65f3c301d526f253f195b89bccbbc8548b2c/rules/weakcrypto.go#L44. I would create another rule for FIPS with the full list of compliant cyphers and disallow all other cyphers.

**Comment by push7joshi** [comment]
Yup, this would just be additions to those ciphers. I will try to get a pr going, thanks!

**Comment by ccojocar** [comment]
@push7joshi Are you still interested to contribute this or should we close it? Thanks

**Comment by ccojocar** [comment]
Closing this issue since the request seems to be old and no interest around it. Thanks
