### ISSUE TITLE
Docker `latest` tag has broken build in `-version`

### ISSUE THREAD

**Issue by shakefu** [securego/gosec#664]
### Summary 

![image](https://user-images.githubusercontent.com/1046227/125560397-ef51b92f-598d-4f4c-86a4-bc6d17312a5f.png)

### Steps to reproduce the behavior

Pull the latest tag (sha `429f812ce352`) and run it with -version

### gosec version

Unknown - that's the issue.

### Operating system / Environment

Container

### Expected behavior

It should print version info.

### Actual behavior

It thinks it's a `dev` build.

**Comment by shakefu** [comment]
Also true for tagged versions: 

![Uploading image.png…]()

**Comment by shakefu** [comment]
Also true for recent tagged version:
![image](https://user-images.githubusercontent.com/1046227/125560582-514e7b23-c1ec-46c0-b4af-1e2e8f32d90b.png)

**Comment by ccojocar** [comment]
This looks like a bug. The version should be injected into the binary.

**Comment by ccojocar** [comment]
Fixed by https://github.com/securego/gosec/pull/672
