### ISSUE TITLE
Add possibility to list waived (nosec) marked issues but not count them as such (feature request)

### ISSUE THREAD

**Issue by bakito** [securego/gosec#675]
### Summary 

Our Security regulations demand evidence reports that our source code follows secure coding guidelines. 
We are using gosec for this purpose. 
The regulations demand, that waived issues are also listed. Hence it would be great, if gosec optionally could generate reports, where waived issues are reported, but not counted as such and marked as waived.

### Steps to reproduce the behavior

Run gosec with any report

### gosec version

any

### Go version (output of 'go version')

any

### Operating system / Environment
any

### Expected behavior

Waived issue are not visible in the report.

### Actual behavior

Waived issue are visible in the report but not counted as such.

**Comment by ccojocar** [comment]
It think this is useful feature. Do you want to contribute this enhancement? Thanks

**Comment by bakito** [comment]
I was trying to implement it, but didn't find a way to get it working.
That's why I created the Feature Request and not a PR.

**Comment by bakito** [comment]
What I currently have is here: https://github.com/securego/gosec/compare/master...bakito:show-nosec?expand=1

**Comment by ccojocar** [comment]
It looks good on a first look. Which test scenarios you cannot cover?

**Comment by bakito** [comment]
I can not get a valid test, where nisec issues are shown, but not counted as issue

**Comment by ccojocar** [comment]
I would open a pull request, and let's see how we can find a solution to cover this test scenario.
