### ISSUE TITLE
invalid package name: "" when adding v2 project

### ISSUE THREAD

**Issue by c-mcallister** [securego/gosec#682]
### Summary 
`gosec ./...` on the root this simple project errors with:
```
[gosec] 2021/08/12 12:18:06 Including rules: default
[gosec] 2021/08/12 12:18:06 Excluding rules: default
[gosec] 2021/08/12 12:18:06 Import directory: /Users/cam/gosecIssue/v2
[gosec] 2021/08/12 12:18:06 Checking package: gosecissue
[gosec] 2021/08/12 12:18:06 Checking file: /Users/cam/gosecIssue/v2/version2.go
[gosec] 2021/08/12 12:18:06 Import directory: /Users/cam/gosecIssue
[gosec] 2021/08/12 12:18:06 Checking package: gosecissue
[gosec] 2021/08/12 12:18:06 Checking file: /Users/cam/gosecIssue/version1.go
Results:

Golang errors in file: [/Users/cam/gosecIssue/v2/version2.go]:

  > [line 6 : column 2] - could not import github.com/gin-gonic/gin (invalid package name: "")
```

this is kinda related to #501  but IS idiomatic go as per: https://blog.golang.org/v2-go-modules#TOC_2.

### Steps to reproduce the behavior
**Note:** My example is checked in here: https://github.com/c-mcallister/gosecIssue
  

create a simple go project
create a `v2` folder with a new version of the project in the root as per https://blog.golang.org/v2-go-modules#TOC_2.
make sure that the go in the v2 folder imports something
run `gosec ./...` from the root project

```
.
├── go.mod
├── v2
│   ├── go.mod
│   ├── go.sum
│   └── version2.go
└── version1.go
```

### gosec version
```
$ gosec --version
Version: 2.5.0
Git tag: v2.5.0
Build date: 2020-10-26T11:52:22Z
```
### Go version (output of 'go version')
```
$ go version
go version go1.16 darwin/amd64
```

### Operating system / Environment
`macos big sur v 11.4`

### Expected behavior
gosec analyses the original version and the v2 folder correctly

### Actual behavior
gosec errors on the imports from the v2 folder

**Comment by c-mcallister** [comment]
we can manually work around this with 
gosec -exclude-dir v2 ./...

**Comment by ccojocar** [comment]
@c-mcallister It seems that you have two go modules in one git repository which is not a standard practice. This doesn't follow the standard layout for major versions update. See for more details the project layout recommended on https://golang.org/doc/modules/major-version. 

I am closing this for now since gosec uses the standard go build for parsing the AST and expects only one go module per project. It is possible to scan the folders separately as you suggested above.

**Comment by c-mcallister** [comment]
@ccojocar please can you re-open this ticket?  While there is a workaround, it's not practical for automated tooling to accommodate this bug in this way.

The godocs for https://golang.org/doc/modules/major-version are only relevant when we are able to entirely stop developing on one version, and replace it with another major version.

This is usually impractical for library projects and instead, the go recommended way to support multiple versions of a repo at the same time (and built into the tooling) is as described here:  https://blog.golang.org/v2-go-modules#TOC_2
there is a new version in a `/v2` folder which is entirely independent to the root (including with it's own`go.mod` files)

**Comment by c-mcallister** [comment]
There is more detail on this v2 pattern here: https://donatstudios.com/Go-v2-Modules which does go into the fact that this approach has not been very widely broadcast, and the behaviour of tools like gosec will further encourage teams to get this wrong.

**Comment by izhakjakov** [comment]
We are experiencing a similar problem with `github.com/go-redis/redis/v8`
```
Results:

Golang errors in file: [/updateGoMod/common/redis.go]:

 > [line 11 : column 2] - "github.com/go-redis/redis/v8" imported but not used

 > [line 11 : column 2] - could not import github.com/go-redis/redis/v8 (invalid package name: "")
```
