### ISSUE TITLE
G204 with concatenated string warns about "function call"

### ISSUE THREAD

**Issue by scop** [securego/gosec#684]
### Summary 

G204 says "Subprocess launched with **function call** as ..." for a string concatenation (no function call).

### Steps to reproduce the behavior

```go
func reproducer(s string) {
	exec.Command("foo-" + s)
}
```

### gosec version

Current git

### Go version (output of 'go version')

go version go1.17 linux/amd64

### Expected behavior

Would be better to use the "...with variable" message for this I think.

### Actual behavior

```
G204 (CWE-78): Subprocess launched with function call as argument or cmd arguments (Confidence: HIGH, Severity: MEDIUM)
```

**Comment by ccojocar** [comment]
@nanikjava Please could you have a look at this issue? it seems to be related to the recent changes you have done to rule G204. Thanks

**Comment by nanikjava** [comment]
@scop 
The new G204 rule that currently in place considered that as an issue, to short circuit can use the following:

```
package main

import "os/exec"

func x(s string) {
	reproducer("foo-" + s)
}

func reproducer(s string) {
	exec.Command(s)
}
```


Following is the link to the test cases for G204 https://github.com/securego/gosec/blob/master/testutils/source.go#L1297, this will show the different code styles

**Comment by ccojocar** [comment]
@scop I think also from security perspective this looks like a potential issue since the string held by the `s` variable can be potentially injected into the command execution.  For instance if that value is provided by an input controlled by an attacker. 

`gosec` is not able to analyse the full call graph in order to identify if this value is a taint input or not but it returns a warning. This looks as a valid warning which can be ignored when the `s` value is sanitised.

**Comment by scop** [comment]
I agree it's a potential security issue, that's not what this report was about.

This report is about the error message saying _function call_ when there is no function call involved but just a string concatenation.

If gosec is unable to distinguish between various ways tainted input could end up in the command or args, I think it should use a more generic language like "Subprocess launched with possibly tainted input as argument or cmd arguments" instead.

**Comment by ccojocar** [comment]
@scop Thanks for clarifications. I changed the message to be more generic as you suggested above. See https://github.com/securego/gosec/pull/688

**Comment by scop** [comment]
Nice, thanks!
