### ISSUE TITLE
No result after I run gosec , and it is very slow

### ISSUE THREAD

**Issue by luckybool1020** [securego/gosec#696]
### Summary 
the output log only have "Import directory",don't have "checking file", and it's very slow
<img width="870" alt="Screen Shot 2021-09-07 at 5 53 03 PM" src="https://user-images.githubusercontent.com/16422202/132325384-03920585-77cb-40c2-8555-8005e114ed48.png">

### gosec version
dev
### Go version (output of 'go version')
1.14.5
### Operating system / Environment
mac 10.15.1

**Comment by ccojocar** [comment]
@luckybool1020 We phased out the support for Go 1.14. See the supported version here https://github.com/securego/gosec/blob/bfb0f422fe759a58c8bdd48b0c6d89e03387a36f/.github/workflows/ci.yml#L23. 
Please could you try with 1.15+ and let me know how it works. 

Thanks
