### ISSUE TITLE
Ignore Function/Method

### ISSUE THREAD

**Issue by strongishllama** [securego/gosec#697]
### Summary
If this is already a feature my apologies, I couldn't find it anywhere in the documentation.

It would be great if there was the ability to ignore a function/method. The example I had in mind was ```foo.Bar()``` could return an error but it's not checked and you don't want to add ```/* #nosec */``` above it every time it's called.

If this would be a useful feature I'd be happy to implement it, although I'm not familiar with the codebase.

**Comment by ccojocar** [comment]
This is feature is not available but I am happy to accept a pull request for it. How do you plan to mark a function/method which should be ignore? Do you think should be ignored only by specific rules or by all rules? Thanks

**Comment by strongishllama** [comment]
@ccojocar My bad, looks like this is already possible with the following? Thanks anyway!

```
# Run with a global configuration file
$ gosec -conf config.json .
```
```
{
    "G104": {
        "foo": ["Bar"]
    }
}
```
