### ISSUE TITLE
Exclude rules in config file

### ISSUE THREAD

**Issue by baruchiro** [securego/gosec#704]
### Summary 

How can I set the exclude/include in the `config.json`?

### Steps to reproduce the behavior

I created a file `gosec.config.json` with:

```json
{
    "exclude": "G104"
}
```

I'm running `gosec -conf gosec.config.json ./...`, but the error `G104` still exists.

### gosec version

```
Version: dev
Git tag: 
Build date:
```

### Go version (output of 'go version')

`go version go1.17.1 linux/amd64`

### Operating system / Environment

Inside a VSCode dev-caontainer:

```bash
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

### Expected behavior

All the available configs should be able to configure from CLI and from the config file.

### Actual behavior

The `gosec` not accept the `exclude` config from the config file.

Related: #505

**Comment by ragumix** [comment]
Yes, it's an interesting question, I faced with it too. Please help.
