### ISSUE TITLE
`-exclude-generated` option not working or visible in `-h`

### ISSUE THREAD

**Issue by nobishino** [securego/gosec#709]
### Summary 

`-exclude-generated` option is [documented in README.md](https://github.com/securego/gosec#excluding-generated-files), but `gosec -exclude-generated .` does not show analysis results and exits with 2.

Also, `gosec -h` does not print `-exclude-generated` option.

### Steps to reproduce the behavior

- ` go install github.com/securego/gosec/v2/cmd/gosec@v2.8.1` (reproduces at latest too)
- `gosec -exclude-generated .`
- `echo $?` -> 2

### gosec version

- `v2.8.1`
- Reproduces at latest https://github.com/securego/gosec/commit/17105ab93ed478496256efc460950f2dce4e9bac too.

### Go version (output of 'go version')

go version
go version go1.17.1 darwin/amd64

### Operating system / Environment

- macOS Big Sur version 11.6
- output of `go env`(folded):

<details>

```
go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/main/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/main/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

</details>

### Expected behavior

- `gosec -exclude-generated .` prints analysis results.
- `gosec -h` prints `-exclude-generated` option.

### Actual behavior

- `gosec -exclude-generated .` does not print analysis results and exits with 2.
- Instead, `gosec exclude-generated`(without leading `-`) runs properly and prints analysis results.
- `gosec -h` does not print `-exclude-generated` option.

**Comment by parasense** [comment]
Ping @ccojocar 
Sorry for the necro-post, but any chance to maybe branch master to bump the current version with documented `-exclude-generated` ?
