### ISSUE TITLE
G307: gosec starts detecting G307 (CWE-703) even with proposed way to safely handle errors

### ISSUE THREAD

**Issue by achiku** [securego/gosec#714]
### Summary 

gosec v2.9.1 starts detecting `G307 (CWE-703): Deferring unsafe method "Close" on type "*os.File" (Confidence: HIGH, Severity: MEDIUM)` which could have been avoided by following https://github.com/securego/gosec/issues/512 with previous version of gosec.

### Steps to reproduce the behavior

```golang
package main

import (
        "log"
        "os"
)

func main() {
        f, err := os.Open("./testfile.txt")
        if err != nil {
                log.Fatal(err)
                return
        }
        defer func() {
                if err := f.Close(); err != nil {
                        log.Fatal("failed to close file")
                }
        }()
        log.Println("success")
        return
}
```

```
(~/work/achiku/gosec-issue)
❯❯❯ ll
total 8
-rw-r--r--  1 chiku  staff  268 10 18 11:32 main.go
-rw-r--r--  1 chiku  staff    0 10 18 11:31 testfile.txt
(~/work/achiku/gosec-issue)
❯❯❯ go run main.go
2021/10/18 11:32:22 success
(~/work/achiku/gosec-issue)
❯❯❯ gosec .
[gosec] 2021/10/18 11:32:27 Including rules: default
[gosec] 2021/10/18 11:32:27 Excluding rules: default
[gosec] 2021/10/18 11:32:27 Import directory: /Users/chiku/work/achiku/gosec-issue
[gosec] 2021/10/18 11:32:28 Checking package: main
[gosec] 2021/10/18 11:32:28 Checking file: /Users/chiku/work/achiku/gosec-issue/main.go
Results:


[/Users/chiku/work/achiku/gosec-issue/main.go:14-18] - G307 (CWE-703): Deferring unsafe method "Close" on type "*os.File" (Confidence: HIGH, Severity: MEDIUM)
    13:         }
  > 14:         defer func() {
  > 15:                 if err := f.Close(); err != nil {
  > 16:                         log.Fatal("failed to close file")
  > 17:                 }
  > 18:         }()
    19:         log.Println("success")



Summary:
  Gosec  : 2.9.1
  Files  : 1
  Lines  : 21
  Nosec  : 0
  Issues : 1

```

with v2.8.1

```
(~/work/achiku/gosec-issue)
❯❯❯ curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $GOPATH/bin v2.8.1
securego/gosec info checking GitHub for tag 'v2.8.1'
securego/gosec info found version: 2.8.1 for v2.8.1/darwin/amd64
securego/gosec info installed /Users/chiku/sdk/go1.16.7/bin/gosec
(~/work/achiku/gosec-issue)
❯❯❯ gosec .
[gosec] 2021/10/18 11:32:43 Including rules: default
[gosec] 2021/10/18 11:32:43 Excluding rules: default
[gosec] 2021/10/18 11:32:43 Import directory: /Users/chiku/work/achiku/gosec-issue
[gosec] 2021/10/18 11:32:44 Checking package: main
[gosec] 2021/10/18 11:32:44 Checking file: /Users/chiku/work/achiku/gosec-issue/main.go
Results:


Summary:
  Gosec  : 2.8.1
  Files  : 1
  Lines  : 21
  Nosec  : 0
  Issues : 0
```

### gosec version

- v2.9.1
- https://github.com/securego/gosec/releases/tag/v2.9.1

### Go version (output of 'go version')

```
❯❯❯ go version
go version go1.16.7 darwin/amd64
```

### Operating system / Environment

```
❯❯❯ uname -a
Darwin FVFZR19DLYWP 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
```

### Expected behavior

No errors, or solve this error.

### Actual behavior

gosec detects G307 (CWE-703).

**Comment by jsirianni** [comment]
I am seeing this as well. I would expect a defer func() to pass gosec without issue, because I am checking the error. This was working before, not sure what version. 

```
G307 (CWE-703): Deferring unsafe method "Close" on type "*os.File" (Confidence: HIGH, Severity: MEDIUM)
    191: 			}
  > 192: 			defer func() {
  > 193: 				if err := f.Close(); err != nil {
  > 194: 					logger.Errorw("Failed to close file", zap.Error(err))
  > 195: 				}
  > 196: 			}()

```

**Comment by Aisuko** [comment]
We hit the same issue, we use the Github Action with the `@master` version. And I belive we can ignore this check first by add `/* #nosec G307 */` (only in the situation below, you already check the error return by file close function)


```
// Github Action version of Gosec
 - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./... -exclude=G301,G304,G107,G101,G110
```

The error

```
[/github/workspace/linkerd/install.go:274-278] - G307 (CWE-703): Deferring unsafe method "Close" on type "*os.File" (Confidence: HIGH, Severity: MEDIUM)
42
    273: 	}
43
  > 274: 	defer func() {
44
  > 275: 		if err := out.Close(); err != nil {
45
  > 276: 			fmt.Println(err)
46
  > 277: 		}
47
  > 278: 	}()
48
    279: 
49

```

**Comment by lootek** [comment]
This is not necessarily a _false_ positive: https://www.joeshaw.org/dont-defer-close-on-writable-files/

**Comment by xxgreg** [comment]
The double defer pattern is mentioned in the update at the end of the post.
That's actually the article I learnt about the pattern from.

It is safe when close is idempotent. When code has multiple returns it is
easy to miss adding a close.

 Also if you've already found an error, then call close, and get another
error, what should you do? Return both errors? Most code I've seen ignores
the close error in this scenario, and returns the first error.

**Comment by lootek** [comment]
Well, but calling just `defer f.Close()` where you don't even log the possible error (neither skip it explicitly with `_ = f.Close()` is IMO not a good practice as you'll never know if sth went wrong or not.

In that article, it's stated it's unclear/not stated in docs whether you actually should safely close the resource multiple times (and even if it's working now, I wouldn't rely on that).

> Also if you've already found an error, then call close, and get another
error, what should you do? Return both errors? Most code I've seen ignores
the close error in this scenario, and returns the first error.

I'd either combine/wrap them both or return only the first one but log any other at the same time.

Anyway, I'd say this is not so good for the gosec to be that radical as people are now massively skipping the checks with `/* #nosec */` (not even specifying the check number as I took a brief look at the linked PRs) and that's for sure not what should happen. 
I strongly vote for reverting the changeset to make it work the way it did before - claiming about deferred actions with no error checks/skipped error checks and the simple error handling (like eg. logging) being enough to "fix"/shut up the validation rule.

**Comment by xxgreg** [comment]
@lootek It is stated in the docs. In fact the docs were specifically updated because of this pattern. See: https://github.com/golang/go/issues/32427

```
// Close closes the File, rendering it unusable for I/O.
// On files that support SetDeadline, any pending I/O operations will
// be canceled and return immediately with an error.
// Close will return an error if it has already been called.
func (f *File) Close() error {
```

**Comment by lootek** [comment]
thanks @xxgreg , didn't notice that! Then the double-close pattern is even worse ;)

**Comment by danieljmt** [comment]
@ccojocar @elgohr do you have any updated guidance on this?

**Comment by elgohr** [comment]
I guess I already mentioned this https://github.com/securego/gosec/pull/661#issuecomment-889913968

**Comment by danieljmt** [comment]
So essentially we always have to deal with a false positive, even when we're just reading a file or have handled syncing the file as suggested?

**Comment by elgohr** [comment]
My intention was to discuss this in the PR, before it got merged to avoid this false positive... Now it's merged - I have no idea

**Comment by elgohr** [comment]
To my point of view a solution would be to revert the change and start again with the initial PR (including the failing false-positive-test)

**Comment by danieljmt** [comment]
Yeah that sounds like it'd be reasonable to me! 😄

**Comment by ccojocar** [comment]
> To my point of view a solution would be to revert the change and start again with the initial PR (including the failing false-positive-test)

@elgohr Please feel free to revert the pull request and to provide an updated solution. Thanks

**Comment by elgohr** [comment]
@ccojocar please see https://github.com/securego/gosec/pull/733
Do you want to reopen the old PR?

**Comment by ccojocar** [comment]
@elgohr I merged your pull request. 

> Do you want to reopen the old PR?

You can reopen it if you want to rework it.

**Comment by danieljmt** [comment]
@ccojocar Please could we get a new release now the PR has been reverted?

**Comment by ccojocar** [comment]
@danieljmt new version released https://github.com/securego/gosec/releases/tag/v2.9.3
