### ISSUE TITLE
Add suppression information in the output of GoSec

### ISSUE THREAD

**Issue by Yiwei-Ding** [securego/gosec#723]
### Summary 

Violations can be suppressed by inline comments and external configurations in GoSec. We propose to add a `-track-suppressions=true` CLI option for adding suppression information, including its kind and justification, in the output of GoSec.

The code below shows the example in the format of SARIF:

```json
"results": [
  {
    "level": "error",
    "locations": [
      {
        "physicalLocation": {
          "artifactLocation": {
            "uri": "D:\\gotest\\hello.go"
          },
          "region": {
            "endColumn": 2,
            "endLine": 7,
            "snippet": {
              "text": "6: \tusername := \"admin\"\n7: \tpassword := \"f62e5bcda4fae4f82370da0c6f20697b8f8447ef\"\n8: \tfmt.Println(\"Doing something with: \", username, password)\n"
            },
            "sourceLanguage": "go",
            "startColumn": 2,
            "startLine": 7
          }
        }
      }
    ],
    "message": {
      "text": "Potential hardcoded credentials"
    },
    "ruleId": "G101",
    "suppressions": [
      {
        "kind": "inSource",
        "justification": "Sample justification message."
      }
    ],
  }
]
```

### Motivation

GoSec is to inspect source code for security problems by scanning the Go AST. When codes violate one or more defined rules, GoSec will report errors.

In our scenarios, when violations are suppressed, Security Development Lifecycle (SDL) tools, such as GoSec, are expected to export suppression information, including its kind and justification. We could take advantage of this info to generate corresponding signals for auditing purposes.

### Proposed Solution

1. Keep the current behavior of GoSec, i.e., issues will not be shown on the command line if the related rules are suppressed, unless `-nosec=true` is used.
2. When the new CLI option `-trakc-suppressions=true` is used, the violations (or issues in GoSec) that suppressed by inline directive comments will not be ignored, and the rules that suppressed externally will run to generate issues (but will not report errors in CLI).
3. Add suppression info in the output of GoSec
    1. For inline suppressions, we generate suppression info where `kind` is `inSource` and `justification` is the text after two or more consecutive dashes in the directive comments.
    For example:
        ```golang
        /* #nosec G101 -- Justification example */
        password := "f62e5bcda4fae4f82370da0c6f20697b8f8447ef"
        ```
        ```go
        password := "f62e5bcda4fae4f82370da0c6f20697b8f8447ef" // #nosec -- Justification example
        ```
        Output:
        ```json
        {"kind": "inSource", "justification": "Justification example"}
        ```
    2. For external suppressions, we generate suppression info where `kind` is `external` and `justification` is a certain sentence such as “Globally suppressed”.
    For example:
        ```
        gosec -exclude=G101 -track-suppressions=true ./..
        ```
        Output:
        ```json
        {"kind": "external", "justification": "Globally suppressed"}
        ```

We are very glad to contribute to GoSec. Let me know if you have any ideas.

**Comment by ccojocar** [comment]
@Yiwei-Ding Thanks for raising this issue. The proposal looks good. I am looking forward to review your pull request for this issue.
