### ISSUE TITLE
simplified Docker run command in README.md

### ISSUE THREAD

**Issue by cgijb** [securego/gosec#729]
### Summary 

When running in a Go module directory, there's an easy way to get gosec kicked off. For those not Linux savvy, it may be useful to add:

```
docker run --rm -it -w /$(basename $(pwd)) -v $(pwd):/$(basename $(pwd)) securego/gosec ./...
```

### Steps to reproduce the behavior

1. Create a basic project with your usually `mkdir whatever && cd whatever && go mod init whatever`
2. Add some code and some tests in the project
3. Verify everything is working as expected with a basic `go test -cover ./...`
4. Run the Docker command `docker run --rm -it -w /$(basename $(pwd)) -v $(pwd):/$(basename $(pwd)) securego/gosec ./...`

### gosec version

Worked with **v2.9.2**

### Go version (output of 'go version')

Checked with code written running with **go version go1.16.2 linux/amd64**

### Operating system / Environment

Linux/Docker

### Expected behavior

N/A

### Actual behavior

N/A

**Comment by ccojocar** [comment]
@cgijb Thanks for providing this command. It is already documented in the README. Check out the https://github.com/securego/gosec#docker-image. 

I think your command makes the assumption that the `docker run` is executed in the project folder which is not always the case.

**Comment by ccojocar** [comment]
@cgijb Please feel free to raise a pull request if additional clarifications are required in the README. I am going to close this issue for now. Thank you!
