### ISSUE TITLE
Issues scanning private GitHub repos added as dependencies for another project

### ISSUE THREAD

**Issue by Ravikanth143143** [securego/gosec#732]
### Summary 
I am using gosec v2.9.2 in github workflow. 

I have a project X that has all the commons code and project Y that includes the dependencies of X. Without the dependencies `gosec ./...` in Y seems to run fine with no issues. However, when the dependencies are added it seems to break the security scanning. Below is the error:

> [gosec] 2021/11/23 04:58:25 Import directory: /github/workspace/logger
> [gosec] 2021/11/23 04:58:26 Checking package: logger
> [gosec] 2021/11/23 04:58:26 Checking file: /github/workspace/logger/logger.go
> 
> Results:
> Golang errors in file: [/github/workspace/logger/logger.go]:

  > [line 5 : column 2] - could not import github.com/MyRepo/common-golang-lib/config (invalid package name: "")

I also set:
`GO111MODULE: on`

### Steps to reproduce the behavior
Create a private github repo and reference it in your current project on which you need to run gosec

### gosec version
v2.9.2

### Go version (output of 'go version')
1.17

### Operating system / Environment
ubuntu using github workflow

### Expected behavior
There should be a way to scan the private github repos

### Actual behavior
private github repos doesn't get scanned.

**Comment by ccojocar** [comment]
@Ravikanth143143 Can you build successfully the project with `go build` when you include the dependencies? It seems that the go module dependencies cannot be solved. You can also try to run `go mod download` before running the gosec scan.

**Comment by ccojocar** [comment]
I am closing this issue since it seems to me that is related to the go dependencies and not gosec tool. Note that gosec relies on go build infrastructure to resolve the go module dependencies.
