### ISSUE TITLE
Path installation is incorrect for v2

### ISSUE THREAD

**Issue by jimmynalqa** [securego/gosec#749]
### Summary 
Cannot find gosec v2 package after installation from $GOROOT and $GOPATH

### Steps to reproduce the behavior
run install command ```go get -u github.com/securego/gosec/v2/cmd/gosec``` 

### gosec version
```v2```

### Go version (output of 'go version')
```go version go1.14.7 windows/amd64```

### Operating system / Environment
```Windows```

### Expected behavior
Should be no issue after installation

### Actual behavior
Got this error message after installing gosec with ```go get -u github.com/securego/gosec/v2/cmd/gosec``` :
```
Package github.com/securego/gosec/v2/cmd/gosec: cannot find package "github.com/securego/gosec/v2/cmd/gosec" in any of:
        c:\go\src\github.com\securego\gosec\v2\cmd\gosec (from $GOROOT)
        C:\Users\AABBCCDD\go\src\github.com\securego\gosec\v2\cmd\gosec (from $GOPATH)
```

**Comment by jimmynalqa** [comment]
my ```go env```:
```
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\AABBCCDD\AppData\Local\go-build
set GOENV=C:\Users\AABBCCDD\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\AABBCCDD\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\AABBC~1\AppData\Local\Temp\go-build652181450=/tmp/go-build -gno-record-gcc-switches
```

**Comment by jimmynalqa** [comment]
Also I found out this path is exists in my machine after installation ```C:\Users\AABBCCDD\go\src\github.com\securego\gosec\cmd\gosec```. Noticed that there is no ```..\v2\..``` in the path.

**Comment by ccojocar** [comment]
@jimmynalqa Thanks for raising this issue but we don't support anymore go version 1.14. These are the supported versions https://github.com/securego/gosec/blob/72f1145f8a102ab0663b8844efc74794c21932d7/.github/workflows/ci.yml#L23. Please could you try with 1.17 version. Thanks
