### ISSUE TITLE
As a DevOps, I want to have a robust CI pipeline to test all the features of gosec on every commit to master.

### ISSUE THREAD

**Issue by ShreyasSubhedar** [securego/gosec#750]
### Summary 
Currently we have test cases that runs on the codebase, but it'll be really awesome to have a complete CI pipeline that tests all the features of gosec ex. Test the gosec flags by scanning an image and assert with the expected values 
possible CI tools:- 
- Github Actions
- Travis
- Circle

**Comment by ccojocar** [comment]
@ShreyasSubhedar Thanks for raising this issue but gosec has already a CI pipeline. Please have a look at https://github.com/securego/gosec/tree/master/.github/workflows
