### ISSUE TITLE
Question: Shouldn't check for potential file inclusion via variable for os.Create?

### ISSUE THREAD

**Issue by vaiojarsad** [securego/gosec#760]
I got complaints about the potential unsafe use of os.Open and ioutil.ReadFile and I was wondering why I didn't get any about os.Create.

The program that I was working on was a really trivial tool, only for internal use (so, no real risk) but in all cases (os.Open, ioutil.ReadFile and os.Create) the provided variable to these functions could have been manipulated by a malicious user.

**Comment by ungerik** [comment]
Is this complaint coming from `gosec`? If you create a function that opens a file and gets the filepath passed as an argument, then this warning has to be disabled in the function because how else are you supposed to provide a lib opens an unknown file.

**Comment by ungerik** [comment]
Using `filepath.Clean(filePath)` might solve the problem.

**Comment by ccojocar** [comment]
This function call seems to be missing form the list. I added it. Thanks for pointing this out.

**Comment by vaiojarsad** [comment]
Anytime, my pleasure!
