### ISSUE TITLE
Sarif Snippet contains line number prefixes + additional parts instead only relevant

### ISSUE THREAD

**Issue by de-jcup** [securego/gosec#773]
### Steps to reproduce the behavior
Scan some go code with e.g. a CWE 79 - cross site scripting

The `SARIF` output generated by `gosec` does contain a snippet text, but the text does not contain line number prefixes. Also additional source code lines are added as well and not only the relevant part.

Example output:
```json
"region" : {
            "endColumn" : 14,
            "endLine" : 69,
            "snippet" : {
              "text" : "68: \t\t}\n69: \t\tvar data = template.HTML(v.TmplFile)\n70: \t\tisTmpl := true\n"
            },
            "sourceLanguage" : "go",
            "startColumn" : 14,
            "startLine" : 69
          }
```
So snippet is here : `"68: \t\t}\n69: \t\tvar data = template.HTML(v.TmplFile)\n70: \t\tisTmpl := true\n"`

Reading https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10541136

> NOTE: The snippet property has various uses:
> ·         It allows a SARIF viewer to present the contents of the region even if the artifact from which it was taken is not available.
> ·         It also allows an end user examining a SARIF log file to see the relevant content without opening another file.
> ·         It can be used to improve result matching.
> 

I would have expected : `\t\tvar data = template.HTML(v.TmplFile)` or `var data = template.HTML(v.TmplFile)`

At https://github.com/mercedes-benz/sechub we use also the (truncated) snippet to identify the relevant part for false-positive handling, so it is very important for us to have only the relevant part here.

#### Full example sarif output from gosec:

```json
{
  "runs" : [ {
    "results" : [ {
      "level" : "error",
      "locations" : [ {
        "physicalLocation" : {
          "artifactLocation" : {
            "uri" : "go-test-bench/pkg/servestd/servestd.go"
          },
          "region" : {
            "endColumn" : 14,
            "endLine" : 69,
            "snippet" : {
              "text" : "68: \t\t}\n69: \t\tvar data = template.HTML(v.TmplFile)\n70: \t\tisTmpl := true\n"
            },
            "sourceLanguage" : "go",
            "startColumn" : 14,
            "startLine" : 69
          }
        }
      } ],
      "message" : {
        "text" : "this method will not auto-escape HTML. Verify data is well formed."
      },
      "ruleId" : "G203"
    } ],
    "taxonomies" : [ {
      "downloadUri" : "https://cwe.mitre.org/data/xml/cwec_v4.4.xml.zip",
      "guid" : "f2856fc0-85b7-373f-83e7-6f8582243547",
      "informationUri" : "https://cwe.mitre.org/data/published/cwe_v4.4.pdf/",
      "isComprehensive" : true,
      "language" : "en",
      "minimumRequiredLocalizedDataSemanticVersion" : "4.4",
      "name" : "CWE",
      "organization" : "MITRE",
      "releaseDateUtc" : "2021-03-15",
      "shortDescription" : {
        "text" : "The MITRE Common Weakness Enumeration"
      },
      "taxa" : [ {
        "fullDescription" : {
          "text" : "The software does not neutralize or incorrectly neutralizes user-controllable input before it is placed in output that is used as a web page that is served to other users."
        },
        "guid" : "25e839d4-f25e-382a-9390-cf419bcd5969",
        "helpUri" : "https://cwe.mitre.org/data/definitions/79.html",
        "id" : "79",
        "shortDescription" : {
          "text" : "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
        }
      } ],
      "version" : "4.4"
    } ],
    "tool" : {
      "driver" : {
        "guid" : "8b518d5f-906d-39f9-894b-d327b1a421c5",
        "informationUri" : "https://github.com/securego/gosec/",
        "name" : "gosec",
        "rules" : [ {
          "defaultConfiguration" : {
            "level" : "warning"
          },
          "fullDescription" : {
            "text" : "Errors unhandled."
          },
          "help" : {
            "text" : "Errors unhandled.\nSeverity: LOW\nConfidence: HIGH\n"
          },
          "id" : "G104",
          "name" : "Errors unhandled.",
          "properties" : {
            "precision" : "high",
            "tags" : [ "security", "LOW" ]
          },
          "relationships" : [ {
            "kinds" : [ "superset" ],
            "target" : {
              "guid" : "7df38d1d-038e-3ced-8601-8d9265b90a25",
              "id" : "703",
              "toolComponent" : {
                "guid" : "f2856fc0-85b7-373f-83e7-6f8582243547",
                "name" : "CWE"
              }
            }
          } ],
          "shortDescription" : {
            "text" : "Errors unhandled."
          }
        }, {
          "defaultConfiguration" : {
            "level" : "error"
          },
          "fullDescription" : {
            "text" : "this method will not auto-escape HTML. Verify data is well formed."
          },
          "help" : {
            "text" : "this method will not auto-escape HTML. Verify data is well formed.\nSeverity: MEDIUM\nConfidence: LOW\n"
          },
          "id" : "G203",
          "name" : "this method will not auto-escape HTML. Verify data is well formed.",
          "properties" : {
            "precision" : "low",
            "tags" : [ "security", "MEDIUM" ]
          },
          "relationships" : [ {
            "kinds" : [ "superset" ],
            "target" : {
              "guid" : "25e839d4-f25e-382a-9390-cf419bcd5969",
              "id" : "79",
              "toolComponent" : {
                "guid" : "f2856fc0-85b7-373f-83e7-6f8582243547",
                "name" : "CWE"
              }
            }
          } ],
          "shortDescription" : {
            "text" : "this method will not auto-escape HTML. Verify data is well formed."
          }
        } ],
        "semanticVersion" : "2.9.5",
        "supportedTaxonomies" : [ {
          "guid" : "f2856fc0-85b7-373f-83e7-6f8582243547",
          "name" : "CWE"
        } ],
        "version" : "2.9.5"
      }
    }
  } ],
  "$schema" : "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "version" : "2.1.0"
}
```

### gosec version
2.9.5

### Go version (output of 'go version')
go 1.17.5 linux/amd64

### Operating system / Environment
Linux Ubuntu

### Expected behavior
snippet text attribute shall contain either  `\t\tvar data = template.HTML(v.TmplFile)` or (without whitespaces more readable IMHO:) `var data = template.HTML(v.TmplFile)` 

### Actual behavior
snippet text attribute contains line numbers and additional source parts : `"68: \t\t}\n69: \t\tvar data = template.HTML(v.TmplFile)\n70: \t\tisTmpl := true\n"`

**Comment by ccojocar** [comment]
This behaviour is expected. The gosec tries here to collect more context around the warning. See https://github.com/securego/gosec/blob/853e1d5034b80fa728026db1ff50456acc748a32/issue.go#L186.  This behaviour is present in all types of reports because sometime is useful to look at this context in order to understand the issue.

I think the exact line can be extracted from the text snippet with a bit of post-processing since all lines are prefixed with a line number.

**Comment by Jeeppler** [comment]
The line number in the `code` is redundant, as the `Issue` has already line and column number attributes. The line number can cause a number of issues while using the report further. Additionally, it requires one to parse the resulting code snippet all the time for any post processing. In my opinion, there are to many concerns mixed together.

Furthermore, the SARIF standard introduced a `region` and `contextRegion` object: https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10541121. The region contains only information about the exact finding location. The contextRegion, as the name suggest, contains additional information around the context of the finding. From my perspective, the separation is a smart move as it helps to decouple different concerns.

**Comment by ccojocar** [comment]
It makes sense. This feature was developed before SARIF support and is independent from the output format. We can anyhow improve what is outputted in the SARIF report to not include the entire snippet and just the line with the error. Also we can add `region` and `contextRegion` support as a separat feature.

**Comment by Jeeppler** [comment]
> We can anyhow improve what is outputted in the SARIF report to not include the entire snippet and just the line with the error. Also we can add `region` and `contextRegion` support as a separat feature.

Agreed, that would be a good solution.

**Comment by de-jcup** [comment]
@ccojocar : Thank you very much for the very fast response and the implementation!
