### ISSUE TITLE
Build tags not respected across packages

### ISSUE THREAD

**Issue by ninja18** [securego/gosec#782]
### Summary 
In a code with multiple packages, definitions with build tags in one package are not picked up in other packages where the code is referenced while using gosec with build tags. But `go build` is able to compile successfully.
### Steps to reproduce the behavior
In a project with two packages `config` and `echo` where a member of `config` in `<release/debug>-consts.go` is used in `echo`. The package and directory structure looks like this
```
├── config
│   ├── debug-const.go
│   └── release-const.go
├── echo
│   └── echo.go
├── go.mod
├── go.sum
├── main.go

2 directories, 7 files
```
running `gosec -tags release ./...` throws error mentioned in the below section.

*Note:* When the files with build tags are defined and used in the same package, gosec is able to respect the build tags and pick up the right file.
### gosec version
```
Version: dev
Git tag:
Build date:
```
### Go version (output of 'go version')
go1.16 darwin/amd64

### Operating system / Environment
OS X Big Sur

### Expected behavior
Should pick up definitions based on build tags from other packages.

### Actual behavior
```
[gosec] 2022/02/23 16:21:23 Including rules: default
[gosec] 2022/02/23 16:21:23 Excluding rules: default
[gosec] 2022/02/23 16:21:23 Import directory: /Users/user/go/src/tmptest/echo
[gosec] 2022/02/23 16:21:24 Checking package: echo
[gosec] 2022/02/23 16:21:24 Checking file: /Users/user/go/src/tmptest/echo/echo.go
[gosec] 2022/02/23 16:21:24 Import directory: /Users/user/go/src/tmptest
[gosec] 2022/02/23 16:21:25 Checking package: main
[gosec] 2022/02/23 16:21:25 Checking file: /Users/user/go/src/tmptest/main.go
[gosec] 2022/02/23 16:21:25 Import directory: /Users/user/go/src/tmptest/config
Results:

Golang errors in file: [/Users/user/go/src/tmptest/echo/echo.go]:

  > [line 5 : column 5] - could not import tmptest/config (invalid package name: "")


Golang errors in file: [/Users/user/go/src/tmptest/main.go]:

  > [line 4 : column 5] - could not import tmptest/config (invalid package name: "")
```

**Comment by ccojocar** [comment]
Gosec analysis package by package. Anyhow this is not supported by the underlying parsing infrastructure provided by the Go standard library. This is used by gosec. I am going to close this issue since is out of scope for now. Thanks
