### ISSUE TITLE
G404: math/rand backed by crypto/rand

### ISSUE THREAD

**Issue by fugkco** [securego/gosec#783]
### Summary 

According to [this SO](https://stackoverflow.com/a/35208651/670388) it is possible to have `math/rand` backed by `crypto/rand`. I'm not sure how safe this is, but if it is safe, is it possible to add an exception for such an implementation?

### Steps to reproduce the behavior
https://go.dev/play/p/qDB3zY-Jval

### gosec version
Not sure, I'm using it via golang-ci lint version `1.44.0`.

### Go version (output of 'go version')
```
$ go version
go version go1.17.3 linux/amd64
```

### Expected behavior
Not error with G404

### Actual behavior
Errors with G404

**Comment by fugkco** [comment]
Oh, I just tested with the latest version (`v2.10.0`) of gosec

```
Results:


[../rand.go:22] - G404 (CWE-338): Use of weak random number generator (math/rand instead of crypto/rand) (Confidence: MEDIUM, Sever
ity: HIGH)
    21:
  > 22:         r := rand.New(CryptoRandSource{})
    23:         for i := 0; i < minimumLength; i++ {



Summary:
  Gosec  : 2.10.0
  Files  : 4
  Lines  : 281
  Nosec  : 0
  Issues : 1
```

**Comment by ccojocar** [comment]
I am not sure if now `math.Rand` is backed by the crypto rand, but historically this was considered insecure. You can ignore the warning at your own risk. I am closing this issue since is out of scope for an implementation in gosec. Thanks
