### ISSUE TITLE
Add a rule for Slowloris Attack 

### ISSUE THREAD

**Issue by ccojocar** [securego/gosec#807]
### Summary 

Add rule which should detect if `ReadHeaderTimeout` is configured in the `http.Server`.  This should prevent a Slowloris Attack. See more details at https://medium.com/a-journey-with-go/go-understand-and-mitigate-slowloris-attack-711c1b1403f6.

**Comment by adamdecaf** [comment]
Wouldn't this check be more correct to alert when ReadTimeout == 0 and ReadHeaderTimeout == 0? 

```go
	// (snip) If ReadHeaderTimeout
	// is zero, the value of ReadTimeout is used. If both are
	// zero, there is no timeout.
	ReadHeaderTimeout [time](https://pkg.go.dev/time).[Duration](https://pkg.go.dev/time#Duration)
```

https://pkg.go.dev/net/http#Server.ReadHeaderTimeout
