### ISSUE TITLE
G203 this method will not auto-escape HTML. Verify data is well formed.

### ISSUE THREAD

**Issue by kaihendry** [securego/gosec#813]
### Summary 

I believe this is a false positive saying that HTML won't be autoescaped in my JS embed https://github.com/kaihendry/ltabus/blob/master/static/main.js

https://github.com/kaihendry/ltabus/runs/6347544889?check_suite_focus=true

Do I need to just exclude this now?

**Comment by ccojocar** [comment]
This is generic warning. If you are confident that what's inside that file is not going to introduce templating issues, you can ignore it.
