### ISSUE TITLE
Unexpected package creation during export data loading

### ISSUE THREAD

**Issue by MarcelXia** [securego/gosec#815]
I get an error when running gosec

### Steps to reproduce the behavior
gosec -fmt=golint -quiet ./..

(and I know there might be some workaround for this)

### gosec version
dev
gosec -version gives dev
 
### Go version (output of 'go version')
go version go1.18.2 darwin/arm64

### Operating system / Environment
Mac Monterey 12.4

### Expected behavior
is runs sucessful

### Actual behavior
it stops with this error

**Comment by cschneider4711** [comment]
Probably related to https://github.com/golang/go/issues/51629

**Comment by ccojocar** [comment]
fixed by https://github.com/securego/gosec/pull/817
