### ISSUE TITLE
gosec does not respect the go package import alias

### ISSUE THREAD

**Issue by vishaltak** [securego/gosec#820]
### Summary 

If we import `crypto/tls` with an alias( say `cryptotls`), gosec does not recognize it properly and reports issues even though it would not if it `crypto/tls` was imported without an alias.

### Steps to reproduce the behavior
1. Run gosec on the below file using command `gosec .`

```go
package main

import (
	"crypto/tls"
	cryptotls "crypto/tls"
)

func main() {
	// this will not create an issue
	_ = tls.Config{MinVersion: tls.VersionTLS12}
	// this will create an issue
	_ = cryptotls.Config{MinVersion: cryptotls.VersionTLS12}
}
```

Output:
```
~/.asdf/installs/golang/1.17.9/packages/bin/gosec .
[gosec] 2022/06/02 11:37:59 Including rules: default
[gosec] 2022/06/02 11:37:59 Excluding rules: default
[gosec] 2022/06/02 11:37:59 Import directory: /Users/vishaltak/Desktop
[gosec] 2022/06/02 11:38:00 Checking package: main
[gosec] 2022/06/02 11:38:00 Checking file: /Users/vishaltak/Desktop/test.go
Results:


[/Users/vishaltak/Desktop/test.go:12] - G402 (CWE-295): TLS MinVersion too low. (Confidence: HIGH, Severity: HIGH)
    11:         // this will create an issue
  > 12:         _ = cryptotls.Config{MinVersion: cryptotls.VersionTLS12}
    13: }



Summary:
  Gosec  : 2.11.0
  Files  : 1
  Lines  : 13
  Nosec  : 0
  Issues : 1
```

### gosec version
Version: 2.11.0
Git tag: v2.11.0
Build date: 2022-03-21T15:55:53Z

### Go version (output of 'go version')
go version go1.17.9 darwin/arm64

### Operating system / Environment
Output of `uname -a` is

```
Darwin Vishals-MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64
```

### Expected behavior
No issues should be reported by gosec when import alias is used

### Actual behavior
Issue is reported by gosec when import alias is used

**Comment by TimonOmsk** [comment]
@ccojocar Can I fix this? :)

**Comment by ccojocar** [comment]
Sure, go for it! Thanks
