### ISSUE TITLE
Confused about G204

### ISSUE THREAD

**Issue by fatsheep9146** [securego/gosec#831]
### Summary 

I'm little confused about G204 rules, when I wrote a test file, with following content 

```go
package main

import (
	"log"
	"os"
	"os/exec"
)

func RunCmdWithShortDeclartionsWithInputArgs() {
	cmdstr := os.Args[0]
	cmd := exec.Command(cmdstr)
	err := cmd.Start()
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Waiting for command to finish...")
	err = cmd.Wait()
}

func main() {
        RunCmdWithVariableDeclartionWithInputArgs()
}
```
The gosec tool will complained `Subprocess launched with variable (Confidence: HIGH, Severity: MEDIUM)`. Which I think the output is reasonable.

But when I just change `cmdstr` from short declaration to var key keyword, gosec do not complain anymore.

```go
package main

import (
	"log"
	"os"
	"os/exec"
)

func RunCmdWithVariableDeclartionWithInputArgs() {
	var cmdstr = os.Args[0]
	cmd := exec.Command(cmdstr)
	err := cmd.Start()
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Waiting for command to finish...")
	err = cmd.Wait()
}

func main() {
        RunCmdWithVariableDeclartionWithInputArgs()
}

```

So I'm confused that since the G204 is intended for making sure there isn't a potential command injection vector here, the way of variable declaration should not matter? 

### gosec version

master

### Go version (output of 'go version')

go version go1.18.1 darwin/amd64

### Operating system / Environment

macos

### Expected behavior

The way of variable declaration should not influence the gosec's behavior, no matter in short declaration `cmd := os.Args[0]` or in var keyword `var cmd = os.Args[0]`

**Comment by ccojocar** [comment]
Thanks for reporting this. It looks like a bug.

**Comment by fatsheep9146** [comment]
BTW, I'm curious about how to solve the G204 for our project. I've checked all example codes in 

https://github.com/securego/gosec/blob/0212c83699de8f57058399c07463a3c1bdebf0a1/testutils/source.go#L1812-L2021

I found that no matter how to use,  using the os.Args as input of exec.Command will always be considered as not passing the G204 rules.

But using os.Args as input is an inevitable use case for our project, is "ignoring G204 rules with `nolint` comments" the only 
choice we have? 

I have seen many related issues, but still don't find any answers.

#204 #292 #339 #343 #677 

Really hope for your advise!  =D

@ccojocar

**Comment by ccojocar** [comment]
@fatsheep9146 normally when the input comes from an external source such as os.Args, it needs to be sanitized before usage. This is because an attacker might be able to control that input and inject malicious content, specifically here an unwanted command. It is not always the case but gosec tries to warn about this potential issue. If you think that there is no way an attacker can control the input, then you can ignore the warning.
