### ISSUE TITLE
Gosec is returning a non zero exit status when --track-suppressions is used

### ISSUE THREAD

**Issue by owenwaller** [securego/gosec#832]
### Summary 

We are using gosec to scan our code base which has one necessary gosec suppression.

With gosec v2.12.0 we are now seeing a non-zero exit status code when `--track-suppressions` is enabled, This is causing our CI builds to fail when they previously passed.

Previously with gosec v2.9.6 we did not see this. Gosec v2.9.6 was the last version we were using in our Jenkins CI solution so I cannot say which version of gosec first reports this problem after v2.9.6.

### Steps to reproduce the behavior

Using this example:

```
package main

import "fmt"

func main() {
	username := "admin"
	// #nosec G101 -- Ignored to show --track-suppression behaviour
	password := "f62e5bcda4fae4f82370da0c6f20697b8f8447ef"

	fmt.Println("Doing something with: ", username, password)
}
```

With `--track-suppressions`

```
$ gosec --track-suppressions .
[gosec] 2022/07/19 18:55:58 Including rules: default
[gosec] 2022/07/19 18:55:58 Excluding rules: default
[gosec] 2022/07/19 18:55:58 Import directory: /tmp/gosec
[gosec] 2022/07/19 18:55:58 Checking package: main
[gosec] 2022/07/19 18:55:58 Checking file: /tmp/gosec/main.go
Results:


Summary:
  Gosec  : 2.12.0
  Files  : 1
  Lines  : 11
  Nosec  : 1
  Issues : 0

$ echo $?
1
```

Without `--track-suppressions`

```
$ gosec .
[gosec] 2022/07/19 18:57:01 Including rules: default
[gosec] 2022/07/19 18:57:01 Excluding rules: default
[gosec] 2022/07/19 18:57:01 Import directory: /tmp/gosec
[gosec] 2022/07/19 18:57:02 Checking package: main
[gosec] 2022/07/19 18:57:02 Checking file: /tmp/gosec/main.go
Results:


Summary:
  Gosec  : 2.12.0
  Files  : 1
  Lines  : 11
  Nosec  : 1
  Issues : 0

$ echo $?
0
```

I am aware that the `--track-suppressions`  flag is only effective for JSON and SAIRF output formats. However the behavior is the same with either of the`--fmt sairf` and `--fmt json` flags set/

### gosec version

v2.12.0

### Go version (output of 'go version')

go version go1.18.4 linux/amd64

### Operating system / Environment
```
$uname -a

Linux hostname 4.19.0-0.bpo.9-amd64 #1 SMP Debian 4.19.118-2+deb10u1~bpo9+1 (2020-06-09) x86_64 GNU/Linux
```

### Expected behavior

The exit status should be zero if the number of issues is zero, regardless of the use of `--track-suppressions` because the gosec false positive is suppressed.

### Actual behavior

The exit status is non-zero (1) even though the gosec false positive is suppressed and there are no other gosec failures,

Can we revert to the v2.9.6 behaviour, as that does not break our CI builds unnecessarily?

Many thanks

Owen

**Comment by ccojocar** [comment]
This looks like a bug, thanks for reporting it.
