### ISSUE TITLE
Pointer not declared by package atomic

### ISSUE THREAD

**Issue by Aoang** [securego/gosec#847]
### Summary 
Pointer not declared by package atomic

### Steps to reproduce the behavior
use https://github.com/golang/go/blob/go1.19/src/sync/atomic/type.go#L39

### gosec version
securego/gosec@master

### Go version (output of 'go version')
go version go1.19 linux/amd64

### Operating system / Environment
Ubuntu Latest, GitHub Action

### Expected behavior
nothing will happen

### Actual behavior
```
Results:

Golang errors in file: [/github/workspace/pool/gopool.go]:

  > [line 23 : column 45] - Pointer not declared by package atomic
```

https://github.com/FlowerLab/sorbifolia/runs/7817888253?check_suite_focus=true

**Comment by ccojocar** [comment]
Thanks for reporting this. The action is using the latest release `v2.12.0` which was done prior to Go 1.19. The Go 1.19 will be supported in the next release.
