### ISSUE TITLE
Unexpected package creation during export data loading

### ISSUE THREAD

**Issue by jintao-zero** [securego/gosec#848]
### Summary 
        i use gitlab to repo my project.
        when i run gosec 3.5.3 to check my project , it report this message: "Unexpected package creation during export data loading".  but if i run gosec 3.5.2 ， it's ok.

### Steps to reproduce the behavior
docker run -it --rm -v /Users/***/go:/go --volume "$PWD":/tmp/app --env CI_PROJECT_DIR=/tmp/app registry.gitlab.com/security-products/gosec:3.5.3 sh
/bin/gosec /tmp/app/...

### gosec version
3.5.3
### Go version (output of 'go version')
go version go1.19 linux/amd64
### Operating system / Environment
go version go1.19 linux/amd64
### Expected behavior
pass scan
### Actual behavior
Unexpected package creation during export data loading

**Comment by ccojocar** [comment]
The released version of gosec doesn't support yet Go 1.19. You can try to use the master version and hopefully the next release will support Go 1.19. Thanks
