### ISSUE TITLE
Github Action cannot pull private Go modules

### ISSUE THREAD

**Issue by mvs5465** [securego/gosec#851]
### Summary 

This is a reopen request for https://github.com/securego/gosec/issues/490 as the issue is still present.

When using private golang modules stored in Github, you must authenticate with the repositories in order to download them. The recommended fix for this is to use ssh or token authentication indicated by a git config URL override:
```
git config --global url.git@github.com:.insteadOf https://github.com/
```

However because the gosec action runs inside a Docker container, the git fix above is not propagated and thus, private dependencies cannot be scanned. The resulting error message looks a bit like this:

```
fatal: could not read Username for 'https://github.<enterprise url>.com': No such device or address
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
```

### Steps to reproduce the behavior

Use a private dependency then attempt to scan it with the Github action.

### gosec version

n/a

### Go version (output of 'go version')

n/a

### Operating system / Environment

n/a

### Expected behavior

Git config propagated to inside of gosec action. 

### Actual behavior

The gosec action is not configurable enough to allow git URLs to be overridden.

**Comment by ccojocar** [comment]
Thanks for reporting this but this cannot be fixed on gosec level. You need to mount your private ssh keys inside of the container used by gosec. This is how Github actions work. Thanks
