### ISSUE TITLE
error calling SprintID: runtime error: invalid memory address or nil pointer dereference with v2.13.0

### ISSUE THREAD

**Issue by mblaschke** [securego/gosec#852]
### Summary 
i'm getting an `invalid memory address or nil pointer dereference` with v2.13.0:

```
[/Users/mblaschke/Projects/webdevops/azure-scheduledevents-manager/main.go:258] - G114 ([gosec] 2022/08/19 09:20:19 template: gosec:9:155: executing "gosec" at <$issue.Cwe.SprintID>: error calling SprintID: runtime error: invalid memory address or nil pointer dereference
make: *** [gosec] Error 1
```

### Steps to reproduce the behavior
run gosec against https://github.com/webdevops/azure-scheduledevents-manager

### gosec version

`2.13.0`

### Go version (output of 'go version')
`go version go1.19 darwin/arm64`

### Operating system / Environment
`macOS` (and on github runners)

### Expected behavior
not failing :)

### Actual behavior
fails

**Comment by dgbittner** [comment]
I am also getting this error in our build pipeline as per description above...
