### ISSUE TITLE
Gosec Docker Action run completed with exit code 1

### ISSUE THREAD

**Issue by davidaparicio** [securego/gosec#861]
### Summary 

We are using gosec to scan our code base and generate the SARIF file (Integration with code scanning cf gosec README)

```
[gosec] 2022/08/31 07:29:16 Checking package: main
[gosec] 2022/08/31 07:29:16 Checking file: /github/workspace/cmd/server/main.go
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Run Gosec Security Scanner
```

The part of log has been taken from [here](https://github.com/davidaparicio/namecheck/runs/8108357252?check_suite_focus=true#step:4:46)

### Steps to reproduce the behavior

Run on GitHub the workflow
https://github.com/davidaparicio/namecheck/blob/main/.github/workflows/gosec-analysis.yml

### gosec version 

Tried with master and v2.12.0 of the GitHub action (` uses: securego/gosec@v2.12.0 #master `)

### Go version (output of 'go version')

Go version of docker.io/securego/gosec:latest

### Operating system / Environment

Github runners / Current runner version: '2.296.0'
Image: ubuntu-20.04
Version: 20220828.1

### Expected behavior

No failure, or at least, an error message.
We remove `-no-fail` argument, but no message too.

### Actual behavior

The exit status is non-zero (1) and there are no other gosec failures.
The first failure was [1 week ago](https://github.com/davidaparicio/namecheck/actions/runs/2925858495)
We revert to the v2.12.0 behaviour, without success ([run failed](https://github.com/davidaparicio/namecheck/actions/runs/2962021702)). Since 2 weeks from the last successful [run](https://github.com/davidaparicio/namecheck/actions/runs/2881772015)

**Comment by ccojocar** [comment]
Please could you try out the latest release v2.13.1 instead of v2.12.0? Could yous still reproduce the issue? Thanks

**Comment by davidaparicio** [comment]
Hi @ccojocar, I have reproduce the issue => the same exit code without error message even warning...
https://github.com/davidaparicio/namecheck/runs/8110200485?check_suite_focus=true#step:4:9

**Comment by ccojocar** [comment]
@ccojocar Is this the project you are trying to scan` git@github.com:davidaparicio/namecheck.git`? If I run locally gosec against this project `./gosec -fmt sarif -out results.sarif ./...` , it finds some issues and obviously returns a non-zero exit code. This is the sarif result:
```
{
	"runs": [
		{
			"results": [
				{
					"level": "error",
					"locations": [
						{
							"physicalLocation": {
								"artifactLocation": {
									"uri": "cmd/server/main.go"
								},
								"region": {
									"endColumn": 12,
									"endLine": 52,
									"snippet": {
										"text": "if err := http.ListenAndServe(\":8080\", nil); err != nil {"
									},
									"sourceLanguage": "go",
									"startColumn": 12,
									"startLine": 52
								}
							}
						}
					],
					"message": {
						"text": "Use of net/http serve function that has no support for setting timeouts"
					},
					"ruleId": "G114"
				}
			],
			"taxonomies": [
				{
					"downloadUri": "https://cwe.mitre.org/data/xml/cwec_v4.4.xml.zip",
					"guid": "f2856fc0-85b7-373f-83e7-6f8582243547",
					"informationUri": "https://cwe.mitre.org/data/published/cwe_v4.4.pdf/",
					"isComprehensive": true,
					"language": "en",
					"minimumRequiredLocalizedDataSemanticVersion": "4.4",
					"name": "CWE",
					"organization": "MITRE",
					"releaseDateUtc": "2021-03-15",
					"shortDescription": {
						"text": "The MITRE Common Weakness Enumeration"
					},
					"version": "4.4"
				}
			],
			"tool": {
				"driver": {
					"guid": "8b518d5f-906d-39f9-894b-d327b1a421c5",
					"informationUri": "https://github.com/securego/gosec/",
					"name": "gosec",
					"rules": [
						{
							"defaultConfiguration": {
								"level": "error"
							},
							"fullDescription": {
								"text": "Use of net/http serve function that has no support for setting timeouts"
							},
							"help": {
								"text": "Use of net/http serve function that has no support for setting timeouts\nSeverity: MEDIUM\nConfidence: HIGH\n"
							},
							"id": "G114",
							"name": "G114",
							"properties": {
								"precision": "high",
								"tags": [
									"security",
									"MEDIUM"
								]
							},
							"relationships": [
								null
							],
							"shortDescription": {
								"text": "Use of net/http serve function that has no support for setting timeouts"
							}
						}
					],
					"semanticVersion": "dev",
					"supportedTaxonomies": [
						{
							"guid": "f2856fc0-85b7-373f-83e7-6f8582243547",
							"name": "CWE"
						}
					],
					"version": "dev"
				}
			}
		}
	],
	"$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
	"version": "2.1.0"
}
```

If you want the action to return a zero exit code and not break your build, you should fix these issues first.

This doesn't seem like an issue. It is expected behaviour. I am going to close it.

**Comment by davidaparicio** [comment]
Yes, the scan is against git@github.com:davidaparicio/namecheck.git :)

Okay, weird because an [old GitHub job](https://github.com/davidaparicio/namecheck/actions/runs/2925858495) said:

> Unable to upload "results.sarif" as it is not valid SARIF:
> - instance.runs[0].tool.driver.rules[0].relationships[0] is not of a type(s) object
