### ISSUE TITLE
G109 is missing

### ISSUE THREAD

**Issue by eumel8** [securego/gosec#878]
Gitlab SAST points me to a critical issue on my scanned Go Code:

Integer Overflow or Wraparound
    
```
Identifiers 
            CWE-190
            Gosec Rule ID G109     
            gosec.G109-1
          
```

identified code:

```go
Port:       int32(iport)
```

No idea what's wrong here. Couldn't found any advices in the guideline. Would be good to have something [here](https://securego.io/docs/rules/g109.html)

**Comment by ccojocar** [comment]
duplicate of #127
