### ISSUE TITLE
Should `defer resp.Body.Close()` not be marked as G307?

### ISSUE THREAD

**Issue by 030** [securego/gosec#890]
defer resp.Body.Close()

does not seem to be marked as G307

but if

```
	file, err := os.Open(filepath.Clean(""))
	if err != nil {
		return nil
	}
	defer file.Close()
```
is used then a G307 is reported.

**Comment by TimonOmsk** [comment]
I think we should mark all deferred "Close" methods which returns "error" as the G307 issue

**Comment by szuecs** [comment]
@TimonOmsk can you explain how an http.Body.Close() after a successful response can happen to fail?
I mean I/O with devices, kernel abstractions and filesystems is completely different and this issue should have been closed with won't fix, because it makes no sense IMO.

**Comment by AlexanderYastrebov** [comment]
I think `defer rsp.Body.Close()` is very common and the tool should probably treat it differently from other `io.ReadCloser`s
