### ISSUE TITLE
unable to suppress G307 with configuration

### ISSUE THREAD

**Issue by varkey98** [securego/gosec#900]
### Summary 
Tried to suppress G307 issue similar to G104 as mentioned in the readme file
```
{
    "G307": {
            "os.File": ["Close"]
    }
}

```

### Steps to reproduce the behavior
`defer os.File.Close()`
run with this conf:
```
{
    "G307": {
            "os.File": ["Close"]
    }
}
```

### gosec version
Version: dev
Git tag:
Build date:

### Go version (output of 'go version')
go version go1.18.5 linux/amd64

### Operating system / Environment
Ubuntu x64

### Expected behavior
Dont know if this rule is supported, if it is then this code should not have flagged.

### Actual behavior
This code snippet is getting flagged in the gosec report.

**Comment by ccojocar** [comment]
ruled removed in https://github.com/securego/gosec/issues/900
