### ISSUE TITLE
Support for Linux on IBM Z ( s390x )

### ISSUE THREAD

**Issue by davidhay1969** [securego/gosec#901]
### Summary 

Query: is there any possibility to get `s390x` binaries for `gosec` added to the Releases page ?

I'm able to build `gosec` from source on an IBM Z box running Ubuntu 18.04

`git clone git@github.com:securego/gosec.git $GOPATH/src/github.com/gosec`

`cd $GOPATH/src/github.com/gosec`

`make`

```text
make build
make[1]: Entering directory '/home/hayd/go/src/github.com/gosec'
go build -o gosec ./cmd/gosec/
make[1]: Leaving directory '/home/hayd/go/src/github.com/gosec'
```

`file gosec`

```text
gosec: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), dynamically linked, interpreter /lib/ld64.so.1, with debug_info, not stripped
```

`./gosec --version`

```text
Version: dev
Git tag:
Build date:
```

so it's doable ...

I'm guessing that having access to an IBM Z build box would be part of the equation 😁 

Any view ?

**Comment by ccojocar** [comment]
I think you can add it here https://github.com/securego/gosec/blob/f79c584dbbec47a01a69adbe3e2e96f54bbe74d6/.goreleaser.yml#L18. 

Please could you also validate that goreleaser works properly with this architecture?

Thanks

**Comment by davidhay1969** [comment]
Hey Cosmin

Thanks, will check out the change to `.goreleaser.yml`

In terms of the `goreleaser` binary itself, yes, I'm able to build that on a `s390x` box: -

`go version`

```text
go version go1.19.3 linux/s390x
```

`git clone git@github.com:goreleaser/goreleaser.git $GOPATH/src/github.com/goreleaser`

`cd $GOPATH/src/github.com/goreleaser`

`go build .`

`file goreleaser`

```text
goreleaser: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), dynamically linked, interpreter /lib/ld64.so.1, with debug_info, not stripped
```

`./goreleaser -v`

```text
goreleaser version dev
goos: linux
goarch: s390x

https://goreleaser.com
```

`go test -v .`

```text
=== RUN   TestVersion
=== RUN   TestVersion/complete
=== RUN   TestVersion/only_version
=== RUN   TestVersion/version_and_date
=== RUN   TestVersion/version,_date,_built_by
=== RUN   TestVersion/all_empty
--- PASS: TestVersion (0.00s)
    --- PASS: TestVersion/complete (0.00s)
    --- PASS: TestVersion/only_version (0.00s)
    --- PASS: TestVersion/version_and_date (0.00s)
    --- PASS: TestVersion/version,_date,_built_by (0.00s)
    --- PASS: TestVersion/all_empty (0.00s)
PASS
ok  	github.com/goreleaser/goreleaser	0.017s
```

**Comment by ccojocar** [comment]
Feel free to open a pull request with the change. Thanks for contributing!

**Comment by davidhay1969** [comment]
Incoming 🤣 🙇‍♂️ 
[ Adding s390x support #902 ](https://github.com/securego/gosec/pull/902)

**Comment by davidhay1969** [comment]
Hey @ccojocar thanks for reviewing/approving/merging the [ Adding s390x support #902 ](https://github.com/securego/gosec/pull/902)

Daft question, perhaps, but what's the next step ? Looking at the `gosec` [releases](https://github.com/securego/gosec/releases) page, the most recent build is `v2.14.0` dated October 17 - do we need to wait for the next release to see whether `goreleaser` has helped in terms of getting a `s390x` build that I can play with ?

Apologies for the dumb question ....

**Comment by ccojocar** [comment]
There will be a version released for IBM Z when we will do the next release. The binary will automatically attached to the Github's release by the release action.
