### ISSUE TITLE
Check fails with cryptic error when run from parent dir

### ISSUE THREAD

**Issue by madmaxoft** [securego/gosec#915]
### Summary 

(Sorry if I'm doing anything wrong, I'm a total Go newbie)

I'm trying to use gosec to check a rather large codebase that uses modules and Go 1.19. When running `gosec .` in a folder of one of the modules, it succeeds; however, when running `gosec modulefolder` from the parent folder of the module, the check fails with a cryptic message:
```
parsing errors in pkg "eplist": parsing line: strconv.Atoi: parsing "\\Programy\\gosec-min-repro\\eplist\\a.go": invalid syntax
```
I have managed to reduce the repro case to only a few lines of code, attached below.

### Steps to reproduce the behavior

Create a folder `eplist`, and in it, file `a.go` with the following contents:
```
package eplist

import (
	goplist "howett.net/plist"
)

func Un(data []byte, out interface{}) (err error) {
	_, err = goplist.Unmarshal(data, out)
	return
}
```

Add the `go.mod` file:
```
module eplist

go 1.18

require howett.net/plist v1.0.0 
```

Run `gosec .` from the `eplist` folder, it should succeed. Run `gosec eplist` from the parent folder, it fails. Run gosec from any other folder (with absolute or relative path to `eplist` as parameter) and it fails with the same error.

### gosec version
```
$>gosec --version
Version: dev
Git tag:
Build date:
```
Not much useful; I believe it is version `v2@v2.13.1`, since a folder of such name is in my `$GOPATH/pkg/mod/github.com/securego/gosec` folder.

### Go version (output of 'go version')
`go version go1.19.3 windows/amd64`

### Operating system / Environment
Windows 10

### Expected behavior

Consistent behavior between runs from the module folder and from its parent folder.
If an error is reported, include more details, such as line number.

### Further notes

What I'm trying to achieve in the end is a script that checks all in-house modules used by our main module, as well as that main module, in a single `gosec` invocation (so that the output is all in a single file). For that, I'm recursively parsing the go.mod files of the in-house modules for all local folders containing the code, and then passing all those folders to `gosec` in a single invocation.

**Comment by madmaxoft** [comment]
Note: As for the Further notes, my approach seems to work for 30+ other modules, only one fails, it seems to be related to the `howett.net/plist` package, but I have no idea what's wrong.

**Comment by ccojocar** [comment]
I think the problems is that you are missing the go module file in the root folder. It works fine if I have something like this:
```
tree .
.
├── eplist
│   └── a.go
├── go.mod
└── go.sum

2 directories, 3 files
```
the result is:
```
gosec ./...
[gosec] 2023/01/26 18:25:27 Including rules: default
[gosec] 2023/01/26 18:25:27 Excluding rules: default
[gosec] 2023/01/26 18:25:27 Import directory: /Users/cosmin/go/src/github.com/securego/samples/goplist/eplist
[gosec] 2023/01/26 18:25:27 Checking package: eplist
[gosec] 2023/01/26 18:25:27 Checking file: /Users/cosmin/go/src/github.com/securego/samples/goplist/eplist/a.go
Results:


Summary:
  Gosec  : dev
  Files  : 1
  Lines  : 10
  Nosec  : 0
  Issues : 0

```

In Go you need to define a go module in the root folder of you repository, the subfolder `eplist` is a package not a module. I hope this helps.

**Comment by nohajc** [comment]
Hi, related to this, I would like to know how to handle the case when you need to scan more than one separate go modules which don't necessarily share a common root.

I've already verified that it is possible to pass multiple directories to the gosec command so that I get a unified output for all the input modules.

What you suggest would mean that gosec always looks for go.mod in the current working directory and not the directory specified on command line.

**Comment by nohajc** [comment]
@ccojocar And if anything, the error message about invalid syntax is misleading as the module can be obviously compiled without error. Respectfully, this issue should be reopened.

**Comment by ccojocar** [comment]
What's the output of `go build` command when you run it in the same folder like `gosec`?

**Comment by nohajc** [comment]
No output. It just works. Exit code 0.
Here's the code:
[test.zip](https://github.com/securego/gosec/files/10520128/test.zip)

When you run `gosec .` in `test/gosec_example_0`, it works. If you run `gosec gosec_example_0/` from `test` it doesn't. If this is the expected behavior, I don't understand why...

**Comment by nohajc** [comment]
Checking the source code, the error message might be coming from here:
https://github.com/securego/gosec/blob/master/analyzer.go#L329

Which looks like it's trying to parse a string as line number but that string is in fact a file path...

**Comment by ccojocar** [comment]
I agree the error is cryptic but also the `go build` doesn't seem to work for me:
```
gosec gosec_example_0
[gosec] 2023/01/27 16:15:39 Including rules: default
[gosec] 2023/01/27 16:15:39 Excluding rules: default
[gosec] 2023/01/27 16:15:39 Import directory: /Users/gcojocar/Downloads/test/gosec_example_0
[gosec] 2023/01/27 16:15:39 Checking package: eplist
[gosec] 2023/01/27 16:15:39 Checking file: /Users/gcojocar/Downloads/test/gosec_example_0/a.go
Results:

Golang errors in file: [/Users/gcojocar/Downloads/test/gosec_example_0/a.go]:

  > [line 4 : column 10] - could not import howett.net/plist (invalid package name: "")



Summary:
  Gosec  : dev
  Files  : 1
  Lines  : 10
  Nosec  : 0
  Issues : 0
```

```
go build gosec_example_0
package gosec_example_0 is not in GOROOT (/Users/cosmin/.gvm/gos/go1.19.5/src/gosec_example_0)
echo $?
1
```

BTW the error is returned by the go build underlying parser which is used by gosec. The go build errors are transparent, gosec just reports them further.

**Comment by nohajc** [comment]
Ok, so let me reword the question. Why does `gosec` call `go build gosec_example_0` and not `cd` into gosec_example_0` before calling `go build .`?

Does it mean it's not possible to scan a module by specifying the module path while not being in the module directory?
What is even the purpose of the command line argument if gosec will only work when run from the go module directory (implying `gosec .` regardless of the path passed`)?

**Comment by ccojocar** [comment]
> Does it mean it's not possible to scan a module by specifying the module path while not being in the module directory?
What is even the purpose of the command line argument if gosec will only work when run from the go module directory (implying gosec . regardless of the path passed)?

It is, because it is possible to scan specific packages inside of the module, relative to the module root folder.

**Comment by nohajc** [comment]
Ok, so that means you can also scan multiple specific packages by one invocation but they must all live inside one module, right?

Any chance gosec could be improved to handle multiple modules at once so that you get unified report?

**Comment by ccojocar** [comment]
No plans to do this. Thanks for suggestion.

**Comment by nohajc** [comment]
Ok, thank you for clarification.

**Comment by madmaxoft** [comment]
I think the original problem still needs addressing: There IS a cryptic error message output by `gosec`. Even if it is from incorrect usage, the error message doesn't help the user at all, and indicates a problem in `gosec` code.
Also, the documentation should clarify the usage across modules / packages.
