### ISSUE TITLE
Unable to install latest gosec sometimes

### ISSUE THREAD

**Issue by malisetti** [securego/gosec#919]
### Summary
Doing the below to install the latest gosec, sometimes it installs and sometimes it fails with 
`wget -O - -q https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh`
```
securego/gosec info checking GitHub for latest tag
securego/gosec crit unable to find '' - use 'latest' or see https://github.com/securego/gosec/releases for details
```

### Steps to reproduce the behavior
Not sure, `wget -O - -q https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh` produces both the cases
### Go version (output of 'go version')
1.17.13

### Operating system / Environment
docker/golang:1.17 

### Expected behavior
Either fail every time or succeed every time

### Actual behavior
Sometimes installs latest gosec version and sometimes not

**Comment by ccojocar** [comment]
This seems like a GitHub issues.

**Comment by danninov** [comment]
I also have this problem. Is there any solution to this?

**Comment by joelngwt** [comment]
It's not sometimes for me, it's failing every time with the following command, it used to work:

```
curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest

securego/gosec info checking GitHub for tag 'latest'
securego/gosec crit unable to find 'latest' - use 'latest' or see https://github.com/securego/gosec/releases for details
```
