### ISSUE TITLE
Unable to run gosec using config file

### ISSUE THREAD

**Issue by pankajpantkappa** [securego/gosec#930]
### Summary 
Unable to run gosec with custom config file

### Steps to reproduce the behavior
1. create a config file called `gosec.toml` with these lines
    `severity = "medium"`
2. run command `gosec -conf gosec.toml ./..`
3. It gives error: `[gosec] 2023/02/11 23:58:48 invalid character 's' looking for beginning of value`   

### gosec version
Version: v2.15.0
### Go version (output of 'go version')
go 1.18

### Operating system / Environment
macOS

### Expected behavior
The command runs successfully.
### Actual behavior
It always gives error

**Comment by ccojocar** [comment]
`severity` is not supported in the config file, you can use the command line argument `severity` to set the severity level. Thanks
