### ISSUE TITLE
Problems with gopkg.in dependecy

### ISSUE THREAD

**Issue by tuxillo** [securego/gosec#965]
### Summary 

Pulling securego/gosec occassionally produces `gopkg.in/yaml.v3: unrecognized import path "gopkg.in/yaml.v3": reading https://gopkg.in/yaml.v3?go-get=1: 502 Bad Gateway` errors.

Is there any reason to not use directly this repo: https://github.com/go-yaml/yaml/tree/v3 ?

### Steps to reproduce the behavior

```
while true
do
    echo again
    rm -fr ${HOME}/go/src/gopkg.in ${HOME}/go/src/github.com/securego
    GO111MODULE=off go get -u github.com/securego/gosec/cmd/gosec
    sleep 10
done
```
### gosec version

Dunno, it fails to pull 😅

### Go version (output of 'go version')

```
go version go1.19.3 darwin/arm64
```

### Operating system / Environment

MacOS (but also happens in Linux, etc)

### Expected behavior

Actually pull gosec

### Actual behavior

```
package gopkg.in/yaml.v3: unrecognized import path "gopkg.in/yaml.v3": reading https://gopkg.in/yaml.v3?go-get=1: 502 Bad Gateway
	server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-yaml/yaml.git/info/refs?service=git-upload-pack: write tcp 10.131.9.188:60820->140.82.121.3:443: write: broken pipe
again
package gopkg.in/yaml.v3: unrecognized import path "gopkg.in/yaml.v3": reading https://gopkg.in/yaml.v3?go-get=1: 502 Bad Gateway
	server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-yaml/yaml.git/info/refs?service=git-upload-pack: write tcp 10.131.9.188:60820->140.82.121.3:443: write: broken pipe
```

**Comment by ccojocar** [comment]
Thanks for reporting this but I am afraid we cannot do much about this unless there is another packages repository which is more reliable. 

If this is critical to you, you can try to use directly the exiting binary instead of compiling it every time.

**Comment by tuxillo** [comment]
Not sure why this is closed. The only use of gopkg.in I can see is in yaml.v3 and I already pointed out to another repo which, if I'm not wrong, provides exactly the same lib.

**Comment by ccojocar** [comment]
As far as I can see the yaml.v3 is provided only by this package https://pkg.go.dev/gopkg.in/yaml.v3@v3.0.1. Could you provide the link to the other repository? Thanks

**Comment by ccojocar** [comment]
The Github repository is using the gopkg.in/yaml.v3 module path: https://github.com/go-yaml/yaml/blob/v3/go.mod also this is mentioned in the installation instructions in the README file. 

There is not alternative as far I can see.

**Comment by tuxillo** [comment]
@ccojocar you're right! Thanks a lot for checking.
