### ISSUE TITLE
Vulnerabilities with "tls-observatory" module

### ISSUE THREAD

**Issue by yuri-potatoq** [securego/gosec#972]
### Summary 
The module `github.com/mozilla/tls-observatory` has several registered vulnerabilities. Like:
[SNYK-1083907](https://security.snyk.io/vuln/SNYK-GOLANG-GOETCDIOETCDV3ETCDSERVER-1083907)
[SNYK-1083902](https://security.snyk.io/vuln/SNYK-GOLANG-GOETCDIOETCDV3ETCDMAIN-1083902)
[SNYK-1083945](https://security.snyk.io/vuln/SNYK-GOLANG-GOETCDIOETCDV3EMBED-1083945)

The module is used to handle some cipher constants at one single place.
https://github.com/mozilla/tls-observatory/blob/master/constants/ciphersuites.go#L21

My question is if there are another module where we can grab this information, or we can dump the version of  `certificate-transparency-go` to a new one. Which i think will fix this vulnerabilities ([mod](https://github.com/mozilla/tls-observatory/blob/master/go.mod#L8))

### Steps to reproduce the behavior
Current behavior.

### gosec version
v2.16.0

### Go version (output of 'go version')
1.19.0

### Operating system / Environment
For all.

### Expected behavior
Use another module to get the constants or dump the version of `certificate-transparency-go` which has
a new version  of `go.etcd.io/etcd`
### Actual behavior
Using constants from a vulnerable module.

**Comment by ccojocar** [comment]
Thanks for reporting this, but this is package is not used by the gosec tool but by the generator which generates the tls rule which contains the list of ciphers. This rule gets compiled compiled into gosec but has no dependencies to tls-observatory. 

There is not a major security risk using this module just for generator tool.
