### ISSUE TITLE
Proposal: merge G201 and G202 into a single SQL injection rule

### ISSUE THREAD

**Issue by audunmo** [securego/gosec#990]
### Summary 

Currently, there are two separate rules governing SQL injection reporting in gosec, G201 SQL injection via string formatting and G202 SQL injection via string concatenation.
_What I propose is that these should be merged into a single G201 SQL Injection rule, in order to improve usability, and ease further development_

The primary benefit to this is that you get a cleaner interface. The strategies, concat and formats, are really an internal representation. They're _how_ gosec finds SQL injection, and not really materially different in impact for the user. After all, either your app is affected by SQLi or not, it's not really important to you if that is happening via string formats or string concats. The distinction matters to gosec internally, but I doubt it much matters to gosecs users. 

Additionally, if and when you're faced with adding a new SQL injection detection strategy, you're now faced with adding an entirely new rule to gosec. This can be awkward, as for example the existing rules for SQL injection are G201 and G202, but there are non-SQLi rules on G203 and G204. Adding a new one will mean it will be added as G205, not neatly grouped together with G201/202. See  #988 for a concrete example of a potential new strategy.

The primary drawback is of course that we'd have to change the API of gosec, by removing one of the rules. This requires a new major-version release, for something that feels like a minor change to the users. I'd argue that this is an acceptable trade-off, but I don't want to rock the boat too hard with a major version without discussion

### Specifics

I propose that we keep the G201 rule, rename it SQL Injection, and retire the use of G202 as a rule identifier. All of the existing G202 cases will be covered in the new G201

In practice I imagine this as implemented something like this:
- G202 is rewritten so that its code can both be active as a standalone rule, and be reused as part of G201.
- G201 will now cover both cases, with G202 continuing to exist until the next major release
- User mentions of G202, via for example `nosec`, should print a deprecation warning, letting them know that in the next major version G202 will be removed, and that they should start using G201 to keep their workflows the same.
- In the next major release, G202 is removed as a standalone rule.

This way, the switch over to new rule-identifiers should be relatively painless for users.

**Comment by ccojocar** [comment]
Thanks for proposing this. It makes sense to refactor those two rules. We can deprecate the G202 and rename the G201 to be more generic as you are suggesting. In the README, we keep a list of rules which were deprecated or removed.

**Comment by ccojocar** [comment]
Even better, we can rewrite these two rules in one analyser using the new parsing infrastructure based on SSA, see https://github.com/securego/gosec/blob/master/analyzers/ssrf.go.

**Comment by audunmo** [comment]
Cool! Would that mean that the code moves away from using the ast package for finding node types then? Just want to confirm I'm understanding this correctly 😊 @ccojocar

**Comment by ccojocar** [comment]
The plan is to migrate some rules overtime to SSA, but we can use both where it makes sense. SSA provides better support for taint analysis, and it will allow us to detect more complex issues across the call graph.

**Comment by audunmo** [comment]
Gotcha, sounds like a good time to perform that migration. Would it be preferable to then also move it away from the rules package, and into the analyzer package, like in the example?

**Comment by audunmo** [comment]
I've begun work on merging these two

**Comment by ccojocar** [comment]
@audunmo are you still planing to contribute something for this? I am going to close if for now. Please feel free to reference it in your pull request. Thanks

**Comment by audunmo** [comment]
Yeah, sorry life happened! Will reference this issue once things chill out again
