### ISSUE TITLE
Document context for every rule

### ISSUE THREAD

**Issue by mcandre** [securego/gosec#994]
The documentation has numerous gaps. Can we please get an entry in https://securego.io/docs/rules/rule-intro for each rule that gosec applies by default?

For example, I have no idea what to make of `G204`. This rule is triggering on projects where I curry some common CLI command prefixes for build system convenience. I'm inclined to disable this rule entirely, but I would prefer to be able to read a gosec documentation page for the rule instead of blindly ignoring security advice.

**Comment by ccojocar** [comment]
This is a duplicate https://github.com/securego/gosec/issues/127
