### ISSUE TITLE
Update docker image to go 1.21

### ISSUE THREAD

**Issue by Schwartz-Matthew-bah** [securego/gosec#999]
### Summary 

The `securego/gosec:latest` image is still using go version 1.20.4 which is incompatible with gosec as it now relies on the toolchain directive.

### Steps to reproduce the behavior

Run `docker run --entrypoint '' securego/gosec:latest go version` in a terminal

It outputs `go version go1.20.4 linux/amd64`

### Expected behavior

Image should use go 1.21 and gosec should execute successfully.

### Actual behavior

Running gosec inside the image produces the following error due to being on version 1.20.4

```
err: exit status 1: stderr: go: errors parsing
unknown directive: toolchain\n
```

**Comment by ccojocar** [comment]
There is a new release which was built with go 1.21.0: https://github.com/securego/gosec/releases/tag/v2.17.0
